fix: fix tabs urls on progress tab
openedx/frontend-app-learning pull request #1009
Opened 2022-12-06 10:43 UTC by ghassanmas

This fix does fixes the url links by getting them from the state
 simliar to how tabs navigation gets them.

 This would allow it work for PUBLIC_PATH is not '/', i.e. in
 tutor.

  This was reported in openedx/build-test-release-wg/issues/222

2022-12-06 10:44 UTC, openedx-webhooks commented
Thanks for the pull request, @ghassanmas!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-12-06 11:25 UTC, mariajgrimaldi commented
Thank you @ghassanmas for taking this on! I was testing it in my local environment and I keep getting this error:
![image](https://user-images.githubusercontent.com/64440265/205899155-719490e1-5ecf-40fe-ac35-f6a7aa8071f0.png)

Am I testing this wrong?

2022-12-06 11:36 UTC, ghassanmas commented
Sorry, I replied to issue for question, https://github.com/openedx/build-test-release-wg/issues/222#issuecomment-1339184975

2022-12-06 14:29 UTC, itsjeyd commented
@ghassanmas Thank you for your contribution! Just to confirm, is it ready for review?

2022-12-06 14:30 UTC, ghassanmas commented
Yes it is. 

> On 6 Dec 2022, at 16:29, Tim Krones ***@***.***> wrote:
> 
> 
> @ghassanmas <https://github.com/ghassanmas> Thank you for your contribution! Just to confirm, is it ready for review?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/openedx/frontend-app-learning/pull/1009#issuecomment-1339472918>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AD42PH4XBZ5ZNIRKMM6LH7LWL5EVPANCNFSM6AAAAAASVLCOUM>.
> You are receiving this because you were mentioned.
>

2022-12-07 12:43 UTC, arbrandes requested changes

2022-12-07 12:43 UTC, arbrandes commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +      destination={tabs.find(({ slug }) => slug === 'outline').url}
You'll need to do something similar to what [this other page](https://github.com/openedx/frontend-app-learning/blob/master/src/courseware/course/course-exit/CourseInProgress.jsx#L27-L28) does, otherwise the destination might be null.

```javascript
const datesTab = tabs.find(tab => tab.slug === 'dates');
const datesTabLink = datesTab && datesTab.url;
...
{datesTabLink && (
  <Component />
)}
```

2022-12-07 12:43 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +          <Hyperlink destination={tabs.find(({ slug }) => slug === 'dates').url} onClick={() => logLinkClicked('dates')}>
Same as above.  You'll need to make this link optional, depending on whether that tab exists or not.

2022-12-07 12:45 UTC, arbrandes commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +      destination={tabs.find(({ slug }) => slug === 'outline').url}
This is why @mariajgrimaldi was seeing an error, btw.

2022-12-07 13:52 UTC, arbrandes requested changes
Made a few comments.

In general, please make sure the indentation follows the pattern set by the rest of the code.

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
>    const outlineLink = (
You also need to check here that the Url exists.  Something like:

```suggestion
  const outlineLink = !overviewTabUrl ? "" : (
```

(I haven't tested the syntax.)

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +        overviewTabUrl && (
```suggestion
      {overviewTabUrl && (
```

Let's stick to the indentation pattern set above.

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +}
```suggestion
      )}
```

Indentation.

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +    org, tabs,
```suggestion
    org,
    tabs,
```

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +            getTabUrlifExits('dates') && (
```suggestion
        {datesTabUrl && (
```

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +
```suggestion
```

Remove whitespace.

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +              <Hyperlink destination={getTabUrlifExits('dates')} onClick={() => logLinkClicked('dates')}>
```suggestion
              <Hyperlink destination={datesTabUrl} onClick={() => logLinkClicked('dates')}>
```

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +}
```suggestion
        )}
```

Indentation.

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +  getTabUrlifExits('outline') && (
```suggestion
        {overviewTabUrl && (
```

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +  };
There are only two links, and we're not doing anything fancy.  I don't think we need this function.

```suggestion
const overviewTab = tabs.find(tab => tab.slug === 'outline');
const overviewTabUrl = overviewTab && overviewTab.url;
const datesTab = tabs.find(tab => tab.slug === 'dates');
const datesTabUrl = datesTab && datesTab.url;
```

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +    <Hyperlink destination={getTabUrlifExits('outline')} onClick={() => logLinkClicked('course_outline')}>
```suggestion
    <Hyperlink destination={overviewTabUrl} onClick={() => logLinkClicked('course_outline')}>
```

2022-12-07 13:52 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +}
```suggestion
        )}
```

Indentation.

2022-12-07 14:00 UTC, ghassanmas commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +}
That's the es-lint auto-fix, because I added extra check porbably...

2022-12-07 14:03 UTC, ghassanmas commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +  };
It's redudant logic though, defining 4 variables instead of function would sound cleaner to me.... I can change it if you have strong feeling to though

2022-12-07 14:16 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +  };
It's redundant, but if implemented like you suggest, you'll be calling the `find` two more times than necessary, below.  In other words, it's not just about readability, it's about efficiency.

2022-12-07 14:17 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +}
If this is what eslint is generating, then eslint is broken. 🤷🏼‍♂️

2022-12-07 15:21 UTC, arbrandes requested changes
Just two minor quibbles with the code, if you don't mind.  Thanks!

2022-12-07 15:21 UTC, arbrandes commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +  const outlineLink = (overviewTabUrl ? (
Thanks!  Re-reading the code, though, I think we can get away with a:

```suggestion
  const outlineLink = overviewTabUrl && (
```

... because `outLineLink` is only used inside another corresponding conditional below.

2022-12-07 15:21 UTC, arbrandes commented on src/course-home/progress-tab/related-links/RelatedLinks.jsx
> +
```suggestion
```

We can remove this blank line.

2022-12-07 15:25 UTC, ghassanmas commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +  const outlineLink = (overviewTabUrl ? (
Yes but the expression would run even  if it's not used below, and I made this way bceause the expression is returing a react compoenent

2022-12-07 15:31 UTC, ghassanmas commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +  const outlineLink = (overviewTabUrl ? (
I am testing for that, the thing is react would cry if it expect a compoenent but it gets `undefined` though `null` is okay for it! But yeah you are right that case wouldn't occuar because it will render it if the link is `undefined`

2022-12-07 15:35 UTC, ghassanmas commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +  const outlineLink = (overviewTabUrl ? (
The test is good, and the change applied

2022-12-07 15:38 UTC, arbrandes commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +  const outlineLink = (overviewTabUrl ? (
Works for me!

2022-12-07 15:54 UTC, arbrandes commented
Code looks good!  Testing it now.

2022-12-07 17:55 UTC, arbrandes approved these changes
Tested on devstack and Tutor: both use cases are properly served, now.

Thanks, @ghassanmas!

2022-12-07 17:55 UTC, merged

2022-12-07 17:55 UTC, openedx-webhooks commented
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1009&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2022-12-06+10:43&entry.1917517419=2022-12-07+17:55&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->