[BD-29] [TNL-7303] Add course license details
openedx/frontend-app-learning pull request #103
Opened 2020-07-03 05:35 UTC by pcockwell

Add `CourseLicense` component with a display

**JIRA tickets**:
BD-29
[TNL-7303](https://openedx.atlassian.net/browse/TNL-7303)

**Dependencies**:
https://github.com/edx/edx-platform/pull/24393

**Screenshots**:
All Rights Reserved License
![all-rights-reserved-license](https://user-images.githubusercontent.com/829980/86434807-925aff00-bd28-11ea-936e-a24cb6e4d489.png)

Creative Commons License
![creative-commons-license](https://user-images.githubusercontent.com/829980/86434823-9dae2a80-bd28-11ea-8468-489076c47ffd.png)

**Merge deadline**: None

**Testing instructions**:

1. Pull the `patrick/BB-2678-tnl-7303-add-course-license-details-to-course-l` branch of the `open-craft:edx-platform` repository locally
2. Create a course in Studio
3. Edit the course, and select Settings > Schedule & Details
4. Set a license at the bottom of the page
5. Pull the `patrick/BB-2678-tnl-7303-add-course-license-details` branch of the `open-craft:frontend-app-learning` repository locally and setup your local LMS.
6. Run `npm install && npm start` in your `frontend-app-learning` folder
7. Navigate to to any unit in the course
8. Observe the license changes

**Author notes and concerns**:

1. Some CSS was added for course license display that does not use Utility-First CSS classes. If desired, this can be modified.

**Reviewers**
- [ ] @Agrendalath
- [ ] edX reviewer[s] TBD

2020-07-03 05:35 UTC, edx-webhook commented
Thanks for the pull request, @pcockwell! I've created [BLENDED-391](https://openedx.atlassian.net/browse/BLENDED-391) to keep track of it in Jira.

When this pull request is ready, tag your edX technical lead.

<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->

2020-07-06 17:18 UTC, Agrendalath requested changes

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/sequence/Sequence.jsx
> +        </div>
This is going to break if we don't set a license, because the API is going to return `license: null`. We could do something like this to prevent it from breaking, but I'll ask on the upstream ticket what should be the default behavior for this.

```suggestion
        {course.license && (
          <div className="sequence-footer">
            <CourseLicense license={course.license} />
          </div>
        )}
```

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +};
Would it make sense to create an enum above to make this more readable?
E.g.:
```js
enum CreativeCommonsLicenseTagsEnum {
    Attribution = 'by',
    Noncommercial = 'nc',
    NoDerivatives = 'nd',
    ShareAlike = 'sa',
};

const CreativeCommonsLicenseTags = {
  [CreativeCommonsLicenseTagsEnum.Attribution]: {
    text: 'Attribution',
    icon: faCreativeCommonsBy,
  },
  [CreativeCommonsLicenseTagsEnum.Noncommercial]: {
    text: 'Noncommercial',
    icon: faCreativeCommonsNc,
  },
  [CreativeCommonsLicenseTagsEnum.NoDerivatives]: {
    text: 'No Derivatives',
    icon: faCreativeCommonsNd,
  },
  [CreativeCommonsLicenseTagsEnum.ShareAlike]: {
    text: 'Share Alike',
    icon: faCreativeCommonsSa,
  },
};
```

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +  if (license === undefined) {
`undefined !== null` and the API can actually return `null`. The `!license` check should be sufficient here.

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +        options[key.toLowerCase()] = value.toLowerCase();
What does this line relate to? Some more comments would be nice for this function.

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +    version = version || '1.0';
What's the use-case here? Can we run into something like `ver=` while parsing this? Couldn't we just use `let version = '1.0'` in line 46?

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +  if (options.length === 0) {
Isn't this `undefined` for an `Object`? Shouldn't we use something like this instead?
```suggestion
  if (Object.keys(options).length === 0) {
```

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +  const renderCreativeCommonsLicense = (activeCreativeCommonsLicenseTags = [], version) => (
Nit: the default arg for `activeCreativeCommonsLicenseTags` will never be used, but sounds fine to keep it.

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +      <span className="license-text">Some Rights Reserved</span>
These texts (plus `sr-only` messages) should be wrapped with something like `{intl.formatMessage(messages['learn.course.load.failure'])` to allow translations.

2020-07-06 17:18 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +  license: PropTypes.string.isRequired,
It might not be `required`, depending on how we'll handle the `null` values from the API.

2020-07-07 02:54 UTC, pcockwell commented on src/courseware/course/CourseLicense.jsx
> +};
I tried setting an `enum` in the code, and kept getting errors. Do you have any examples of where it has successfully been implemented? Documentation online seems sparse regarding the requirements to make this work.

2020-07-07 02:55 UTC, pcockwell commented on src/courseware/course/CourseLicense.jsx
> +  if (license === undefined) {
Done in next commit

2020-07-07 03:08 UTC, pcockwell commented on src/courseware/course/CourseLicense.jsx
> +    version = version || '1.0';
Cleaned up in next commit

2020-07-07 03:08 UTC, pcockwell commented on src/courseware/course/CourseLicense.jsx
> +        options[key.toLowerCase()] = value.toLowerCase();
Comments added in next commit

2020-07-07 03:08 UTC, pcockwell commented on src/courseware/course/CourseLicense.jsx
> +  if (options.length === 0) {
Done in next commit

2020-07-07 03:12 UTC, pcockwell commented on src/courseware/course/CourseLicense.jsx
> +  const renderCreativeCommonsLicense = (activeCreativeCommonsLicenseTags = [], version) => (
Removed in next commit

2020-07-07 03:45 UTC, pcockwell commented on src/courseware/course/CourseLicense.jsx
> +      <span className="license-text">Some Rights Reserved</span>
Done in next commit

2020-07-07 20:36 UTC, Agrendalath commented on src/courseware/course/CourseLicense.jsx
> +};
Ah, sorry, I got confused and thought we were using TypeScript for a moment…
It would look like this for JS:
```js
const CreativeCommonsLicenseTagsEnum = {
  Attribution: 'by',
  Noncommercial: 'nc',
  NoDerivatives: 'nd',
  ShareAlike: 'sa',
};

const CreativeCommonsLicenseTags = {
  [CreativeCommonsLicenseTagsEnum.Attribution]: {
    text: 'Attribution',
    icon: faCreativeCommonsBy,
  },
  [CreativeCommonsLicenseTagsEnum.Noncommercial]: {
    text: 'Noncommercial',
    icon: faCreativeCommonsNc,
  },
  [CreativeCommonsLicenseTagsEnum.NoDerivatives]: {
    text: 'No Derivatives',
    icon: faCreativeCommonsNd,
  },
  [CreativeCommonsLicenseTagsEnum.ShareAlike]: {
    text: 'Share Alike',
    icon: faCreativeCommonsSa,
  },
};
```

I guess it's fine to keep this as is, though.

2020-07-07 20:58 UTC, Agrendalath reviewed
Thank you for addressing the comments. Looks good, @pcockwell!
I left come minor comments. Let's wait for Marco to clarify the empty license case.

2020-07-07 20:58 UTC, Agrendalath commented on src/courseware/course/course-license/messages.js
> +    description: 'License text shown when using all All Rights Reserved license type.',
Type: doubled "all"?

2020-07-07 20:58 UTC, Agrendalath commented on src/courseware/course/course-license/messages.js
> +  'learn.courseLicense.allRightsReserved.license.text': {
Could we make this `learn.course.license.licenseType.text`, etc? It will clearly indicate the hierarchy.
E.g. `learn.course.license.allRightsReserved.text`?

2020-07-07 20:58 UTC, Agrendalath commented on src/courseware/course/course-license/messages.js
> +    defaultMessage: 'Creative Commons licensed content, with terms as follow:',
Typo: shouldn't it be "follows"?

2020-07-07 20:58 UTC, Agrendalath commented on src/courseware/course/course-license/CourseLicense.jsx
> +    defaultVersion = '1.0';
I suppose we should set `version` here? It couldn't have been set before anyway, as there were no `options`.

2020-07-08 09:20 UTC, pcockwell commented on src/courseware/course/course-license/messages.js
> +    description: 'License text shown when using all All Rights Reserved license type.',
Fixed in next commit

2020-07-08 09:22 UTC, pcockwell commented on src/courseware/course/course-license/messages.js
> +  'learn.courseLicense.allRightsReserved.license.text': {
Fixed in next commit

2020-07-08 09:22 UTC, pcockwell commented on src/courseware/course/course-license/messages.js
> +    defaultMessage: 'Creative Commons licensed content, with terms as follow:',
Fixed in next commit

2020-07-08 09:23 UTC, pcockwell commented on src/courseware/course/course-license/CourseLicense.jsx
> +    defaultVersion = '1.0';
Fixed in next commit

2020-07-09 17:13 UTC, davidjoy commented on src/index.scss
> +.sequence-footer {
Where possible, it'd be good to use our CSS utility classes rather than having a semantic class name like this one.

https://edx.github.io/paragon/foundations/typography
https://edx.github.io/paragon/foundations/css-utilities

I think everything but that padding should be possible via classes shown on those two pages.  

What's the idea behind the percentage horizontal padding, rather than just choosing a particular number?  Does it change that much/improve the look on smaller devices?

2020-07-10 02:11 UTC, Agrendalath approved these changes
Works great! Leaving one additional thing, but this will not need another review round from my end after being changed. Also please address David's comment.

Btw. please don't squash the commits before finishing the review. GitHub falsely flags some comments as outdated in such case (plus it's hard to see the actual changes in particular files).

:+1:
* [x]  I tested this: tested all license types locally
* [x]  I read through the code
* [x]  I checked for accessibility issues
* [ ]  <s>Includes documentation</s>

2020-07-10 02:11 UTC, Agrendalath commented on src/courseware/course/course-license/CourseLicense.jsx
> +};
This is going to work, but will show an error in the console. Wouldn't it be better to use a default value like this instead of checking `!license` in `parseLicense`?
```suggestion
CourseLicense.propTypes = {
  license: PropTypes.string,
  intl: intlShape.isRequired,
};

CourseLicense.defaultProps = {
  license: 'all-rights-reserved',
};
```

However this means that we need to create this component this way, because the API would return `null`, not `undefined`.
```js
<CourseLicense license={course.license || undefined} />
```

2020-07-10 04:56 UTC, pcockwell commented on src/index.scss
> +.sequence-footer {
I've been able to reproduce all of this CSS using utility classes except for the `:hover` effect on the link, which I've kept in the `index.scss` file.

2020-07-10 04:59 UTC, pcockwell commented
@ormsbee I believe everything should be resolved as of the most recent commits. Could you take another pass? Once ready, I'll rebase and squash.

2020-07-11 01:07 UTC, Agrendalath commented
@pcockwell, Travis reports one linting issue and two outdated snapshots for integration tests. Could you please:
1. change the linting accordingly,
1. add `license` to the [course metadata factory](https://github.com/edx/frontend-app-learning/blob/master/src/courseware/data/__factories__/courseMetadata.factory.js),
3. update outdated snapshots?

2020-07-12 09:38 UTC, pcockwell commented
@Agrendalath Those issues should now be resolved.

2020-07-14 16:56 UTC, davidjoy commented on src/courseware/course/sequence/Sequence.jsx
> +          <CourseLicense license={course.license || undefined} />
This is a bit of a nit: If we handle coercing falsy course license values in the api.js layer, we can do away with this `|| undefined` here and create a more consistent value throughout the app (i.e., use our anti-corruption layer).  Also, we always expect the `license` field to be defined in the response, so my preference would be for it to be `null` instead of `undefined`.

2020-07-14 16:57 UTC, davidjoy commented on src/courseware/data/api.js
> +    license: metadata.license,
In the same way that we coerce other values to be camelCase, have different names, etc., we could ensure license is truthy or `null` here.  That way we don't have to be protective later.

2020-07-14 16:57 UTC, davidjoy commented on src/courseware/data/api.js
> +    license: metadata.license,
(This code is the "anti-corruption layer" mentioned above)

2020-07-14 16:58 UTC, davidjoy requested changes
Small nit, but worth touching I think.  Otherwise looks great/will Approve ASAP

2020-07-14 17:14 UTC, Agrendalath commented on src/courseware/course/sequence/Sequence.jsx
> +          <CourseLicense license={course.license || undefined} />
@davidjoy, I actually suggested this approach, because `null` [doesn't fall back](https://reactjs.org/docs/react-component.html#defaultprops) to [defaultProps](https://github.com/edx/frontend-app-learning/pull/103/files#diff-d3d8c9fa2454167844ad1ce727c81d04R162-R164). Should we define the default license on the api.js layer or somewhere in the `CourseLicense` component's code instead?

2020-07-15 14:31 UTC, davidjoy commented on src/courseware/course/sequence/Sequence.jsx
> +          <CourseLicense license={course.license || undefined} />
Ah - we can just go ahead with this then, if there were issues.  It's probably not worth having to rethink it for now.

2020-07-15 14:31 UTC, davidjoy approved these changes

2020-07-17 04:56 UTC, pcockwell commented
@davidjoy My understanding is that this and https://github.com/edx/edx-platform/pull/24393 are ready to merge. Is there anything further you need?

2020-07-17 17:26 UTC, merged