feat: fetch exam access token
openedx/frontend-app-learning pull request #1083
Opened 2023-03-13 21:01 UTC by varshamenon4

2023-03-13 21:15 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.jsx
> +  if (examAccessToken) {
I think there might be some async issues to consider here. What happens if the api call behind `checkExamAccessToken` isn't done yet?

2023-03-23 13:48 UTC, varshamenon4 reviewed
Some clarifying questions for review!

2023-03-23 13:48 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.test.jsx
> +  it('calls fetchExamAccess if isExam upon block id', () => {
Is this the right approach to testing this? That is, mocking the functions and making sure they are called? Have some additional tests which still need to be implemented below but could use a look to make sure it's in the right direction.

2023-03-23 13:48 UTC, varshamenon4 commented on src/index.jsx
> +        EXAMS_BASE_URL: process.env.EXAMS_BASE_URL || null,
Not sure why this dupe key error is happening? I tried to add the merge config in tests but wondering if this has to do with it being in both frontend-lib-special-exams and frontend-app-learning as env variables. And if this is the case, I'm not sure if it's better to completely get rid of in one place or another.

2023-03-23 13:48 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +import { getExamAccess, fetchExamAccess, isExam } from '@edx/frontend-lib-special-exams';
When I run the tests locally on the IDE, I get an error that these functions cannot be found. I'm wondering if it has to do with this export/import being reflected in my branch of frontend-lib-special-exams and not the main branch?

2023-03-23 13:59 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.test.jsx
> +  it('calls fetchExamAccess if isExam upon block id', () => {
yeah this looks correct to me

2023-03-23 13:59 UTC, Zacharis278 commented on src/index.jsx
> +        EXAMS_BASE_URL: process.env.EXAMS_BASE_URL || null,
why is EXAMS_BASE_URL needed here?

2023-03-23 14:12 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.jsx
> +import { getExamAccess, fetchExamAccess, isExam } from '@edx/frontend-lib-special-exams';
I think that's it, likely has to do with installing via module.config vs. what's in package.json

2023-03-23 15:42 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +import { getExamAccess, fetchExamAccess, isExam } from '@edx/frontend-lib-special-exams';
ahhh okay.

2023-03-23 15:44 UTC, varshamenon4 commented on src/index.jsx
> +        EXAMS_BASE_URL: process.env.EXAMS_BASE_URL || null,
I believe because we want to merge config in frontend-app-learning with these other settings--though it's not called in frontend-app-learning. Since frontend-app-learning already imports the edx frontend platform dependency.

2023-03-31 15:24 UTC, zacharis278 commented
@varshamenon4 not sure if you already plan to have this covered but I think we're missing some tests around how the blockExamAccess flag works.

2023-03-31 19:00 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.test.jsx
> +    render(<Unit {...mockData} />);
@Zacharis278 still getting used to jest testing, but is this the correct way to test the isExam and fetchExamAccess calls? And yes, like you mentioned I still need to test if blockExamAccess is working correctly. I'm guessing this would happen my mocking those other functions and their return values and making sure that the blockExamAccess is set correctly? And then also testing that the iframe url either has or doesn't have the exam access token?

2023-04-05 19:44 UTC, varshamenon4 reviewed
Had some questions about testing that I could use some eyes on!

2023-04-05 19:44 UTC, varshamenon4 commented on src/courseware/course/Course.test.jsx
> +// const originalIsExam = jest.requireActual('@edx/frontend-lib-special-exams').isExam();
I tried mocking some of the pieces of the Unit that were added to hopefully resolve the tests in Course and Sequence but that didn't seem to work. I am looking into the errors now. It's showing an unexpected error but I'm also seeing console errors about incorrect return type for Course and Sequence so going to dig into that.

2023-04-05 19:44 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +          srMessage={intl.formatMessage(messages.loadingSequence)}
This just continues to render the loading sequence like above but I'm wondering if there should be an error like the code below or if this is the right expected behavior for when exam access is blocked.

2023-04-05 19:44 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.test.jsx
> +    // todo: should fetch
Not sure how to mock when exam access is not granted. I'm thinking of returning a rejected Promise, but I think I'll need to update the mockFetchExamAccess to handle both resolved/rejected cases.

2023-04-05 19:44 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.test.jsx
> +    const renderedUnit = screen.getByTitle(unit.display_name);
Getting an error here as it's just leading to the loading sequence. When I was debugging I could see that the block exam access was successfully set to false when exam access is granted, but there seemed to be some async issue happening. I'm wondering if I'm missing something on mocking the Promise.

2023-04-06 14:43 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.jsx
> +          srMessage={intl.formatMessage(messages.loadingSequence)}
I see what you mean, I think fetchExamAccess in our useEffect hook should always do `setBlockExamAccess(false)` after the promise returns. You could accomplish that by simple changing `fetchExamAccess().then(() => {` to `fetchExamAccess().finally(() => {`

2023-04-06 15:26 UTC, Zacharis278 commented on src/courseware/course/Course.test.jsx
> +// const originalIsExam = jest.requireActual('@edx/frontend-lib-special-exams').isExam();
ok I see what's happening here. We could mock out the the api into special-exams library but I think that's the wrong way to go about things because it would force ever place we import this to do the same. What's happening is a simple null check problem is frontend-lib-special-exams because exam state isn't initialized. IMO because api.js is an external interface it should be resilient to that.

I think a simple null check in the isExam function would solve this but to avoid issues in the future id recommend:
if no exam state
- isExam - return false
- return empty string + log an error
- return failed promise + log an error

2023-04-06 16:30 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.test.jsx
> +    const renderedUnit = screen.getByTitle(unit.display_name);
Yup your render here causes a promise to fire (fetchExamAccess) inside useEffect because isExam is true. So, your test needs to handle that by either wrapping the render in something like act() or having screen.getByTitle wait until the iframe loads with the token.

Right now your test can't find the iframe because on the first draw of the Unit it's still in the loading state

2023-04-06 17:31 UTC, varshamenon4 commented on src/courseware/course/Course.test.jsx
> +// const originalIsExam = jest.requireActual('@edx/frontend-lib-special-exams').isExam();
Ah I see @Zacharis278. And to clarify, this change would be in isExam itself/frontend-lib-special-exams. And you're suggesting doing the bullet points for each api function to be safe, so isExam, getExamAccess, and fetchExamAccess respectively?

2023-04-06 17:35 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +          srMessage={intl.formatMessage(messages.loadingSequence)}
Okay so I'll update this and also update to render the error instead of page loading?

2023-04-06 20:19 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.jsx
> +          srMessage={intl.formatMessage(messages.loadingSequence)}
I don't even think you _need_ to do anything in the UI here since the xblock itself is going to render its own error. It might be nicer but in the interest of getting things across the line the default xblock error should be enough.

2023-04-06 20:20 UTC, Zacharis278 commented on src/courseware/course/Course.test.jsx
> +// const originalIsExam = jest.requireActual('@edx/frontend-lib-special-exams').isExam();
yeah it would have to be in the frontend-lib-special-exams

2023-04-07 19:29 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.test.jsx
> +  it('does not update url if exam and exam access not granted', async () => {
Could you take a look at this test? Not sure how to go about testing this case. I tried adding a catch to the useEffect, but I'm not sure that that is correct, as it seems to resolve and set the exam access token when I test this.

2023-04-13 13:34 UTC, varshamenon4 commented on src/courseware/course/Course.test.jsx
> +// const originalIsExam = jest.requireActual('@edx/frontend-lib-special-exams').isExam();
Added to frontend-lib-special-exams in this PR: https://github.com/openedx/frontend-lib-special-exams/pull/97

2023-04-13 13:34 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.test.jsx
> +    const renderedUnit = screen.getByTitle(unit.display_name);
Fixed.

2023-04-13 14:56 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +        setExamAccessToken(getExamAccess());
Found some bugginess with this switch in logic (below, adding the check for exam access token before setting block exam access), that this is now not loading because the exam access token isn't set (but I believe this is some type of syncing issue).

2023-04-13 15:06 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +        setExamAccessToken(getExamAccess());
Basically, the exam access token is eventually set, but when I check for it in line 61, it's showing up as blank. As I had it before (when it was working), the blockExamAccess was always set to false when an exam. But since now with the finally after fetch exam access, it should always get to blockExamAccess set to false. I'm going to try hacking the error case to see if it never gets to the finally in this case.

2023-04-13 15:15 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +        setExamAccessToken(getExamAccess());
I now don't think this is an issue. Because when I test that fetchExamAccess returns a rejected value, then it shouldn't get to the finally block. So I don't need the logic altogether to check the examAccessToken within the useEffect block, in the finally(). I just need to test/hack the case where the exam access token is not granted. But lemme know if you think I should investigate.

2023-04-13 17:39 UTC, varshamenon4 reviewed
Ready for re-review.

2023-04-13 17:39 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +      }).catch((error) => logError(error));
Need to catch an error in case of a rejected promise returned. But lemme know if there is a better approach.

2023-04-13 17:39 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +      {!showError && !hasLoaded && blockExamAccess && (
Just wanted to confirm that these are the conditions we want met to have loading sequence?

2023-04-13 18:22 UTC, Zacharis278 requested changes

2023-04-13 18:22 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.jsx
> +      }).catch((error) => logError(error));
this is a 'we should never hit this line' type error right? In which case, this looks fine.

2023-04-13 18:22 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.jsx
> +      {!showError && !hasLoaded && blockExamAccess && (
I think this logic leaves a gap if blockExamAccess is false (which renders the iframe) but the iframe content isn't loaded yet (so hasLoaded==False). We might get two spinners in that case because the statement above also creates one if !hasLoaded.

So maybe `!showError && (!hasLoaded || blockExamAccess)`, or better yet combining this logic with the above avoid the issue of something unintentionally rendering PageLoading twice entirely.

2023-04-13 18:26 UTC, varshamenon4 commented
Yup, you're right on this creating 2 spinners. I noticed that when I had the logic to block exam access and it was creating two spinners. I'll update. @Zacharis278 

https://github.com/openedx/frontend-app-learning/pull/1083#discussion_r1165875958

2023-04-13 18:26 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +      {!showError && !hasLoaded && blockExamAccess && (
Yup, you're right on this creating 2 spinners. I noticed that when I had the logic to block exam access and it was creating two spinners. I'll update. @Zacharis278

2023-04-13 18:27 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +      }).catch((error) => logError(error));
Yeah we shouldn't. I was just getting some warnings when I tried to test having fetchExamAccess return an rejected promise.

2023-04-13 18:44 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.jsx
> +      {!showError && !hasLoaded && blockExamAccess && (
Updated the logic!

2023-04-13 20:19 UTC, Zacharis278 commented on src/courseware/course/sequence/Unit.test.jsx
> +    expect(waitFor(() => expect(window.scrollTo()).toHaveBeenCalled()));
is this change intentional?

2023-04-13 20:23 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.test.jsx
> +    expect(waitFor(() => expect(window.scrollTo()).toHaveBeenCalled()));
Ah I was testing something and had commented it out but I forgot to add back the await. Fixing now

2023-04-13 20:25 UTC, varshamenon4 commented on src/courseware/course/sequence/Unit.test.jsx
> +    expect(waitFor(() => expect(window.scrollTo()).toHaveBeenCalled()));
Fixed!

2023-04-17 14:00 UTC, zacharis278 approved these changes

2023-04-17 18:59 UTC, merged