feat: added open/close state of discussion sidebar in local storage
openedx/frontend-app-learning pull request #1086
Opened 2023-03-17 06:11 UTC by muhammadadeeltajamul

- Discussion Sidebar will maintain its state i.e. if a user opens discussion sidebar in a unit and then navigates to course home. When he will open any unit, discussion sidebar will remain open. 
- User will atleast once view discussion sidebar.
- Sidebar information has been maintained in localstorage

Ticket: [INF-767](https://2u-internal.atlassian.net/browse/INF-767)

2023-03-20 14:19 UTC, sundasnoreen12 requested changes
PR LGTM. Please add test cases to store enable state of the sidebar in the local storage to improve the codeCoverage.

2023-03-21 07:27 UTC, ayeshoali approved these changes
Test cases are failing please review those.

2023-03-27 09:43 UTC, sundasnoreen12 requested changes

2023-03-27 09:43 UTC, sundasnoreen12 commented on src/courseware/course/Course.test.jsx
> +    axiosMock.onGet(`${getConfig().LMS_BASE_URL}/api/discussion/v1/courses/${courseId}`).reply(200, { provider: 'openedx' });
You can pass a static courseId as we passing in discussion MFE for api calling

2023-03-27 09:43 UTC, sundasnoreen12 commented on src/courseware/course/Course.test.jsx
> +    const { courseId } = courseware;
Use static courseId instead of getting from store as we are using in discussion MFE

2023-03-27 09:43 UTC, sundasnoreen12 commented on src/courseware/course/Course.test.jsx
> +    axiosMock.onGet(`${getConfig().LMS_BASE_URL}/api/discussion/v2/course_topics/${courseId}`)
You can pass a static courseId as we passing in discussion MFE for api calling

2023-03-27 09:43 UTC, sundasnoreen12 commented on src/courseware/course/Course.test.jsx
> +    const element = screen.queryByTestId(elementTestId);
use this instead of these lines to avoid duplication.
const element = await waitFor(() => screen.queryByTestId('sidebar-DISCUSSIONS'));

2023-03-27 09:43 UTC, sundasnoreen12 commented on src/courseware/course/Course.test.jsx
> +  [true, false].forEach(async (value) => (it(`Discussion sidebar storage value is ${!value} when sidebar is ${value ? 'closed' : 'open'}`, async () => {
use object instead of bool to pass the result attribute to avoid if else condition 
[{value: true, result: 'false'}, {value: false, result: 'true'}].forEach(async ({value, result})

2023-03-27 09:43 UTC, sundasnoreen12 commented on src/courseware/course/Course.test.jsx
> +    }
expect(localStorage.getItem('showDiscussionSidebar')).toBe(result);

2023-03-27 09:43 UTC, sundasnoreen12 commented on src/courseware/course/Course.test.jsx
> +  [true, false, null].forEach(async (value) => (it(`discussion sidebar is ${value === false ? 'hidden' : 'shown'} when localstorage value is ${value}`, async () => {
use object to pass the hasClass attribute to avoid if else condition

[{value: true, hasClass: null}, {value: false, hasClass: 'd-none'},{value: null, hasClass: null}].forEach(async ({value, hasClass})

2023-03-27 09:43 UTC, sundasnoreen12 commented on src/courseware/course/Course.test.jsx
> +    }
we can use more precise code like this i think try to reuse it.

const class = hasClass ? 'have' : 'not have';
expect(element)[class].toHaveClass(hasClass);

2023-03-27 10:02 UTC, muhammadadeeltajamul commented on src/courseware/course/Course.test.jsx
> +    axiosMock.onGet(`${getConfig().LMS_BASE_URL}/api/discussion/v1/courses/${courseId}`).reply(200, { provider: 'openedx' });
In learning MFE, course is being created in the factory and it is not defined as a const. It is better to extract course id rather than using a static courseId

2023-03-27 11:41 UTC, muhammadadeeltajamul commented on src/courseware/course/Course.test.jsx
> +    }
Element has multiple classes... We need to seperate it using if other wise test case will always fail when it will try to check class null

2023-03-28 07:27 UTC, sundasnoreen12 approved these changes
PR LGTM

2023-03-28 07:52 UTC, awais-ansari requested changes

2023-03-28 07:52 UTC, awais-ansari commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
> +  const showDiscussionSidebar = discussionStorageEmpty ? true : localStorage.getItem('showDiscussionSidebar') === 'true';
Refactor the code. If can be written.
const showDiscussionSidebar = localStorage.getItem('showDiscussionSidebar') !== 'false';

2023-03-28 07:52 UTC, awais-ansari commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
>    }, [currentSidebar]);
Refactor: 
const toggleSidebar = useCallback((newSidebarId) => {
  const showDiscussionSidebar = newSidebarId === SIDEBARS.DISCUSSIONS.ID;
  localStorage.setItem('showDiscussionSidebar', showDiscussionSidebar);
  setCurrentSidebar(currentSidebar === newSidebarId ? null : newSidebarId);
}, [currentSidebar, setCurrentSidebar]);

2023-03-28 07:52 UTC, awais-ansari commented on src/courseware/course/Course.test.jsx
> +    const { courseId } = courseware;
refactor:
const { courseware: { courseId } } = state;

2023-03-28 07:52 UTC, awais-ansari commented on src/courseware/course/Course.test.jsx
> +    mockData.unitId = Object.keys(state.models.units)[0];
const [firstUnitId] = Object.keys(state.models.units);
mockData.unitId = firstUnitId;

This will remove the eslint error

2023-03-28 07:52 UTC, awais-ansari commented on src/courseware/course/Course.test.jsx
> +    mockData.sequenceId = Object.keys(state.models.sequences)[0];
const [firstSequenceId] = Object.keys(state.models.sequences);
mockData.sequenceId = firstSequenceId;

This will remove the eslint error

2023-03-28 07:52 UTC, awais-ansari commented on src/courseware/course/Course.test.jsx
> +  ].forEach(async (obj) => (it(`discussion sidebar is ${obj.visible ? 'shown' : 'hidden'} when localstorage value is ${obj.value}`, async () => {
line length is greater than 120 characters.

2023-03-28 07:52 UTC, awais-ansari commented on src/courseware/course/Course.test.jsx
> +  ].forEach(async (obj) => (it(`discussion sidebar is ${obj.visible ? 'shown' : 'hidden'} when localstorage value is ${obj.value}`, async () => {
async ({value, visible}) => {}

directly destructure the object

2023-03-28 07:52 UTC, awais-ansari commented on src/courseware/course/Course.test.jsx
> +  ].forEach(async (obj) => (it(`Discussion sidebar storage value is ${!obj.value} when sidebar is ${obj.value ? 'closed' : 'open'}`, async () => {
line length is greater than 120 characters.
async ({value, visible}) => {}
directly destructure the object

2023-03-28 10:12 UTC, muhammadadeeltajamul commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
>    }, [currentSidebar]);
This code is logically different

2023-03-28 10:38 UTC, awais-ansari approved these changes

2023-03-28 10:39 UTC, merged