AA-205: created chapters and subsections containing progress
openedx/frontend-app-learning pull request #109
Opened 2020-07-15 20:13 UTC by daphneli-chen

2020-07-16 15:25 UTC, Dillon-Dumesnil approved these changes
Awesome job Daphne! This is really coming along and it's awesome getting to see something functional and put together!
Don't think I have anything blocking, but I'd say to wait for at least one other review before merging just to double check everything.

2020-07-16 15:25 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Chapter.jsx
> +      <div className="row">
Nit: But I think I'd prefer this like 
```
{!hide && (
  <div className="row"?

2020-07-16 15:25 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/ProgressTab.jsx
> +      {enrollmentMode} {administrator} {username}
Assuming this is still just there for testing purposes?

2020-07-16 15:25 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +  const totalScoreSr = `${earned} of ${possible} possible points`; // screen reader information
Good comment! Definitely helped me with this line.

2020-07-16 15:25 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +        {(section.due != null
This maybe should be `!==`..?

2020-07-16 15:25 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +      && <ProblemScores scoreName={scoreName} problemScores={section.problemScores} />}
Writing it here, but kind of applies all over and are all nits anyway, but I'd personally prefer more of the logic on one line. It's harder for me personally to try and follow this vs
```
{section.problemScores.length > 0 && section.showGrades && 
  <ProblemScores ...

2020-07-16 15:25 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +      // firstAttempted: PropTypes.object, // don't think i need this
Just a reminder to delete this if you don't end up needing it

2020-07-16 15:25 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +        && <DueDateTime due={section.due} />}
I'll let others weigh in as well, but I'm not convinced we need an entire component for this and could just inline what you have for the DueDateTime here.

2020-07-16 17:02 UTC, xnick421 requested changes

2020-07-16 17:02 UTC, xnick421 commented on package.json
>      "husky": "^3.1.0",
how come these are updated?  i don't see a newly added package.  or maybe im over looking it?

2020-07-16 17:02 UTC, xnick421 commented on src/course-home/progress-tab/Section.jsx
> +      {(section.problemScores.length > 0
i think this could just be written  as ` section.problemScores.length`

2020-07-16 17:02 UTC, xnick421 commented on src/course-home/progress-tab/ProblemScores.jsx
> +          <dd className="individual-problem-scores" key={problem.id}>{problem.earned}/{problem.possible}</dd>))}
so i guess now we are passing a uuid from the BE so we are able to reference `.id`.  but in my opinion, making the BE serve something to the FE simply because of a framework restraint doesnt really make sense.  An option here could be normalizing the problem data in the `thunk` file where these problems are processed from the BE.  we could then add a `id` property and just set it to the index, or index+1.  either way should matter, because technically the key will not referring to the same index of each element at render time.

2020-07-16 17:02 UTC, xnick421 commented on src/course-home/progress-tab/Section.scss
> +  flex-wrap: wrap;
did we try to use bootstrap for some of these?

2020-07-16 21:36 UTC, ciduarte reviewed
Good job getting through this! This styling wasn't easy.

Most of my comments have to do with your use of CSS and classNames. We talked about this through chat, but try to avoid adding classNames that have no use. I would also try to use Paragon and Bootstrap classNames before trying to write CSS. Avoid reinventing the wheel! :)

I also agree with Dillon's comment about the way you're formatting these `{(foo.bar) && <Component />}` across all of these files. If it helps, I would look into how similar files are structured, and try to mimic for readability.

2020-07-16 21:36 UTC, ciduarte commented on src/course-home/progress-tab/Chapter.scss
> +}
I don't think we should be creating these custom CSS classes just to match the old experience. Fortunately we can use Paragon for a lot of built in styling, and the design team will be doing an overhaul on not only Paragon styling, but the Progress Tab.

I would suggest removing `chapter-display-name` and opting for `lead font-weight-normal` in the className.

2020-07-16 21:36 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +  }
nit: we could one line this to `const scoreName = section.graded ? 'Problem' : 'Practice';`

2020-07-16 21:36 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +      && <ProblemScores scoreName={scoreName} problemScores={section.problemScores} />}
+1

2020-07-16 21:36 UTC, ciduarte commented on src/course-home/progress-tab/Section.scss
> +}
So I pulled this branch and removed these CSS classes and it didn't seem to change the styling at all. Trying to avoid redundancy!

2020-07-16 21:36 UTC, ciduarte commented on src/course-home/progress-tab/Section.scss
> +}
We can remove this class and replace it with `d-flex flex-wrap small text-gray-500` in the className.

2020-07-16 21:36 UTC, ciduarte commented on src/course-home/progress-tab/Section.scss
> +  margin-right: 16px;
I realized that you declared `dd { margin-right: 8px }` along with this margin. Because they're being used on the same element, this is redundant. I would remove this as well and just put `mr-3` in the className of the `<dd>` tag.

2020-07-16 21:36 UTC, ciduarte commented on src/course-home/progress-tab/Section.scss
> +  display: block;
You're using `dl { display: block; }` and `problem-scores-container { display: flex; }` on the same element, so these are competing displays... I don't think you need this styling either.

2020-07-16 21:36 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +    <section className="mb-3 ml-3 mt-3">
When you have a margin on the top & bottom, you can simplify it into `my-3`.

Same goes for if you have margins on the left & right said, you could use `mx-#`.

2020-07-17 14:13 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +  }
Oooh. +1. I love a good ternary. And am now a little sad I didn't write this comment.

2020-07-17 14:24 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +        && <DueDateTime due={section.due} />}
ehh, I guess using DueDateTime makes it a little cleaner. It doesn't feel super necessary, but I'm not convinced one way or the other.

2020-07-17 18:25 UTC, daphneli-chen commented on src/course-home/progress-tab/ProgressTab.jsx
> +      {enrollmentMode} {administrator} {username}
yes this is there becuase the information needs to be used for committing but I don't have a use for it yet bc that'll be in future PRs

2020-07-17 18:53 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +      <div className="title row">
Is this `title` className doing something?

2020-07-21 13:35 UTC, Dillon-Dumesnil reviewed
I have a couple of open questions, but it's looking amazing. I'm hype

2020-07-21 13:35 UTC, Dillon-Dumesnil commented on package.json
>      "husky": "^3.1.0",
I'll let Daphne confirm, but my guess is that it's one of the classic, since we all install this app locally, if you installed it and there is a more recent version, those changes will be picked up in your PR.

2020-07-21 13:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Chapter.jsx
> +      {!hide && (
I think the `{!hide &&` should maybe be at the very top of this function. Otherwise we are wanting to hide a section, but we will still add a `section` HTML element to the DOM.

2020-07-21 13:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Chapter.jsx
> +      <div className="row">
Nit: Indent everything after the `&&` for clarity that it is part of the "if" statement

2020-07-21 13:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/messages.js
> +  pointsEarned: {
Is this future planning? I don't see this particular message being used anywhere right now.

2020-07-21 13:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +        {section.due !== null && !isSelfPaced
This should actually not have the `!isSelfPaced` check I'd imagine since we now have PLS. @Ahernkb , can you confirm?

2020-07-21 13:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +  const scoreName = section.graded ? 'prob' : 'prac';
Nit: `scoreName` -> `typeOfScore`
Nitx2: `'prob'`/`'prac'` -> `'problem'`/`'practice'`

2020-07-21 13:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Section.jsx
> +          && <span className="points-earned-sr sr-only">{totalScoreSr}</span>}
Nit: For shorter lines like this, I'd say you just can just one line them. If the line is longer, have the `&&` on the first line and indent all future lines (like an if statement)

2020-07-21 13:43 UTC, davidjoy commented on package.json
> +    "@edx/frontend-component-footer": "^10.0.11",
In general, it's a good idea to split out blanket dependency updates like this into a separate PR if they're not directly related to the code.

2020-07-21 13:45 UTC, davidjoy commented on src/course-home/progress-tab/Section.jsx
> +        && <span className="points-earned small ml-1 mb-2">({earned}/{possible}) {section.percentGraded}%</span>}
Looks like `points-earned` and `points-earned-sr` above aren't being used, I think?

2020-07-21 13:47 UTC, davidjoy commented
Just chiming in a little cause I was in the neighborhood. :) Looks good!

2020-07-21 14:12 UTC, ciduarte approved these changes
This came together great! I would do a final sweep to check for the placement of `&&`, unused CSS classNames, and any lingering comments.

Awesome work 🥳

2020-07-21 14:12 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +      <div className="title row">
Bump on this comment :)

2020-07-21 14:12 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +    // override: PropTypes.object,
Unclear if you're saving this for future use, I would remove it if not

2020-07-21 14:12 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +        {section.due !== null && !isSelfPaced
Clarity for @Ahernkb, this is saying to display an assignment's due date if
1. the assignment has a due date, and
2. the course is **not** self paced.

2020-07-21 14:12 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +        && <div className="mr-1">{section.format}</div>}
nit: I would do a sweep through this PR and make sure you have all of the `&&` on the top-most lines. I would avoid starting lines with `&&` for readability.

If the line seems short enough (in terms of linting), you can even have it all on one line. This one does to me, but I could be wrong.

2020-07-21 14:16 UTC, ciduarte commented on src/course-home/progress-tab/Section.jsx
> +    // override: PropTypes.object,
Missed your comment about override being added in the next step -- ignore me!

2020-07-21 14:42 UTC, daphneli-chen commented on src/course-home/progress-tab/Chapter.jsx
> +      {!hide && (
i don't think the first line can be javascript? i'll try though!

2020-07-21 14:43 UTC, daphneli-chen commented on src/course-home/progress-tab/Section.jsx
> +        && <div className="mr-1">{section.format}</div>}
the eslint requirements say that && has to be first on the line i think? i tried moving them up but it gets angry

2020-07-22 16:50 UTC, daphneli-chen commented on src/course-home/progress-tab/messages.js
> +  pointsEarned: {
meant to use it, should be in now!

2020-07-23 13:41 UTC, Dillon-Dumesnil reviewed
Seeing lots of good things! Let me know if you want to talk about any of my comments and I'd be happy to chat :)

2020-07-23 13:41 UTC, Dillon-Dumesnil commented on package.json
> +    "@edx/frontend-component-footer": "^10.0.11",
Agreed with David Joy here. Let's remove out the package and package-lock files from this PR. This isn't adding anything new and just performing updates so we can wait on all of these and they can happen separately.

2020-07-23 13:41 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Chapter.jsx
> +      {!hide && (
No luck? If not, I might even say then to change this up to be 
```
const hide = (chapter.displayName === 'hidden');
if (hide) return null;
const { sections } = chapter;
```

2020-07-23 13:41 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Subsection.jsx
> +      && <div className="row small">{intl.formatMessage(messages.noScores)}</div> }
Could we not move these to have the `&&` on the top line? I think you might just need to do something like 
```
      {section.problemScores.length > 0 && section.showGrades && (
        <ProblemScores scoreName={scoreName} problemScores={section.problemScores} />
      )}
```
where you wrap the react/html component in parentheses

2020-07-23 13:41 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Subsection.jsx
> +        {section.due !== null && !isSelfPaced && <DueDateTime due={section.due} />}
Did you check in with Kaitlin about this `!isSelfPaced`? I think we might want to be showing this as long as there is a due date now. This might also be able to have you not have to use the self_paced in the serializer.

2020-07-23 13:41 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Subsection.jsx
> +  const scoreName = section.graded ? 'prob' : 'prac';
Nit: prob/prac -> problem/practice

2020-07-23 13:41 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Subsection.jsx
> +  section,
I'll just add it here, but I left a comment in the backend PR too about renaming all of this to subsection. I'd be happy to help work through it, but I think it could be a good improvement so we can move away from all of this mixed up language where we have new variables being subsections and ones from the backend being sections.

2020-07-23 13:41 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Subsection.jsx
> +  const pastDue = section.showCorrectness === 'past_due';
Nit: Since this is only used twice anyway and I think `pastDue` isn't as clear of what this is actually representing, I think I'd say to just replace your uses of `pastDue` with `section.showCorrectness === 'past_due'`.

2020-07-23 15:07 UTC, daphneli-chen commented on src/course-home/progress-tab/Subsection.jsx
> +      && <div className="row small">{intl.formatMessage(messages.noScores)}</div> }
okay ! i'll try that -- eslint otherwise was saying that && would have to be after the line break

2020-07-23 18:17 UTC, Dillon-Dumesnil approved these changes
Some small nit picks, but looks great!

2020-07-23 18:17 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Chapter.jsx
> +  if (hide) { return null; }
Nit: For one liners, you actually don't need brackets.

2020-07-23 18:17 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Subsection.jsx
> +  const scoreName = subsection.graded ? 'problem' : 'practice';
👍

2020-07-23 18:17 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Subsection.jsx
> +      <div className="row small">{intl.formatMessage(messages.noScores)}</div>)}
Nit: Indent the line that comes after the &&. So for example:
```
      {subsection.problemScores.length > 0 && subsection.showGrades && (
        <ProblemScores scoreName={scoreName} problemScores={subsection.problemScores} />)}

2020-07-23 18:17 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Subsection.jsx
> +      && <div className="row small">{intl.formatMessage(messages[`${scoreName}Hidden`])}</div>}
Can we move this up to the top line so it matches all the others?

2020-07-23 18:20 UTC, Dillon-Dumesnil approved these changes

2020-07-23 18:20 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Chapter.jsx
> +  const { subsections } = chapter; // this sections actually refers to the subsections of a chapter
Remove this comment. It makes sense now! Woo!

2020-07-27 14:56 UTC, daphneli-chen commented on src/course-home/progress-tab/Chapter.jsx
> +  if (hide) { return null; }
es lint required braces, is there a way to override that?

2020-07-27 15:00 UTC, daphneli-chen commented on src/course-home/progress-tab/Subsection.jsx
> +      && <div className="row small">{intl.formatMessage(messages[`${scoreName}Hidden`])}</div>}
it breaks the line length rule by 1 character if I do

2020-07-27 15:10 UTC, Dillon-Dumesnil approved these changes
Just a small nit

2020-07-27 15:10 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/Chapter.jsx
> +  if (hide) { return null; }
Eh, don't worry about it. This is fine.

And nit: Rather than define `hide` as a variable, you can just check `if (chapter.displayName === 'hidden')`

2020-07-27 16:05 UTC, ciduarte approved these changes
Looks good, great job 😁

2020-07-27 16:05 UTC, ciduarte commented on src/course-home/progress-tab/Subsection.jsx
> +      && <div className="row small">{intl.formatMessage(messages[`${scoreName}Hidden`])}</div>}
tiny nit: can we move the curly bracket at the end of this line to the next line

2020-07-27 17:28 UTC, Dillon-Dumesnil approved these changes

2020-07-27 17:43 UTC, xnick421 approved these changes

2020-07-28 14:28 UTC, daphneli-chen commented on src/course-home/progress-tab/Subsection.jsx
> +      && <div className="row small">{intl.formatMessage(messages[`${scoreName}Hidden`])}</div>}
the curly bracket can only be moved if there's also a () with it because eslint doesn't allow a } to be alone on a new line but since it's not a multiline jsx i didn't add a () ?

2020-07-28 15:25 UTC, Ahernkb approved these changes
Looks great!

2020-07-28 16:53 UTC, merged