feat: redirect if course outline api returns redirect error
openedx/frontend-app-learning pull request #1111
Opened 2023-05-09 19:37 UTC by jansenk

If the course outline API endpoint returns course access redirect info, redirect to the given URL

2023-05-10 12:44 UTC, schenedx commented on src/course-home/data/api.js
> +    window.location.replace(data.url);
#NIT can you add in code comment to spell out why you are doing this `windows.location.replace` call?
It is clear from your PR description. It's not clear just reading the code.

2023-05-10 12:44 UTC, schenedx approved these changes
👍

2023-05-12 14:50 UTC, muselesscreator approved these changes
LGTM

2023-05-12 15:12 UTC, nsprenkle requested changes, later dismissed
This seems semantically like the wrong thing to do. If I'm asking for access to a course and I don't have it, it seems like I would like a `401 - Unauthorized`, no? Not a `302`. And then it should be the responsibility of the MFE to redirect, not the API.

2023-05-12 18:04 UTC, leangseu-edx commented
> This seems semantically like the wrong thing to do. If I'm asking for access to a course and I don't have it, it seems like I would like a `401 - Unauthorized`, no? Not a `302`. And then it should be the responsibility of the MFE to redirect, not the API.

302 just mean redirect. It make sense if you go to `unauth.com` then to redirect you to `unauth.com/login`. However 302 as an api doesn't really make much sense.

I agree with @nsprenkle that the backend should raise `Unauthorized` then we should wrap `await getAuthenticatedHttpClient().get(url);` in try/catch for the frontend.

2023-05-23 19:34 UTC, schenedx approved these changes
👍

2023-05-23 19:38 UTC, mattcarter approved these changes
approved

2023-05-24 15:25 UTC, leangseu-edx approved these changes

2023-05-24 15:38 UTC, merged