Ayesha/inf 915
openedx/frontend-app-learning pull request #1131
Opened 2023-06-22 14:28 UTC by ayesha-waris

[INF-915](https://2u-internal.atlassian.net/browse/INF-915)

- Removed state tracking and such that the sidebar always opens when a user navigates to a unit.
- The close button should still allow users to close the sidebar, but it should re-open when user reloads the page or navigates to another unit that has discussions enabled.

2023-06-23 07:31 UTC, sundasnoreen12 requested changes

2023-06-23 07:31 UTC, sundasnoreen12 commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
>        setCurrentSidebar(initialSidebar);
No need of line 26 const showDiscussionSidebar = localStorage.getItem('showDiscussionSidebar') !== 'false';

2023-06-23 07:31 UTC, sundasnoreen12 commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
>      }
for line 30-32 use this
const initialSidebar = SIDEBARS.DISCUSSIONS.ID.

2023-06-23 07:31 UTC, sundasnoreen12 commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
>        setCurrentSidebar(initialSidebar);
remove check for line 23

2023-06-23 10:18 UTC, sundasnoreen12 approved these changes
PR LGTM

2023-06-26 15:48 UTC, awais-ansari approved these changes

2023-06-27 00:30 UTC, muhammadadeeltajamul approved these changes

2023-06-27 09:05 UTC, merged