refactor: refactor code by creating 1 instance of header instead of 3
openedx/frontend-app-learning pull request #1164
Opened 2023-08-18 11:45 UTC by sundasnoreen12

[INF-1020](https://2u-internal.atlassian.net/browse/INF-1020)

**Description**

Fixed issue of 

1. bell icon appears, disappears and appears again.
2. When notifications are being loaded, the tray width shrinks.
3. When tray is closed and re-opened, it renders better with some formatting issues, as seen below

2023-08-21 11:41 UTC, awais-ansari requested changes

2023-08-21 11:41 UTC, awais-ansari commented on src/tab-page/TabPage.jsx
> +      {(courseStatus !== 'loading' && courseStatus !== 'loaded' && courseStatus !== 'denied') && (
!['loading', 'loaded', 'denied'].includes(courseStatus)

2023-08-21 12:36 UTC, awais-ansari approved these changes

2023-08-23 06:36 UTC, muhammadadeeltajamul approved these changes

2023-08-23 09:46 UTC, merged