fix: make progress graph respect course settings
openedx/frontend-app-learning pull request #1194
Opened 2023-09-21 12:19 UTC by RafayGhafoor

Closes #753

2023-09-21 12:19 UTC, openedx-webhooks commented
Thanks for the pull request, @RafayGhafoor!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2023-09-21 13:18 UTC, RafayGhafoor commented
@Agrendalath, Please check when you have time. Thank you.

2023-09-21 14:56 UTC, Agrendalath commented
@RafayGhafoor, I believe @navinkarkera is the reviewer here.

2023-09-21 15:52 UTC, RafayGhafoor commented
Thank you, I will mention him here.

@navinkarkera, Please check when you time.

2023-09-25 07:17 UTC, navinkarkera requested changes
@RafayGhafoor I have left some suggestions in edx-platform PR which will require some changes here as well.

2023-09-25 11:12 UTC, RafayGhafoor commented
@navinkarkera, I have made the changes.

2023-09-25 13:54 UTC, navinkarkera approved these changes
:+1: @RafayGhafoor
- [x] I tested this: (tested progress graph locally in devstack)
- [x] I read through the code
- [ ] ~I checked for accessibility issues~
- [ ] ~Includes documentation~
- [ ] ~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~

2023-09-25 19:13 UTC, RafayGhafoor commented
Test

2023-10-05 17:58 UTC, farhaanbukhsh approved these changes
👍

✅ I tested this on my devstack and it works cleanly.
✅ I read through the code
❌ I checked for accessibility issues
❌ Includes documentation
❌ I made sure any change in configuration variables is reflected in the corresponding client's configuration-secure repository.

2023-10-10 07:37 UTC, itsjeyd commented
@RafayGhafoor Thank you for this contribution!

@Agrendalath @farhaanbukhsh Once tests are green, will we need another review from the Aurora team to be able to merge these changes, or are your approvals binding?

2023-10-10 11:52 UTC, Agrendalath commented
@itsjeyd, it's a bug fix, so I suppose that we could ask [the CCs](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project) of the frontend repos to merge this.

2023-10-11 04:54 UTC, navinkarkera commented
@brian-smith-tcril Could you please help us triggering the tests, review and merge the PR here?

2023-10-11 14:57 UTC, brian-smith-tcril approved these changes
This makes sense!

Once https://github.com/openedx/edx-platform/pull/33308/files lands, we will be getting back a boolean value for `disable_progress_graph` from the `progress` endpoint.

This MFE will grab that as a part of `getProgressTabData`
https://github.com/openedx/frontend-app-learning/blob/5604def491098d763801ce198cd977753c550f56/src/course-home/data/api.js#L223-L224

It will be camelCased and turn into `disableProgressGraph`
https://github.com/openedx/frontend-app-learning/blob/5604def491098d763801ce198cd977753c550f56/src/course-home/data/api.js#L234

And then we will be able to use it in `ProgressTab`

LGTM!

2023-10-11 15:10 UTC, navinkarkera commented
@brian-smith-tcril I have merged https://github.com/openedx/edx-platform/pull/33308/, this PR can be merged now.

2023-10-11 15:28 UTC, merged

2023-10-11 15:28 UTC, openedx-webhooks commented
@RafayGhafoor 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1194&entry.1484655318=https://github.com/RafayGhafoor&entry.752974735=2023-09-21+12:19&entry.1917517419=2023-10-11+15:28&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->