feat: legacy course navigation
openedx/frontend-app-learning pull request #1239
Opened 2023-11-22 15:10 UTC by ArturGaspar

## Description

Add an option to enable the legacy course navigation where clicking a breadcrumb leads to the course index page highlighting the selected section.

## Testing instructions

1. Set ENABLE_LEGACY_NAV='true' and ENABLE_JUMPNAV='false'
2. Open a course unit
3. Click the breadcrumb navigation
4. See that you are redirected to the course index page and that the item corresponding to the selected breadcrumb is highlighted

![image](https://github.com/openedx/frontend-app-learning/assets/1616648/fd4dad34-8027-4d53-90d0-31881422e4f3)
![image](https://github.com/openedx/frontend-app-learning/assets/1616648/e27613c9-dc8b-4129-8a02-29c8ca52134e)

2023-11-22 15:10 UTC, openedx-webhooks commented
Thanks for the pull request, @ArturGaspar! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-11-23 13:58 UTC, itsjeyd commented
@ArturGaspar Thank you for this contribution! Please let me know when internal review is done and the build is green.

@jmakowski1123 This is a user-facing change so we'll most likely need a feature ticket for it. Could you please confirm? 

CC @mphilbrick211

2023-11-23 16:33 UTC, Agrendalath commented
@ArturGaspar, this needs to pass through the client's UX QA first, so we can convert the PR to a draft for now.

cc: @itsjeyd

2023-11-23 22:31 UTC, Agrendalath requested changes

2023-11-23 22:31 UTC, Agrendalath commented on .env.development
> +ENABLE_LEGACY_NAV=''
The `README.rst` entry is missing in this PR. When you add it, please change the last words to `section or subsection.`.

2023-11-23 22:31 UTC, Agrendalath commented on src/course-home/outline-tab/OutlineTab.jsx
> +  // Remove the initial # sign.
We should add a higher-level comment above this one to explain what we do here (and why).

2023-11-23 22:31 UTC, Agrendalath commented on src/course-home/outline-tab/OutlineTab.jsx
> +                      (selectedSectionId === null)
```suggestion
                      (selectedSectionId === undefined)
```

The backport PR (https://github.com/open-craft/frontend-app-learning/pull/6) is not really a backport; usually, it's better to open an upstream PR for the review, and then cherry-pick the changes for the backport.

2023-11-23 22:31 UTC, Agrendalath commented on src/course-home/outline-tab/Section.jsx
> +    <div className={classNames('row w-100 m-0', { 'bg-light-200': selected })}>
Why do we use it as an inline CSS instead of adding a CSS class? In the current approach, we won't be able to override this color with a branding package.

2023-11-23 22:31 UTC, Agrendalath commented on src/course-home/outline-tab/SequenceLink.jsx
> +        <div className={classNames('row w-100 m-0', { 'bg-light-200': selected })}>
I recalled that the legacy approach also scrolls the page down to the highlighted unit. This is particularly useful on mobile devices. We cannot rely on adding `id={id}` (e.g., to the `<li>` tag), but we could do something like this:

```js
const sequenceLinkRef = useRef(null);
const mutationObserver = useRef(null);

// Scroll to the selected element.
useEffect(() => {
  if (selected) {
    mutationObserver.current = new MutationObserver((mutationsList, observer) => {
      // Check if the element is already in the DOM.
      if (sequenceLinkRef.current && document.body.contains(sequenceLinkRef.current)) {
        sequenceLinkRef.current.scrollIntoView({ behavior: 'smooth' });
        // Disconnect the observer once the element is found and scrolled to.
        observer.disconnect();
      }
    });

    mutationObserver.current.observe(document.body, { childList: true, subtree: true });
  }

  // Clean up the observer on component unmount.
  return () => {
    if (mutationObserver.current) {
      mutationObserver.current.disconnect();
    }
  };
}, [selected]);
```
`sequenceLinkRef` can be added to the `li` element.

However, this would only work for the sequences. We should think of something that could be reused for sections and sequences.

2023-11-23 22:31 UTC, Agrendalath commented on src/course-home/outline-tab/SequenceLink.jsx
> +        <div className={classNames('row w-100 m-0', { 'bg-light-200': selected })}>
Why do we add the styles here instead of the grandparent `li` node?

Currently, it looks like this (I changed the color a bit to make this more apparent):
![image](https://github.com/open-craft/frontend-app-learning/assets/3189670/79247217-ceff-4650-bda5-b10d6f2b1766)

If we move it to `li`, it will look like this:
![image](https://github.com/open-craft/frontend-app-learning/assets/3189670/d8e16da6-73ff-498c-8db9-d38502d2141b)

2023-11-23 22:31 UTC, Agrendalath commented on src/courseware/course/CourseBreadcrumbs.jsx
> +  let defaultTo;
This name is somewhat confusing. Maybe we could use something like `regularLinkPath` or `regularLinkRoute`?

2023-11-24 12:03 UTC, ArturGaspar commented on src/course-home/outline-tab/OutlineTab.jsx
> +  // Remove the initial # sign.
@Agrendalath Please let me know if it's good in the latest version now.

2023-11-24 12:06 UTC, ArturGaspar commented on src/course-home/outline-tab/SequenceLink.jsx
> +        <div className={classNames('row w-100 m-0', { 'bg-light-200': selected })}>
I initially did it that way because the first and last elements appear a bit taller than the others (due to the container having more padding), but I have changed this now and updated the screenshots in the PR.

2023-11-27 07:10 UTC, ArturGaspar commented on src/course-home/outline-tab/SequenceLink.jsx
> +        <div className={classNames('row w-100 m-0', { 'bg-light-200': selected })}>
I did it without the MutationObserver and it appears to work as expected, and for both section and subsection links. Implementation is in `src/course-home/outline-tab/hooks.js`.

2023-11-27 12:59 UTC, Agrendalath reviewed
@ArturGaspar, looks good! Just two minor comments. 

I'm not leaving a "formal" +1 on this PR yet, as we want to wait for the client's QA.

2023-11-27 12:59 UTC, Agrendalath commented on src/course-home/outline-tab/OutlineTab.jsx
> +                      (selectedSectionId !== undefined)
```suggestion
                      (selectedSectionId)
```

Nit: it should be less error-prone if we checked all falsy values.

2023-11-27 12:59 UTC, Agrendalath commented on src/course-home/outline-tab/Section.scss
> +.section > div > div > .collapsible-body {
```suggestion
.section .collapsible-body {
```

This should be specific enough - we should not strictly rely on the Paragon's implementation.

2023-12-08 19:34 UTC, Agrendalath approved these changes
:+1:

* [x] I tested this: checked that the legacy course navigation works as expected
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [x] Includes documentation: n/a

2023-12-08 19:34 UTC, Agrendalath commented
@ArturGaspar, please mark this PR as ready for review.

2023-12-14 01:17 UTC, jmakowski1123 commented
There is a larger project in play now to bring back the sidebar navigation experience, which was the original experience that was replaced by the breadcrumbs. Part of the consideration in that project is how many navigation options we need, and the breadcrumb pathway is being reconsidered in that context. We need to come to a decision first about which navigation experience the core product supports as the primary one, before investing in this. Suggest to put this on temporarily on hold. https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3909779457/Feature+Enhancement+Proposal+Restore+the+left-sidebar+navigation+in+the+learner+experience

2023-12-15 14:46 UTC, Agrendalath commented
@jmakowski1123, the project you mentioned sounds like a significant change. Do you know if there is any timeline for making this decision?

This PR brings back the legacy (non-MFE) experience - it only changes the action triggered by clicking on the text in the course navigation. If we decide to delete the breadcrumbs, the scope of that project won't be altered in any way by this change.
In the meantime, this PR gives us a (rather nice) side effect of highlighting specific parts of the Course Outline when redirecting users from external pages. Let's say we add a link like `LMS_URL/course/{course_name}#{block_id}` to the external page. When users click on it, they will be directed to the Course Outline page with the highlighted `block_id` (section/subsection), as shown on the screenshots. This is especially useful for the mobile experience, as the page is automatically scrolled to the highlighted element of the Course Outline.

cc: @itsjeyd

2023-12-21 19:11 UTC, jmakowski1123 commented
> @jmakowski1123, the project you mentioned sounds like a significant change. Do you know if there is any timeline for making this decision?
> 
> This PR brings back the legacy (non-MFE) experience - it only changes the action triggered by clicking on the text in the course navigation. If we decide to delete the breadcrumbs, the scope of that project won't be altered in any way by this change. In the meantime, this PR gives us a (rather nice) side effect of highlighting specific parts of the Course Outline when redirecting users from external pages. Let's say we add a link like `LMS_URL/course/{course_name}#{block_id}` to the external page. When users click on it, they will be directed to the Course Outline page with the highlighted `block_id` (section/subsection), as shown on the screenshots. This is especially useful for the mobile experience, as the page is automatically scrolled to the highlighted element of the Course Outline.
> 
> cc: @itsjeyd

I'd like to push for agreement/decision by the end of Jan, with the goal of beginning implementation in Feb for hopeful inclusion in Redwood. You can follow, and join, the conversation here, please feel free to join the wiki thread: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3909779457/Feature+Enhancement+Proposal+Restore+the+left-sidebar+navigation+in+the+learner+experience

2024-01-08 12:54 UTC, xitij2000 approved these changes
#
:+1:

- [x] I tested this: tested on tutor devstack
- [x] I read through the code

2024-02-16 13:56 UTC, itsjeyd commented
> I'd like to push for agreement/decision by the end of Jan, with the goal of beginning implementation in Feb for hopeful inclusion in Redwood. You can follow, and join, the conversation here, please feel free to join the wiki thread: [openedx.atlassian.net/wiki/spaces/OEPM/pages/3909779457/Feature+Enhancement+Proposal+Restore+the+left-sidebar+navigation+in+the+learner+experience](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3909779457/Feature+Enhancement+Proposal+Restore+the+left-sidebar+navigation+in+the+learner+experience)

Hey @jmakowski1123, based on a brief look at the wiki thread it seems like product review is still in progress. Do you have any updates about the timeline for this work?

CC @Agrendalath @ArturGaspar

2024-03-11 08:44 UTC, itsjeyd commented
Hey @cassiezamparini, would you have time to [help](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3909779457/Feature+Enhancement+Proposal%3A+Restore+the+left-sidebar+navigation+in+the+learner+experience?focusedCommentId=4047044699) get the ball rolling again here in terms of product review?

2024-03-11 08:49 UTC, cassiezamparini commented
@itsjeyd Sure thing! I'll add this to my to-do list for tomorrow :)

2024-03-12 10:28 UTC, cassiezamparini commented
@itsjeyd It looks like this feature is on hold based on the comments from @jmakowski1123 in this thread.

Also in order to do a product review, we need to follow the new process @ArturGaspar @Agrendalath - as outlined [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review). Please review the link above and follow the steps I mention below:

- [ ] Create product proposal using a Template: [Choose Your Template - Open Source Product Contributions](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3890249759) 
- [ ] Create a Product Proposal ticket in the platform-roadmap GitHub repository (with a link to the product proposal etc). Note, tickets must be created [here](https://github.com/openedx/platform-roadmap/issues/new?assignees=&labels=&projects=&template=01-roadmap-issue.yml&title=Put+Initiative+Name+Here). The ticket will get auto-added to the Open edX Roadmap project board: [Open edX Roadmap • openedx](https://github.com/orgs/openedx/projects/4/views/24)  
- [ ] The Submitter pings the Core Product Working Group in [Slack](https://openedx.org/slack) ([#wg-product-core](https://openedx.slack.com/archives/C057J2D1WU9)) and shares the proposal. You can ping **me** once you've created the proposal and I can ping the Core Product WG on your behalf. 

Please let me know if anything is unclear. We are still in the process of ironing out this new product review process, so your feedback will be welcomed.

2024-03-12 14:52 UTC, cassiezamparini commented
@itsjeyd @Agrendalath @ArturGaspar 

In relation to [Feature Enhancement Proposal: Restore the left-sidebar navigation in the learner experience](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3909779457/Feature+Enhancement+Proposal+Restore+the+left-sidebar+navigation+in+the+learner+experience?focusedCommentId=4047044699):

> Edward Zarecor:
> Yes, the design phase has wrapped up and dev phase is starting now.  It's targeted for GA in Redwood.

Thoughts?

2024-03-22 09:03 UTC, itsjeyd commented
@cassiezamparini Thanks for looking into the status of product review for this PR!

>> Edward Zarecor:
>> Yes, the design phase has wrapped up and dev phase is starting now. It's targeted for GA in Redwood.
>
> Thoughts?

I don't know what GA means, and I'm not sure how to proceed from here.

If the dev phase is starting now, does that mean we can consider this PR approved from the product perspective?

--

Either way, it's probably worth noting that my involvement here is limited to OSPR management (which currently doesn't include tracking individual steps of the product review process) 🙂 

From that perspective, the main question to answer is the one above, i.e. whether product review is done and we can move forward with finding engineering reviewers for this PR.

--

CC @ArturGaspar @Agrendalath @e0d

2024-03-22 09:06 UTC, itsjeyd commented
Internal-Ref: https://tasks.opencraft.com/browse/BB-8160

2024-03-25 20:58 UTC, jmakowski1123 commented
As part of the project to reimplement the left sidebar navigation ([full MVP spec here](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4025843740/Restoring+Left-sidebar+Navigation+MVP+Product+Requirements)), I do not think it is necessary to invest in any legacy navigation experiences. 

I'm assuming the point of proposing to revive the legacy breadcrumb experience is to make it easier for learners to see where they are in the course outline? This problem will be solved when we reimplement the left sidebar, as learners will be able to wayfind through the course outline without leaving the content. 

The left sidebar will be revived for the Redwood release in June and will be the default experience out of the box. @ArturGaspar does this meet your needs, and if so, can we close this proposal?

2024-04-19 14:41 UTC, ArturGaspar commented
@jmakowski1123 It is possible that the sidebar navigation would fulfil our needs, so I am converting this PR to a draft until the released version can be evaluated. Thank you.

2024-09-07 08:11 UTC, itsjeyd commented
Hey @ArturGaspar and @Agrendalath, just checking in:

> It is possible that the sidebar navigation would fulfil our needs, so I am converting this PR to a draft until the released version can be evaluated.

Do you have any updates on when this evaluation would happen?

2024-09-07 12:32 UTC, Agrendalath commented
@itsjeyd, it's in progress. We should have more info within the next two months.

cc: @ArturGaspar

2024-09-20 12:24 UTC, itsjeyd commented
Sounds good, thanks @Agrendalath.

2024-11-07 09:14 UTC, itsjeyd commented
@Agrendalath It's been [two months](https://github.com/openedx/frontend-app-learning/pull/1239#issuecomment-2335173490) now, so checking in to see if you have any updates to share :)

2024-11-07 19:06 UTC, Agrendalath commented
@itsjeyd, we haven't gotten a clear decision about this yet. It may take another month or two.

2024-12-19 10:33 UTC, Agrendalath commented
We will use the navigation sidebar. Closing.

2024-12-19 10:33 UTC, closed without merging