feat: added implementation for new sidebar
openedx/frontend-app-learning pull request #1260
Opened 2023-12-27 08:05 UTC by sundasnoreen12

[INF-1184](https://2u-internal.atlassian.net/browse/INF-1184)

**Description**
Stack notifications panel on top of discussions based on [Legacy Notifications vs Discussions Sidebar](https://www.figma.com/proto/PwKdrc6pQhlw5XJaB7hBrb/Legacy-Notifications-vs-Discussions-Sidebar?page-id=0%3A1&type=design&node-id=28-14107&viewport=625%2C3258%2C0.21&t=Cq10PY4QgOnlrpuh-9&scaling=scale-down&starting-point-node-id=28%3A14107&hotspot-hints=0&show-proto-sidebar=1) 

When a user navigates to a unit, the sidebar should open when:

1. Audit user: Notification is available for the panel.
2. Audit user: Course is using Openedx provider and Discussion is enabled on this unit.
3. Audit user: Course is using Openedx provider and Discussion is enabled on this unit and Notification is available for the panel.
4. Verified user: Course is using Openedx provider and Discussion is enabled on this unit.

Sidebar should open irrespective of whether the user has closed it on the previous unit they visited.

**Screenshots**
<img width="1113" alt="Screenshot 2023-12-26 at 6 54 53 PM" src="https://github.com/openedx/frontend-app-learning/assets/72802712/2756e935-5b6b-45f1-a5e6-a0cc78ff2bfb">

<img width="754" alt="Screenshot 2023-12-26 at 6 55 29 PM" src="https://github.com/openedx/frontend-app-learning/assets/72802712/2b0438dc-3b7c-4905-935b-e047a25468d6">

2023-12-27 13:47 UTC, awais-ansari requested changes

2023-12-27 13:47 UTC, awais-ansari commented on .env
> +ENABLE_SIDEBAR_NEW_VIEW='false'
update the flag name. `ENABLE_NEW_SIDEBAR` is more clear.

2023-12-27 13:47 UTC, awais-ansari commented on .env.development
> +ENABLE_SIDEBAR_NEW_VIEW='false'
update the flag name. ENABLE_NEW_SIDEBAR is more clear.

2023-12-27 13:47 UTC, awais-ansari commented on src/courseware/course/Course.jsx
> +  const showSidebarNewView = getConfig().ENABLE_SIDEBAR_NEW_VIEW;
showSidebarNewView  => showNewSidebar

2023-12-27 13:47 UTC, awais-ansari commented on src/courseware/course/new-sidebar/NewSidebarIcon.jsx
> +import { RightSidebarFilled, RightSidebarOutlined } from './icons/index';
import { RightSidebarFilled, RightSidebarOutlined } from './icons';

2023-12-27 13:47 UTC, awais-ansari commented on src/courseware/course/new-sidebar/NewSidebarIcon.jsx
> +export default injectIntl(SidebarIcon);
use useIntl hook instead of injectIntl

2023-12-27 13:47 UTC, awais-ansari commented on src/courseware/course/new-sidebar/NewSidebarIcon.jsx
> +      <Icon src={currentSidebar ? RightSidebarFilled : RightSidebarOutlined} className="m-0 m-auto" alt={intl.formatMessage(messages.openNotificationTrigger)} />
line length should not be greater than 120

2023-12-27 13:47 UTC, awais-ansari commented on src/courseware/course/new-sidebar/NewSidebarIcon.jsx
> +    </>
I'm not able to find Figma with the dot. Please share the link here.

2023-12-27 13:47 UTC, awais-ansari commented on src/index.jsx
> +        ENABLE_SIDEBAR_NEW_VIEW: process.env.ENABLE_SIDEBAR_NEW_VIEW || false,
update the flag name. ENABLE_NEW_SIDEBAR is more clear.

2023-12-27 13:47 UTC, awais-ansari commented on src/generic/upgrade-notification/UpgradeNotification.scss
> +}
use text-primary-500 instead of text-black

2023-12-27 13:47 UTC, awais-ansari commented on src/courseware/course/new-sidebar/icons/SvgRightSidebarOutlined.jsx
> +const SvgRightSidebarOutlined = (props) => (
rename => RightSidebarOutlined

2023-12-27 13:47 UTC, awais-ansari commented on src/courseware/course/new-sidebar/icons/SvgRightSidebarFilled.jsx
> +const SvgRightSidebarFilled = (props) => (
rename => RightSidebarFilled

2023-12-27 13:47 UTC, awais-ansari commented on src/courseware/course/new-sidebar/NewSidebarIcon.jsx
> +export default injectIntl(SidebarIcon);
use the same old sidebar file names. SidebarIcon instead of NewSidebarIcon file name

2023-12-27 14:25 UTC, awais-ansari requested changes

2023-12-27 14:25 UTC, awais-ansari commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +    isDiscussionbarAvailable,
refactor and modify the logic. Too much useEffects and states are using here.

2023-12-27 16:24 UTC, sundasnoreen12 commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +    isDiscussionbarAvailable,
I consolidated several useEffect blocks into a single one to eliminate the need for multiple instances. Additionally, it's essential to retain these states within the provider component to prevent redundancy in the code across various individual components.

2024-01-02 09:01 UTC, awais-ansari requested changes

2024-01-02 09:01 UTC, awais-ansari commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +  const isDiscussionbarAvailable = !(!topic?.id || !topic?.enabledInContext);
const isDiscussionbarAvailable = !(!topic?.id || !topic?.enabledInContext); 
this condition can be simplified.
const isDiscussionbarAvailable = topic?.id || topic?.enabledInContext

2024-01-02 09:19 UTC, sundasnoreen12 commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +  const isDiscussionbarAvailable = !(!topic?.id || !topic?.enabledInContext);
then this condition will work 
topic?.id && topic?.enabledInContext

2024-01-03 10:30 UTC, awais-ansari approved these changes

2024-01-05 09:04 UTC, ayesha-waris approved these changes

2024-01-08 08:40 UTC, merged