test: added test cases for new sidebar
openedx/frontend-app-learning pull request #1267
Opened 2024-01-08 12:05 UTC by sundasnoreen12

[INF-1210](https://2u-internal.atlassian.net/browse/INF-1210)

**Description**

1. successfully Open/Hide sidebar tray.
2. successfully close the notification widget.
3. successfully close the sidebar when we have no discussion widget and close the notification widget.
4. should display the Back to course button on small screens.

2024-01-10 10:15 UTC, awais-ansari requested changes
Just small nits.

2024-01-10 10:15 UTC, awais-ansari commented on src/courseware/course/new-sidebar/sidebars/discussions-notifications/notifications/NotificationsWidget.test.jsx
> +    'notification-widget',
nit: Indentation issue.

2024-01-10 10:15 UTC, awais-ansari commented on src/courseware/course/new-sidebar/sidebars/discussions-notifications/notifications/NotificationsWidget.test.jsx
> +      description: 'close the sidebar when we have no discussion widget and close the notification widget.',
rewrite it in a meaningful way.

2024-01-10 13:09 UTC, awais-ansari approved these changes

2024-01-11 10:46 UTC, ayesha-waris approved these changes

2024-01-11 10:54 UTC, merged