feat: use navigation sequence metadata to disabled prev/next buttons
openedx/frontend-app-learning pull request #1273
Opened 2024-01-12 17:15 UTC by mariajgrimaldi

### Description
This PR adds a flag check to navigation components

### How to test

### Other information

2024-01-12 17:15 UTC, openedx-webhooks commented
Thanks for the pull request, @mariajgrimaldi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2024-01-12 23:32 UTC, johnvente commented on src/courseware/course/Course.jsx
> +  const navigationDisabled = sequence ? sequence.navigationDisabled : false;
```suggestion
  const navigationDisabled = sequence?.navigationDisabled ?? false;
```

2024-01-18 10:48 UTC, itsjeyd commented
Hi @mariajgrimaldi, thank you for this contribution!

Like #1262, it seems to relate to https://github.com/openedx/platform-roadmap/issues/301, so I'm flagging it for product review.

CC @jmakowski1123

2024-02-12 22:16 UTC, johnvente commented on src/courseware/course/Course.jsx
> +            sectionId={section ? section.id : null}
```suggestion
            sectionId={section?.id ?? null}
```

2024-02-12 22:17 UTC, johnvente commented on src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
> +    isFirstUnit, isLastUnit, nextLink, previousLink, navigationDisabledPrevSequence, navigationDisabledNextSequence,
```suggestion
    isFirstUnit, 
    isLastUnit, 
    nextLink, 
    previousLink, 
    navigationDisabledPrevSequence, 
    navigationDisabledNextSequence,
```

2024-02-12 22:18 UTC, johnvente commented on src/courseware/course/sequence/sequence-navigation/hooks.js
> +    isFirstUnit, isLastUnit, nextLink, previousLink, navigationDisabledNextSequence, navigationDisabledPrevSequence,
```suggestion
    isFirstUnit, 
    isLastUnit, 
    nextLink, 
    previousLink, 
    navigationDisabledNextSequence, 
    navigationDisabledPrevSequence,
```

2024-02-12 22:22 UTC, johnvente commented on src/courseware/course/sequence/sequence-navigation/hooks.js
> +  const navigationDisabledNextSequence = sequence && sequence.navigationDisabled && isLastUnitInSequence;
```suggestion
  const sequenceNavigationDisabled = sequence?.navigationDisabled;
  const navigationDisabledPrevSequence = sequenceNavigationDisabled && isFirstUnitInSequence;
  const navigationDisabledNextSequence = sequenceNavigationDisabled && isLastUnitInSequence;
```

2024-02-12 22:42 UTC, santiagosuarezedunext commented
Hi Tim, this has already gone through product review, it was discussed and approved in [this post](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3853975595/Feature+Enhancement+Proposal+Hide+Sections+from+course+outline). greetings!
CC: @jmakowski1123

2024-02-13 12:56 UTC, mariajgrimaldi commented on src/courseware/course/Course.jsx
> +            sectionId={section ? section.id : null}
Thanks for the suggestion! But we shouldn't introduce changes not directly related to the implementation specified in the cover letter so it's easier for maintainers to review. Thanks though!

2024-02-13 12:59 UTC, mariajgrimaldi commented on src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
> +    isFirstUnit, isLastUnit, nextLink, previousLink, navigationDisabledPrevSequence, navigationDisabledNextSequence,
Thanks! I'll apply this suggestion right away since what we're introducing is making the line a bit too long

2024-02-13 13:08 UTC, mariajgrimaldi commented on src/courseware/course/sequence/sequence-navigation/hooks.js
> +    navigationDisabledPrevSequence,
Although I don't like adding style changes not directly related to the implementation, as I said before this line was getting too long

2024-02-13 14:21 UTC, johnvente approved these changes
LGTM! thanks

2024-02-13 17:36 UTC, BryanttV commented
Hi @mariajgrimaldi, I tested this PR in my local and it works correctly!

2024-02-13 17:36 UTC, BryanttV approved these changes

2024-02-22 13:29 UTC, itsjeyd commented
Hey @mariajgrimaldi, aside from fixing conflicts this still needs approval from a CC and/or maintainer, right?

2024-03-01 17:44 UTC, mariajgrimaldi commented
Sorry for the delay, @itsjeyd, yes! We still need the maintainers' approval.

2024-03-01 18:00 UTC, arbrandes commented
I'll bite.  Let's see if we can get this working in a PR sandbox, first.

2024-03-01 18:08 UTC, mariajgrimaldi commented
@arbrandes: this needs https://github.com/openedx/edx-platform/pull/34049 to work, is there a way to configure it?

2024-03-01 18:11 UTC, arbrandes commented
Yes, there is!  I just did.  Let's see if it works.  It'll take up to an hour for the sandbox to come up.

2024-03-01 19:04 UTC, open-craft-grove commented
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1273-1395ab.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1273-1395ab.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1273-1395ab-51564656-6300190337-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1273-1395ab-51564656-6300190337-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1273-1395ab-51564656-6300190337-tutor-requirements.txt)

2024-03-05 17:11 UTC, arbrandes commented
I've tested this in the sandbox, and it works!  Now, to look at the code.

2024-03-05 17:41 UTC, arbrandes requested changes
Just a couple of changes, otherwise looks and works great!

2024-03-05 17:41 UTC, arbrandes commented on src/courseware/course/Course.jsx
> +        {!navigationDisabled && (
```suggestion
        {navigationDisabled || (
```

Dual negatives are not great for reading code.

2024-03-05 17:41 UTC, arbrandes commented on src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
> +    return !navigationDisabledPrevSequence && (
```suggestion
    return navigationDisabledPrevSequence || (
```

2024-03-05 17:41 UTC, arbrandes commented on src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
> +    return !navigationDisabledNextSequence && (
```suggestion
    return navigationDisabledNextSequence || (
```

2024-03-05 17:41 UTC, arbrandes commented on src/courseware/course/sequence/sequence-navigation/hooks.js
> +  const sequenceNavigationDisabled = sequence?.navigationDisabled;
```suggestion
  const sequenceNavigationDisabled = sequence.navigationDisabled;
```

It doesn't look like `sequence` is optional, at this point.

2024-03-07 16:35 UTC, mariajgrimaldi commented on src/courseware/course/Course.jsx
> +        {!navigationDisabled && (
Yes, of course. Thanks!

2024-03-07 18:55 UTC, mariajgrimaldi commented
@arbrandes: comments addressed. Thank you!

2024-03-07 19:35 UTC, open-craft-grove commented
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1273-1395ab.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1273-1395ab.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1273-1395ab-51564656-6345779268-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1273-1395ab-51564656-6345779268-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1273-1395ab-51564656-6345779268-tutor-requirements.txt)

2024-03-08 13:50 UTC, arbrandes approved these changes

2024-03-08 13:51 UTC, merged

2024-03-08 13:51 UTC, openedx-webhooks commented
@mariajgrimaldi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1273&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2024-01-12+17:15&entry.1917517419=2024-03-08+13:51&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->