fix: fixed empty section issue
openedx/frontend-app-learning pull request #1292
Opened 2024-02-14 11:06 UTC by sundasnoreen12

[INF-1254](https://2u-internal.atlassian.net/browse/INF-1254)

**Description**
An empty section is displayed when there are no notifications or discussion bars available for the in-context sidebar.
https://www.loom.com/share/5237ee3f8d5f49c884567cbeb7af5262?sid=ab72518e-4cf4-410b-8be9-ce71969a80fb

**A.C**
Section shouldn’t be visible when notification and discussion bar are not available for the incontext sidebar.

2024-02-14 19:43 UTC, awais-ansari requested changes

2024-02-14 19:43 UTC, awais-ansari commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +    }
query.get('sidebar') === 'true' this case is missing here.

2024-02-15 01:44 UTC, muhammadadeeltajamul approved these changes

2024-02-15 08:10 UTC, awais-ansari approved these changes

2024-02-15 10:56 UTC, merged