lk/updated contract
openedx/frontend-app-learning pull request #1328
Opened 2024-03-18 20:14 UTC by leangseu-edx

- **Lk/learning language selection (#1299)**
- **chore: add whole_course_translation and language to courseware meta (#1305)**
- ** feat(AU-1863): Add feedback widget UI mock**
- **chore: add src and dest translation**
- **feat: first iteration of plugin translation**
- **chore: follow the contract**

2024-03-19 14:09 UTC, nsprenkle requested changes
The data values don't match contract. Please update so they match the contract or, if it makes more sense to change the contract, let's do that, but they must match

2024-03-19 21:15 UTC, Rodra approved these changes
Looks great !

2024-03-19 21:43 UTC, Rodra commented on plugins/UnitTranslationPlugin/translation-selection/index.jsx
> +      <FeedbackWidget
Why are we rendering the widget here ?

2024-03-20 13:38 UTC, leangseu-edx commented on plugins/UnitTranslationPlugin/translation-selection/index.jsx
> +      <FeedbackWidget
This is just a place holder. It create the virtual dom here. But it get moved with ref.

2024-03-20 13:51 UTC, Rodra commented on plugins/UnitTranslationPlugin/translation-selection/index.jsx
> +      <FeedbackWidget
Ohh I see... COOL !

2024-03-20 13:51 UTC, Rodra approved these changes

2024-03-20 15:33 UTC, nsprenkle approved these changes
LGTM but before you merge, can you update PR title? This is no longer just language config, it is also feedback, etc.

2024-03-20 17:38 UTC, merged