[FC-0056][Plugin] Course outline sidebar
openedx/frontend-app-learning pull request #1344
Opened 2024-04-04 11:53 UTC by ihor-romaniuk

**Settings**

```yaml
EDX_PLATFORM_REPOSITORY: https://github.com/raccoongang/edx-platform.git
EDX_PLATFORM_VERSION: ts-develop
```

### Description
This pull request adds an important feature to our platform: displaying a navigation sidebar within a given course.

**Note:** Initial solution without using `Frontend Plugin Framework` https://github.com/openedx/frontend-app-learning/pull/1342 

### Design
https://www.figma.com/file/gew5tORDX4Q7wxOS8vjqZu/side-nav-OEX?type=design&node-id=318-3234&mode=design&t=rBe1ToNYP8RY6QOp-0

![image](https://github.com/openedx/frontend-app-learning/assets/17108583/a5a745f2-34fc-43fb-869b-5880ee441d1a)

### Testing instructions
1. Run master devstack.
2. Start platform make dev.up.lms+cms+frontend-app-course-authoring and make checkout on this branch.
3. Go to Course Unit page from the Course Outline page.

2024-04-04 11:54 UTC, openedx-webhooks commented
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2024-04-04 11:56 UTC, ihor-romaniuk commented on src/courseware/course/Course.jsx
> +  const navigationDisabled = isEnabledOutlineSidebar || (sequence?.navigationDisabled ?? false);
The `useSelector(getCoursewareOutlineSidebarSettings)` should be replaced with a method that check if the Sidebar plugin is available and displayed.

2024-04-08 11:16 UTC, ihor-romaniuk commented on src/courseware/course/sidebar/sidebars/index.js
> +export const checkIsSidebarAvailable = (id) => Object.keys(SIDEBARS).includes(id);
Through the close interaction of the navigation plugin's display with the application's functionality display (sidebar display order, breadcrumb display, etc.), we should have a way to check for an active navigation plugin.

Perhaps it should be reworked and placed in a global state and have a list of connected plugins.

2024-04-08 11:18 UTC, ihor-romaniuk commented on src/index.scss
> +@import "../plugins/index.scss";
We needed to be able to include style files from plugins with the ability to use the Paragon system, so we decided to add one entry point for all plugin styles.

2024-04-08 18:03 UTC, arbrandes requested changes
Thank you for taking on this work!  My first big request for a change, however, is the following:

Any feature that should be on by default - which is the case with this sidebar - should **not** be a plugin.  It can be implemented as default content inside a plugin slot, but users should not have to change their configuration to get the corresponding functionality.

In other words, I would like to see all components and corresponding data functions moved out of plugins, but with one caveat: we should create an example plugin that disables the functionality being introduced, and document how to use it.  This means we'll also have to test that this "disable plugin" actually works.

2024-04-11 07:34 UTC, ihor-romaniuk commented
@arbrandes I created a new PR https://github.com/openedx/frontend-app-learning/pull/1349, which will wrap insertion points of triggers for calling the navigation sidebar, added sidebar accessibility checks to hide breadcrumbs when a sidebar is present, and added an example of a standard configuration in `env.config.jsx`.

2024-04-26 07:45 UTC, itsjeyd commented
@ihor-romaniuk 

> I created a new PR https://github.com/openedx/frontend-app-learning/pull/1349, ...

Does that PR replace this one? Asking because I'd like to understand if we need to keep this PR open.

2024-04-26 07:50 UTC, itsjeyd commented
OSPR management note: This is part of a set of PRs for implementing Phase 1 changes for the FC-0056 project. We can [consider it approved](https://github.com/openedx/frontend-app-learning/pull/1342#issuecomment-2074998975) from the product perspective.

CC @GlugovGrGlib

2024-04-26 09:19 UTC, closed without merging

2024-04-26 09:19 UTC, openedx-webhooks commented
@ihor-romaniuk Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1344&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2024-04-04+11:53&entry.1917517419=2024-04-26+09:19&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->

2024-04-26 09:20 UTC, ihor-romaniuk commented
The main PR about the course outline sidebar functionality https://github.com/openedx/frontend-app-learning/pull/1349