feat: [FC-0056] create course outline sidebar
openedx/frontend-app-learning pull request #1375
Opened 2024-04-30 08:36 UTC by ihor-romaniuk

**Settings**

```yaml
EDX_PLATFORM_REPOSITORY: https://github.com/raccoongang/edx-platform.git
EDX_PLATFORM_VERSION: ts-develop
```

### Description
This pull request adds an important feature to our platform: displaying a navigation sidebar within a given course.

Interaction with feature flag `courseware.show_default_right_sidebar` has been added to control the default display of the discussion sidebar and `courseware.disable_navigation_sidebar` to control of enabling the course outline sidebar. 

Discussions or Notifications sidebar shouldn't be opened on Learning MFE by default. If waffle flag enabled - Discussions always opens on the pages with discussions, if user is in Audit and course has verified mode - show Notifications.

### Depends on BE PRs
- [feat: [FC-0056] Implement Sidebar Navigation](https://github.com/openedx/edx-platform/pull/34457)
- Waffle flag to control of displaying the right (discussions & notifications) sidebar by default - **Will be opened soon**
- Waffle flag to control of enabling the course outline sidebar - **Will be opened soon**

### Design
https://www.figma.com/file/gew5tORDX4Q7wxOS8vjqZu/side-nav-OEX?type=design&node-id=318-3234&mode=design&t=rBe1ToNYP8RY6QOp-0

![image](https://github.com/openedx/frontend-app-learning/assets/17108583/a5a745f2-34fc-43fb-869b-5880ee441d1a)

### Testing instructions
1. Run master devstack.
2. Start platform make dev.up.lms+cms+frontend-app-course-authoring and make checkout on this branch.
3. Go to Course Unit page from the Course Outline page.

2024-04-30 08:37 UTC, openedx-webhooks commented
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-04-30 12:01 UTC, open-craft-grove commented
Sandbox deployment failed 💥
Please check the settings and requirements.
Retry deployment by pushing a new commit or updating the requirements/settings in the pull request's description.
📜 [Failure Logs](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6748408619.log)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6748408619-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6748408619-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6748408619-tutor-requirements.txt)

2024-04-30 18:10 UTC, brian-smith-tcril commented
I was able to get this working in tutor locally by merging https://github.com/openedx/edx-platform/pull/34650 into a new branch I made off of latest `edx-platform` master https://github.com/brian-smith-tcril/edx-platform/tree/sidebar-early-merge

I ran
```sh
tutor images build openedx-dev --build-arg EDX_PLATFORM_REPOSITORY=https://github.com/brian-smith-tcril/edx-platform.git --build-arg EDX_PLATFORM_VERSION=sidebar-early-merge
```

and used this plugin
```py
from tutormfe.hooks import MFE_APPS

@MFE_APPS.add()
def _add_my_mfe(mfes):
    mfes["learning"] = {
        "repository": "https://github.com/raccoongang/frontend-app-learning.git",
        "port": 2000,
        "version": "romaniuk/course-outline-sidebar",
    }
    return mfes
```

Since the `ts-develop` branch is ~150 commits behind upstream, it is not working with latest tutor nightly (I believe this is because of the move from node 16 to node 18)

I believe if you rebase https://github.com/openedx/edx-platform/pull/34650 on latest upstream master and point to that branch instead of `ts-develop` the sandbox should deploy properly.

2024-05-01 15:16 UTC, arbrandes commented
Until [the required backend PR](https://github.com/openedx/edx-platform/pull/34650) is merged, I'm moving this to Draft status.

2024-05-02 09:07 UTC, ihor-romaniuk commented
@brian-smith-tcril Thanks for notice that.
I changed the deploy branch to `NiedielnitsevIvan/FC-0056/feature/waffle-flag-for-displaying-discussions-tab` which should be up-to-date and include all required backend changes.
But

2024-05-02 09:32 UTC, open-craft-grove commented
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1375-c25332.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1375-c25332.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6762945355-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6762945355-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6762945355-tutor-requirements.txt)

2024-05-02 15:54 UTC, ihor-romaniuk commented
Update branch with added a few UI enhancements:
- Highlight the active section
- Highlight the active subsections when it collapsed
- Make unit row clickable instead of just unit name

2024-05-02 16:52 UTC, open-craft-grove commented
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1375-c25332.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1375-c25332.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6767288531-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6767288531-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6767288531-tutor-requirements.txt)

2024-05-07 07:49 UTC, ihor-romaniuk commented
Update branch: made a refactoring according to changes in backend endpoints https://github.com/openedx/edx-platform/pull/34650

2024-05-07 08:52 UTC, open-craft-grove commented
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1375-c25332.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1375-c25332.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6794688953-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6794688953-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1375-c25332-51564656-6794688953-tutor-requirements.txt)

2024-05-07 14:44 UTC, arbrandes requested changes
Looks good!  I find this implementation is easier to reason about than the previous one.  Thank you!  It will make it easier for us to revisit this later when we attempt to implement the same functionality via PluginSlots.

Oh, and I tested it against a deploy of master via Tutor nightly, and it seems to work well.

I do have a couple of nits though, if you don't mind.

2024-05-07 14:44 UTC, arbrandes commented on src/courseware/course/sequence/Sequence.test.jsx
> +    // );
Mind removing the commented out code?  Unless it's here for documentation.

2024-05-07 14:44 UTC, arbrandes commented on src/courseware/course/sequence/Sequence.test.jsx
> +    // render(<Sequence {...mockData} />, { wrapWithRouter: true });
Another commented line.

2024-05-07 14:44 UTC, arbrandes commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
> +  const isDefaultDisplayRightSidebar = useSelector(getCoursewareOutlineSidebarSettings).alwaysOpenAuxiliarySidebar;
```suggestion
  const alwaysOpenAuxiliarySidebar = useSelector(getCoursewareOutlineSidebarSettings).alwaysOpenAuxiliarySidebar;
```

Do you mind refactoring so that we don't have a mismatch between the waffle flag name and the name we use here?

2024-05-07 15:48 UTC, ihor-romaniuk commented on src/courseware/course/sequence/Sequence.test.jsx
> +    // );
Sure, I remove it

2024-05-07 15:49 UTC, ihor-romaniuk commented on src/courseware/course/sequence/Sequence.test.jsx
> +    // render(<Sequence {...mockData} />, { wrapWithRouter: true });
Also delete

2024-05-07 15:50 UTC, ihor-romaniuk commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
> +  const isDefaultDisplayRightSidebar = useSelector(getCoursewareOutlineSidebarSettings).alwaysOpenAuxiliarySidebar;
Agree, refactored. Thanks.

2024-05-07 16:01 UTC, arbrandes approved these changes
Thank you!  Approved!

2024-05-07 16:02 UTC, merged

2024-05-07 16:02 UTC, openedx-webhooks commented
@ihor-romaniuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1375&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2024-04-30+08:36&entry.1917517419=2024-05-07+16:02&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->

2024-05-09 05:34 UTC, GlugovGrGlib commented
This PR is the part of - https://github.com/openedx/platform-roadmap/issues/329