feat: option to show/hide ungraded assignment in progress page
openedx/frontend-app-learning pull request #1380
Opened 2024-05-06 10:48 UTC by navinkarkera

Adds option to show ungraded assignment/problems in progress page.

`Private-ref`: [BB-8824](https://tasks.opencraft.com/browse/BB-8824)

**Test instructions:**

* Setup tutor nightly locally.
* Mount this repository using `tutor mounts add /path/to/frontend-app-learning`.
* Run `npm install` in this directory.
* Run `tutor dev launch -I`.
* Add `"SHOW_UNGRADED_ASSIGNMENT_PROGRESS": True,` to `MFE_CONFIG` dict `$(tutor config printroot)/env/apps/openedx/settings/lms/development.py`
* Go to progress tab in any course in learning mfe and confirm that ungraded assignments are displayed.

2024-05-06 10:48 UTC, openedx-webhooks commented
Thanks for the pull request, @navinkarkera!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/committers-frontend-app-learning`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-05-23 15:22 UTC, itsjeyd commented
Hey @navinkarkera, this seems to be [affecting user-facing features](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) -- is there a product proposal for it? If not, you'll need to create one. See [Product Review Process](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process) to get started.

CC @Agrendalath

2024-05-23 15:25 UTC, Agrendalath commented
@itsjeyd, this is still under the client QA, and we'll need to make some adjustments to the current approach. I'll convert this to a draft for now.

2024-05-23 15:47 UTC, itsjeyd commented
@Agrendalath I don't have permission to change to draft either, looks like @navinkarkera would have to do it himself.

bq. ... this is still under the client QA, and we'll need to make some adjustments to the current approach.

Good to know! If you don't expect to be making massive changes, I'd suggest to get started on the product proposal sooner rather than later, as it can take a while to complete.

2024-05-28 11:41 UTC, navinkarkera commented
@Agrendalath @itsjeyd Created a ticket: https://github.com/openedx/platform-roadmap/issues/359 in platform-roadmap GitHub repository

2024-05-31 07:36 UTC, itsjeyd commented
Thanks @navinkarkera. I think you'll also need to add a proposal to the wiki (per step 1a of [https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).

CC @ali-hugo @cassiezamparini for confirmation -- the process hasn't changed, right? Starting the product review process requires both a wiki proposal and a road map ticket?

2024-06-03 07:37 UTC, ali-hugo commented
@itsjeyd There doesn't seem to be a hard and fast rule about this. I've seen some smaller proposals accepted with just the road map ticket, and no wiki proposal - I think this proposal might fall into that category (like @navinkarkera mentioned on the wg-product-core Slack channel, the change is relatively minor, and reintroduces a legacy feature that's missing from the new MFE). 

I will confirm this in the Core Product meeting tomorrow and let you both know.

2024-06-05 09:34 UTC, ali-hugo commented
@navinkarkera @itsjeyd Ok, I got some clarification about the review process (I will be updating the [wiki procedure](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review) soon). 

If https://github.com/openedx/platform-roadmap/issues/359 simply reintroduces missing legacy functionality, and does not  introduce/change any user-facing features, it does not require a separate wiki proposal (@navinkarkera Can you confirm that this is the case?)

What we _do_ need, is a second reviewer who is not from OpenCraft. Do either of you know of a Product person who might have some experience with the Progress Page?

2024-06-06 08:02 UTC, itsjeyd commented
Thanks a lot for the follow-up and info @ali-hugo! 

> Do either of you know of a Product person who might have some experience with the Progress Page?

I don't, unfortunately.

2024-06-06 09:04 UTC, navinkarkera commented
@ali-hugo Thanks for the clarification!

> simply reintroduces missing legacy functionality, and does not introduce/change any user-facing features, it does not require a separate wiki proposal (@navinkarkera Can you confirm that this is the case?)

I haven't used this feature before but I think @Agrendalath can confirm that it was part of legacy.

> What we do need, is a second reviewer who is not from OpenCraft. Do either of you know of a Product person who might have some experience with the Progress Page?

Unfortunately, no.

2024-06-06 13:26 UTC, ali-hugo commented
@navinkarkera I decided to take a look through the screenshots in the meantime. Everything looks good to me. Once we have confirmation that this is indeed a legacy feature, I will find a second person to do a product review.

2024-06-06 13:41 UTC, Agrendalath commented
@ali-hugo, this is how the ungraded subsections looked on the legacy Progress page. We just changed "Practice Scores" to "Ungraded Problem Scores", as the latter is more self-explanatory.
![image](https://github.com/openedx/frontend-app-learning/assets/3189670/ac206c3f-c981-41ee-a888-b51a9d17e7fa)

2024-06-06 14:04 UTC, ali-hugo commented
@Agrendalath Thanks for the screenshot. That wording update makes sense to me. 👍 

@asma-ahmedd Would you mind taking a look through this PR when you have a moment, please? We need a second product thumbs up before it can move forward. [Here is a link to the roadmap ticket](https://github.com/openedx/platform-roadmap/issues/359) with some background. 

Feel free to reach out to me if you have any questions.

2024-06-10 05:09 UTC, asma-ahmedd commented
@ali-hugo
Thank you for including me in this PR. I really appreciate the effort put into it. Here are my thoughts and feedback on the proposal:

**Positive Aspect**

It's crucial to maintain consistency between the legacy system and the new MFE, and adding the option to display ungraded assignments/problems addresses this need effectively.

Enabling the feature via a flag in MFE_CONFIG allows for easy toggling and testing without affecting the entire system immediately.

The display of ungraded assignment progress will undoubtedly benefit both learners and instructors.

   - For Learners: Providing visibility into completed and pending ungraded assignments will empower learners to take control of their study schedules and feel a sense of achievement. This, in turn, will foster motivation and encourage continued engagement with course materials.

   - For Instructors: The ability to track progress on ungraded assignments will provide invaluable insights into learner engagement beyond graded assessments. This will allow instructors to fine-tune their teaching strategies and create content that resonates more effectively with their students.

**Recommendations**
I suggest considering the use of the terms "Practice Scores" and "Graded Scores," supplemented with tooltips for additional clarity.

   - Practice Scores (with a tooltip: "Scores from non-graded activities meant for practice and self-assessment.")
   - Graded Scores (with a tooltip: "Scores from activities that contribute to your final grade.")

**Questions**
How will we address these specific scenarios?

1. Scenario where ungraded assignments are closely related to or integrated with graded assessments.
2. Scenario where learners partially complete an assignment.

**Conclusion**
Overall, this is a valuable addition to the learning MFE, ensuring continuity and enhancing user experience by incorporating ungraded assignments in the progress view. I support moving forward with this PR and look forward to seeing it in action.

2024-06-10 09:13 UTC, navinkarkera commented
@asma-ahmedd Thanks for responding.

> Scenario where ungraded assignments are closely related to or integrated with graded assessments.

I believe that all problems under a graded subsection are considered as graded problems except for the problems with `weight` set to 0 in which case the progress page already shows something like `0/0`.
![image](https://github.com/openedx/frontend-app-learning/assets/10894099/94f06f47-3f67-468e-b125-dc9bb45a0d3a)

> Scenario where learners partially complete an assignment.

Not sure if I understand the question here. I think until a learner completes the problem, no score is awarded which translates to 0 in the progress page.

2024-06-10 11:14 UTC, ali-hugo commented
@asma-ahmedd Thanks for the detailed review!

> I suggest considering the use of the terms "Practice Scores" and "Graded Scores," supplemented with tooltips for additional clarity.

@navinkarkera 
1. How much additional work would it be to add tooltips?
2. I quite like "Practice Scores" and "Graded Scores". Do you think they work well?
3. Out of interest, if we were to change the terms (i.e. "practice scores" and "graded scores"), who would be responsible for updating the [docs](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-lilac.master/student_progress/course_grades.html)?

2024-06-10 11:29 UTC, Agrendalath commented
@ali-hugo,
> Out of interest, if we were to change the terms (i.e. "practice scores" and "graded scores"), who would be responsible for updating the [docs](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/open-release-lilac.master/student_progress/course_grades.html)?

[This is](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/student_progress/course_grades.html#detailed-grades) the up-to-date version of this document. We could update the linked section to add information about the option to display ungraded assignments.

cc: @navinkarkera

2024-06-10 12:57 UTC, ali-hugo commented
Thanks @Agrendalath 🙂

2024-06-10 14:09 UTC, navinkarkera commented
Updated to change the label and include tooltip as described by @asma-ahmedd as well as create a PR in edx-documentation repo to update docs: https://github.com/openedx/edx-documentation/pull/2268

2024-06-11 07:25 UTC, ali-hugo commented
@navinkarkera Thanks for incorporating those changes. This is good to go from a product point of view. 👍

2024-06-11 07:50 UTC, itsjeyd commented
@navinkarkera Now that product review is complete (🎉), should we put this PR up for engineering review or are you planning on making more changes to the code first?

2024-06-14 17:43 UTC, Agrendalath commented
@asma-ahmedd, we have some concerns regarding the tooltips in this use case.
1. The current implementation of the `Tooltip` and `OverlayTrigger` does not seem to be accessible:
   1. The tooltip cannot be opened with the keyboard (I managed to open it in the VoiceOver mode with Control+Option+Space, but it disappears after less than 50ms). To eliminate this problem, we could create a `fa-info-circle` element (with appropriate `aria` attributes) indicating a clickable element. However, this would heavily clutter the whole table, and there is also the second issue.
   2. When the tooltip is created, it appears directly inside the MFE's `body` tag. There is no easy way to navigate it from the "Practice/Problem Scores" text. As a side note, this also applies to the existing "Grade summary" info button.
2. We must show that the tooltip is underneath the regular text. This is especially important in the mobile experience, where learners must explicitly click on the text to see the tooltip. We could indicate that the text is clickable by styling it as a link, but it could also reduce the readability of the whole table.

We think that adding the legend below the "Detailed grades" section could be a cleaner solution. This would allow us to match the learners' experience regardless of the platform or accessibility tools they use.

cc: @navinkarkera, @ali-hugo, @itsjeyd

2024-06-18 08:09 UTC, ali-hugo commented
@Agrendalath Thanks for looking into the accessibility of the tooltips. I agree with you that we should avoid using them for now. Your suggestion of using a legend makes sense to me.

The only example of a legend I could find uses superscripts and footnotes:

<img width="326" alt="Screenshot 2024-06-18 at 09 55 43" src="https://github.com/openedx/frontend-app-learning/assets/88187719/871842e6-b91c-4646-91b8-f937576cb76c">

Did you have something similar in mind? My only concern is that the little "1's" and "2's" might clutter up the table (since the terms "practice scores" and "graded scores" are likely to appear a number of times).

2024-06-19 15:41 UTC, Agrendalath commented
@ali-hugo, right, the footnotes won't look good here. Could we put this legend somewhere above the table to make it easy for screen reader users to find?

2024-06-20 09:10 UTC, ali-hugo commented
@Agrendalath I think that will work nicely. I mocked something up just to see how it would look:

![Proposed legend placement](https://github.com/openedx/frontend-app-learning/assets/88187719/2700ae82-2057-4348-bb41-b18328999d76)

@asma-ahmedd Please confirm whether you are ok with this approach, so that we can wrap this up. 🙂

2024-06-20 09:31 UTC, asma-ahmedd commented
@ali-hugo The mockup looks good to me. I agree with this approach. Let's proceed and conclude this 👍

2024-06-20 09:35 UTC, ali-hugo commented
@asma-ahmedd Thanks for the quick response, and for your help reviewing this PR!

@Agrendalath @navinkarkera This has the "go ahead" from product. 🚀

2024-06-21 14:12 UTC, navinkarkera commented
@ali-hugo @Agrendalath Updated.

![image](https://github.com/openedx/frontend-app-learning/assets/10894099/e7cbea67-c90b-41f7-a143-a8ca8747c4d6)

2024-06-24 07:10 UTC, ali-hugo commented
@navinkarkera Looks great! Just one thing - I think we decided to change the term "Problem Scores" to "Graded Scores", didn't we? (see [this comment](https://github.com/openedx/frontend-app-learning/pull/1380#issuecomment-2157280661)).

2024-07-12 12:15 UTC, itsjeyd commented
@navinkarkera Friendly ping on [this](https://github.com/openedx/frontend-app-learning/pull/1380#issuecomment-2185771951) ⬆️ 🙂

2024-07-25 09:18 UTC, itsjeyd commented
Hey @navinkarkera, when do you think you could get back to @ali-hugo's comment above?

2024-07-25 10:07 UTC, navinkarkera commented
@itsjeyd @ali-hugo Sorry, the pings were redirected to my another email so missed it. I'll update the PR today.

2024-07-26 12:45 UTC, itsjeyd commented
Thanks @navinkarkera! Looks like this is back in draft state now. Let me know when it's ready so we can get the engineering review process started.

2024-07-29 03:48 UTC, ali-hugo commented
@navinkarkera Looks good! Thank you.

2024-08-08 07:01 UTC, itsjeyd commented
Hey @navinkarkera, any updates on when this PR will be ready to move out of draft state and get a technical review?

2024-08-08 12:46 UTC, navinkarkera commented
@itsjeyd @Agrendalath Is planning to deploy this for client's QA this week.

2024-08-08 17:05 UTC, Agrendalath approved these changes
@navinkarkera, @itsjeyd, we're good to move forward with this.

:+1:

* [x] I tested this: checked that the ungraded assignments are displayed on the Progress page, along with the explanation at the top
* [x] I read through the code
* [x] I checked for accessibility issues
* [x] Includes documentation: https://github.com/openedx/edx-documentation/pull/2268

2024-08-13 22:45 UTC, Agrendalath commented
@navinkarkera, @itsjeyd, who should we ask to review and merge this?

2024-09-06 09:20 UTC, Agrendalath commented
@navinkarkera, @itsjeyd, a quick reminder on the ping above ^

2024-09-07 08:19 UTC, itsjeyd commented
@Agrendalath Sorry for the late response, I was off when you [pinged me](https://github.com/openedx/frontend-app-learning/pull/1380#issuecomment-2287300824) and only came back to work earlier this week.

Maintainership for this repo was [transferred from 2U to OpenCraft](https://discuss.openedx.org/t/learning-mfe-looking-for-a-new-maintainer/13414/4) (@bradenmacdonald and @farhaanbukhsh), so the two of them should be able to merge the changes once @navinkarkera marks them as ready and the build turns green.

2024-09-10 06:27 UTC, navinkarkera commented
Rebased, ready to be merged.

2024-09-10 08:00 UTC, farhaanbukhsh commented
I can review this cc: @itsjeyd @Agrendalath  @bradenmacdonald

2024-10-03 21:18 UTC, farhaanbukhsh commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +  );
This can be moved in a separate place since this function is getting duplicated.

2024-10-03 21:24 UTC, farhaanbukhsh requested changes
Overall the approach looks good but can you look into this one comment

2024-10-03 21:24 UTC, farhaanbukhsh commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +  const showUngradedAssignments = (
This can be moved to a separate place since this function is getting duplicated.

2024-10-17 05:16 UTC, navinkarkera commented on src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
> +  const showUngradedAssignments = (
@farhaanbukhsh Done. https://github.com/openedx/frontend-app-learning/pull/1380/commits/1686988a2fd7155a66e45f2b5ea8d196d1528330

2024-10-24 08:21 UTC, itsjeyd commented
@farhaanbukhsh This is ready for another review pass :)

2024-10-26 02:25 UTC, farhaanbukhsh commented
> @farhaanbukhsh This is ready for another review pass :)

on it :)

2024-10-31 10:16 UTC, farhaanbukhsh approved these changes
👍 

Thanks @navinkarkera and @Agrendalath  for the persistence.


- ✅ I tested this on tutor devstack, tested with the flag on and off
- ✅  I read through the code
- ✅   I checked for accessibility issues
- ✅   Includes documentation

2024-10-31 10:18 UTC, merged