chore: README updated
openedx/frontend-app-learning pull request #1396
Opened 2024-05-25 12:42 UTC by CodeWithEmad

- code blocks added.
- heading issues fixed.
- small typos fixed.

2024-05-25 12:42 UTC, openedx-webhooks commented
Thanks for the pull request, @CodeWithEmad! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-05-31 07:50 UTC, itsjeyd commented
@CodeWithEmad Thank you for this contribution! We've got a green build so I'm marking it as ready for review now, but let me know if you had plans to work on it some more.

2024-05-31 07:52 UTC, itsjeyd commented
Hey @openedx/2u-aurora team, this PR is ready for review.

2024-05-31 08:26 UTC, CodeWithEmad commented
If @openedx/2u-aurora team maintains this repo, let me just update the `@edx/engage-squad` mentioned in the readme.

2024-06-06 07:50 UTC, itsjeyd commented
@CodeWithEmad Sounds good!

BTW, if a repo is maintained, it'll have the maintainer(s) listed as `owner` in its catalog-info.yaml file ([example](https://github.com/openedx/frontend-app-learning/blob/master/catalog-info.yaml#L16)). So if you're ever unsure about the maintenance status of a repo you can just check that file.

2024-06-06 08:29 UTC, CodeWithEmad commented
Got it.

2024-06-19 11:40 UTC, itsjeyd commented
Hi @openedx/2u-aurora team, could you have a look at this PR please?

2024-06-26 11:59 UTC, itsjeyd commented
Reached out to core contributors [via Slack](https://openedx.slack.com/archives/C015KC8CN76/p1719403130215399).

2024-06-26 12:39 UTC, sarina requested changes
Looks good, please address the point about catalog-info and we can get this merged.

2024-06-26 12:39 UTC, sarina commented on README.rst
> +Please tag **@openedx/2u-aurora** on any PRs or issues. Thanks.
Let's remove this line, or point at the https://github.com/openedx/frontend-app-learning/blob/master/catalog-info.yaml file. All repos are migrating to using `catalog-info` so let's not make it error prone by duplicating the info.

2024-06-26 12:39 UTC, sarina commented on README.rst
> -#####################
just FYI the overlines are not wrong, it's OK to leave them in. But OK that you've removed them.

2024-06-26 12:39 UTC, sarina commented on README.rst
> +  edx.org-specific to use for your site.
I like this sentence better without this change, but will not block merging on this feedback.

2024-06-28 11:18 UTC, CodeWithEmad commented on README.rst
> -#####################
Yes, I am aware of that. I am just trying to ensure all the documents have a consistent appearance.

2024-06-28 11:19 UTC, CodeWithEmad commented on README.rst
> +Please tag **@openedx/2u-aurora** on any PRs or issues. Thanks.
I'll remove it.

2024-06-28 11:22 UTC, CodeWithEmad commented on README.rst
> +  edx.org-specific to use for your site.
I have no objections to it. I'll revert the change.

2024-06-28 13:09 UTC, sarina approved these changes

2024-06-28 13:09 UTC, merged

2024-06-28 13:09 UTC, openedx-webhooks commented
@CodeWithEmad 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/1396&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2024-05-25+12:42&entry.1917517419=2024-06-28+13:09&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->

2024-07-12 11:56 UTC, itsjeyd commented on README.rst
> +Please tag **@openedx/2u-aurora** on any PRs or issues. Thanks.
@CodeWithEmad It's completely fine to ping repo maintainers for review if they don't respond to a PR within a week or two.

I think @sarina's comment was more about not putting information about who owns a repo into two places. (Because it's easy to forget updating it in both places when it changes, especially when there's a widely accepted default for where this information should go.)

If you wanted to update the README of this repo to mention that PR authors should ping repo maintainers for review, you could still do that. Just keep it neutral -- i.e., instead of explicitly mentioning the current maintainer(s) in the README, tell the reader to check https://github.com/openedx/frontend-app-learning/blob/master/catalog-info.yaml to find out who to ping 🙂

2024-07-12 11:58 UTC, sarina commented on README.rst
> +Please tag **@openedx/2u-aurora** on any PRs or issues. Thanks.
Exactly right, it's about duplicating information. I like @itsjeyd 's suggestion of pointing people to the `catalog-info.yaml` file.