Added a verified upgrade component
openedx/frontend-app-learning pull request #14
Opened 2020-02-28 16:52 UTC by davestgermain

2020-03-02 15:52 UTC, abutterworth requested changes

2020-03-02 15:52 UTC, abutterworth commented on src/courseware/course/CourseSock.jsx
> +              <li>Easily shareable certificate</li>
This needs to be i18n friendly. See:
- https://edx.github.io/frontend-platform/module-Internationalization.html
- which re-exports react-intl components documented here: https://github.com/formatjs/react-intl/blob/master/docs/Components.md#formattedmessage
- example: https://github.com/edx/frontend-app-payment/blob/master/src/payment/checkout/Checkout.jsx#L107 - https://github.com/edx/frontend-app-payment/blob/master/src/payment/checkout/Checkout.jsx#L8

2020-03-04 16:35 UTC, davidjoy commented on src/courseware/course/CourseSock.jsx
> +import React, { Component } from 'react';
Code organization nit - 

The course sock feels like a pretty self contained module, so we may want to formalize it's organization a bit:

```
/course
    /course-sock
        /index.js - exports the public API of the module, which is only the CourseSock component
        /CourseSock.jsx
        /messages.jsx - messages used by the course sock module
        /assets
            /learner-quote.png
            /learner-quote2.png
            /verified-cert.png
```

Then it gets imported as:

`import CourseSock from './course-sock';`

See the courseware/sequence/content-lock module for a pretty simple example.

2020-03-04 16:37 UTC, davidjoy commented on src/courseware/course/CourseSock.jsx
> +  handleClick() {
Fun fact -

You can avoid having to remember to `bind(this)` on handlers like this if they're declared as:

`handleClick = () => { ... }`

Because they're an arrow function, they don't need to be bound!  I've started doing that in class components just so I don't have to remember the `bind` line. :)

2020-03-04 16:41 UTC, davidjoy commented on src/courseware/course/CourseSock.jsx
> +      buttonClass: state.showUpsell ? 'btn-success' : 'btn-outline-success',
Given that `buttonClass` is 'derived state' directly from `showUpsell`, it'd be perfectly reasonable to pull it out of `state` and have a line at the top of `render` that reads:

```
render() {
  const buttonClass = state.showUpsell ? 'btn-success' : 'btn-outline-success'
  // rest of render(), using that const instead of `this.state.buttonClass`
}
```

Would simplify things a touch!

2020-03-04 16:44 UTC, davidjoy approved these changes
A few nits and mild suggestions that I'd probably want to clean up if I were looking at it later. :)

2020-03-04 17:39 UTC, abutterworth approved these changes

2020-03-04 18:06 UTC, merged