chore: make sidebar less intrusive for mobile
openedx/frontend-app-learning pull request #1423
Opened 2024-07-22 19:46 UTC by sundasnoreen12

[INF-1479](https://2u-internal.atlassian.net/browse/INF-1479)

**Description**

Mobile users should only need to close the sidebar widget once, and it should not reopen automatically when switching between units.

**Screenshot**
https://www.loom.com/share/46773322d572481abc3bd16926847ffd?sid=cb55e381-d895-425d-9301-4111036f314c

2024-07-23 09:34 UTC, awais-ansari requested changes

2024-07-23 09:34 UTC, awais-ansari commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +  let initialSidebar = shouldDisplayFullScreen && keyExists ? getLocalStorage(`sidebar.${courseId}`) : SIDEBARS.DISCUSSIONS_NOTIFICATIONS.ID;
Refactor
```
const sidebarKey = `sidebar.${courseId}`;
let initialSidebar = shouldDisplayFullScreen && sidebarKey in localStorage ? getLocalStorage(sidebarKey) : SIDEBARS.DISCUSSIONS_NOTIFICATIONS.ID;

2024-07-23 09:34 UTC, awais-ansari commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +      setLocalStorage(`sidebar.${courseId}`, sidebarId);
Refactor
setLocalStorage(sidebarKey, sidebarId);

2024-07-23 09:34 UTC, awais-ansari commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +      setLocalStorage(`sidebar.${courseId}`, sidebarId === currentSidebar ? null : sidebarId);
Refactor
setLocalStorage(sidebarKey, sidebarId === currentSidebar ? null : sidebarId);

2024-07-23 09:34 UTC, awais-ansari commented on src/courseware/course/new-sidebar/SidebarContextProvider.jsx
> +  }, [isDiscussionbarAvailable, isNotificationbarAvailable, currentSidebar]);
Please try to refactor this `toggleSidebar` function.

2024-07-24 09:14 UTC, awais-ansari approved these changes

2024-07-24 09:40 UTC, ayesha-waris approved these changes
PR LGTM

2024-07-24 09:59 UTC, merged