fix: fixed overflow issue of stacked bar on mobile
openedx/frontend-app-learning pull request #1425
Opened 2024-07-29 11:24 UTC by sundasnoreen12

[INF-1479](https://2u-internal.atlassian.net/browse/INF-1479)

**Description**
Fixed overflow and height issue of discussion iframe of new sidebar on mobile. 

**Screenshot**
**Before**
https://www.loom.com/share/27f6ec9719e041a982ab3f16630a47b1?sid=b2cc9b23-9dbd-4d21-acf3-f793e1f50b97

**After**
https://www.loom.com/share/8c0885c400844731946623b0b3fdadb4?sid=8ac3fcc1-a492-4343-ba44-a17624f570f5

2024-07-29 11:51 UTC, awais-ansari requested changes

2024-07-29 11:51 UTC, awais-ansari commented on src/courseware/course/new-sidebar/sidebars/discussions-notifications/discussions/DiscussionsWidget.jsx
> +        'min-height-700': isMobileView,
Mobile View for the Sidebar will be visible on small screens. Please check this code. [shouldDisplayFullScreen](https://github.com/openedx/frontend-app-learning/pull/1425/files#diff-35ae01d28fc00a1a04b87f91582059692902e9ac4094f49545b4762bddccfbd3L23)

2024-07-30 08:15 UTC, awais-ansari approved these changes

2024-07-30 08:52 UTC, ayesha-waris approved these changes

2024-07-30 08:53 UTC, merged