fix: corrects the navigation issue if the student does not pass the entrance exam
openedx/frontend-app-learning pull request #1429
Opened 2024-08-02 07:13 UTC by imasdekar

- adds checks while rendering the next button text for status of the entrance exam.

closes #1415

Signed-off by: Ishan Masdekar <imasdekar@disroot.org>

2024-08-02 07:13 UTC, openedx-webhooks commented
Thanks for the pull request, @imasdekar!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.


#### :radio_button: Update the status of your PR

Your PR is currently marked as a draft.  After completing the steps above, update its status by clicking "Ready for Review", or removing "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/2u-aurora`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2024-08-07 14:04 UTC, imasdekar commented
@mphilbrick211 Can you please get the checks run and get this reviewed?

2024-08-07 18:13 UTC, GlugovGrGlib commented
@imasdekar I believe we need to wait another week until @bradenmacdonald and @farhaanbukhsh take on maintainer responsibilities for this repo, after this it can be reviewed and scheduled for merge

2024-08-08 07:53 UTC, itsjeyd commented
Hi @imasdekar, thank you for this contribution!

2024-08-08 07:56 UTC, itsjeyd commented
OSPR management note: This PR includes [user-facing changes](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F). However, it fixes an existing bug (#1415) so there should be no need to send it through product review.

CC @jmakowski1123

2024-09-11 18:53 UTC, bradenmacdonald commented on src/course-home/progress-tab/certificate-status/CertificateStatus.jsx
> +  const entranceExamPassed = entranceExamData ? entranceExamData.entranceExamPassed : null;
Nit - you can write this more concisely as:
```suggestion
  const entranceExamPassed = entranceExamData?.entranceExamPassed ?? null;
```

2024-09-11 18:53 UTC, bradenmacdonald commented on src/courseware/course/course-exit/utils.js
> +  const exitActive = ((exitMode !== COURSE_EXIT_MODES.disabled) && (exitMode !== COURSE_EXIT_MODES.entranceExamFail));
Can you help me understand this? What exactly does `exitActive` mean and what are the various exit modes? Just want to make sure this logic is correct, but I'm not clear on what's even going on here.

I'd love if you could add a few JSDoc comments to this file as part of this PR to explain what an "exit mode" is and what each of the `COURSE_EXIT_MODES` mean. And why `exitMode` should be `false` when the exit mode is `entranceExamFail` ??

2024-09-13 06:26 UTC, imasdekar commented on src/courseware/course/course-exit/utils.js
> +  const exitActive = ((exitMode !== COURSE_EXIT_MODES.disabled) && (exitMode !== COURSE_EXIT_MODES.entranceExamFail));
exitActive is used to enable/disable the exit mode i.e. the next buttons. 
Available COURSE_EXIT_MODES: disabled, celebration, nonPassing, inProgress, entranceExamFail
So if the user has failed the entrance exam, access to further course sections should be disabled

2024-09-13 06:28 UTC, imasdekar commented on src/courseware/course/course-exit/utils.js
> +  const exitActive = ((exitMode !== COURSE_EXIT_MODES.disabled) && (exitMode !== COURSE_EXIT_MODES.entranceExamFail));
I've added some comments in the code as per your suggestion. Let me know if more explanation is needed in the comments and I will add accordingly.

2024-09-13 06:29 UTC, imasdekar commented on src/course-home/progress-tab/certificate-status/CertificateStatus.jsx
> +  const entranceExamPassed = entranceExamData ? entranceExamData.entranceExamPassed : null;
Yes, thanks for the suggestion. Have made the changes.

2024-09-13 19:14 UTC, bradenmacdonald approved these changes
Thanks for the fix. I tested it and confirmed the issue is fixed. Although there is still obviously a major bug on the backend - it should be refusing to provide the rest of the course to the user who hasn't passed the exam, regardless of what logic we have on the frontend.

2024-09-13 19:16 UTC, bradenmacdonald requested changes
@imasdekar Actually could you please add a test case for this too? That will fix the coverage problem. Sorry, I just noticed now there isn't a new test.

2024-09-16 06:26 UTC, imasdekar commented
@bradenmacdonald before implementing this fix on the frontend I dis check the backend and found that the entrance data is sent to the frontend and the respective data has a field which states that the user has failed the entrance exam. Hence I decided to utilise the same and implement a fix on the frontend.

2024-09-16 06:28 UTC, imasdekar commented
I will add a test case and update this PR.

2024-09-16 06:30 UTC, imasdekar commented
@bradenmacdonald If req. is also that further course data not be sent from the backend at all if the entrance exam status is failed then what exactly should be the response in such a case? I can work on this backend fix as well.

2024-09-16 16:45 UTC, bradenmacdonald commented
Great! Replied on #1415.

2024-09-23 09:32 UTC, imasdekar commented
@bradenmacdonald  I've added tests as required.

2024-09-23 16:41 UTC, bradenmacdonald commented
Thanks @imasdekar ! Unfortunately the test is not passing on CI - can you please take a quick look?

2024-09-23 16:59 UTC, imasdekar commented
@bradenmacdonald apologies, it should work now.

2024-09-23 18:41 UTC, bradenmacdonald approved these changes

2024-09-23 18:41 UTC, merged