feat: hide studio button for limited staff [BB-9082]
openedx/frontend-app-learning pull request #1436
Opened 2024-08-14 16:41 UTC by 0x29a

2024-08-14 16:41 UTC, openedx-webhooks commented
Thanks for the pull request, @0x29a!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/committers-frontend-app-learning`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-08-16 11:13 UTC, kaustavb12 commented on src/tab-page/LoadedTabPage.jsx
> +
@0x29a The access to course in Studio is currently gated by [this function](https://github.com/openedx/edx-platform/blob/ca46c20abb646b8b887e3c4d999f4e069f7eb871/common/djangoapps/student/auth.py#L138-L142) which checks if user has the correct access. I am wondering if we should use the same and pass a boolean directly from edx-platform instead of trying to make a decision about user access here.

This would make sure we have single source of truth for access to studio. _If this user/role has access to course in studio then they should be shown the button otherwise not._

2024-09-06 08:11 UTC, kaustavb12 approved these changes
LGTM :+1:

- [x] I tested this: Tested in local devstack
- [x] I read through the code

2024-09-07 09:15 UTC, itsjeyd commented
OSPR management note: User-facing change, so will likely need [product approval](https://github.com/openedx/platform-roadmap/issues/361#issuecomment-2335127876) before we can move forward with engineering review and merge.

CC @openedx/committers-frontend-app-learning

2024-10-11 09:29 UTC, itsjeyd commented
@0x29a It looks like the [conversation](https://github.com/openedx/platform-roadmap/issues/361#issuecomment-2335127876) about how to proceed with this PR and https://github.com/openedx/edx-platform/pull/35313 stalled, so I went ahead and [brought it up](https://openedx.slack.com/archives/C057J2D1WU9/p1728638602790569) in the `#wg-product-core` channel on the Open edX Slack. Could you please watch that thread and follow up as necessary?

CC @openedx/committers-frontend-app-learning @mphilbrick211

2024-10-24 08:44 UTC, itsjeyd commented
OSPR management note: Product review complete, see https://github.com/openedx/platform-roadmap/issues/361#issuecomment-2429495888.

2024-10-24 08:46 UTC, itsjeyd commented
@openedx/committers-frontend-app-learning This is ready for engineering review. Since it relies on https://github.com/openedx/edx-platform/pull/35313 it would be great if you could have a look at that PR as well.

2024-10-25 17:53 UTC, farhaanbukhsh commented
@0x29a  can you please rebase the PR? Thanks in advance.

2024-10-28 10:30 UTC, farhaanbukhsh commented
@itsjeyd  I will review this PR :)

2024-10-29 14:46 UTC, itsjeyd commented
Thanks @farhaanbukhsh!

2024-11-09 12:23 UTC, farhaanbukhsh requested changes
@0x29a is a small nitpick but once we fix this we are good to go.

2024-11-09 12:23 UTC, farhaanbukhsh commented on src/tab-page/LoadedTabPage.jsx
> +          studioButtonVisible={hasCourseAuthorAccess}
```suggestion
          isStudioButtonVisible={hasCourseAuthorAccess}
```

2024-11-28 12:08 UTC, itsjeyd commented
@farhaanbukhsh Looks like this is ready for final 👍 and merge :)

2024-11-28 18:45 UTC, farhaanbukhsh approved these changes
👍 

- ✅ I tested this on tutor devstack and all the flags are working properly
- ✅  I read through the code
- ❌  I checked for accessibility issues
- ❌  Includes documentation
- ❌  I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

2024-11-28 19:06 UTC, merged