Enable TypeScript support in this repo
openedx/frontend-app-learning pull request #1459
Opened 2024-09-12 18:34 UTC by bradenmacdonald

As part of taking over maintainership, I want to be able to use TypeScript to improve the quality of the code in this MFE.

This PR is split into three commits:
1. Turn on TypeScript, set up `tsconfig.json` and add types for i18n and the constants in `src/constants.ts`. Updates the CI to do type checking.
2. Update the entire `new-sidebars` folder to use TypeScript, as an example of converting an entire "thing" to TypeScript
3. Rename all `messages.js` to `messages.ts` since none of the "messages" files require any changes to work as TypeScript.

Private ref: [MNG-4362](https://tasks.opencraft.com/browse/MNG-4362)

2024-09-12 18:34 UTC, openedx-webhooks commented
Thanks for the pull request, @bradenmacdonald!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/committers-frontend-app-learning`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-09-12 18:42 UTC, bradenmacdonald commented
@farhaanbukhsh another PR for you - no rush :)

2024-09-19 16:35 UTC, farhaanbukhsh commented
@bradenmacdonald  this will take some time :)

2024-10-03 21:07 UTC, farhaanbukhsh requested changes
@bradenmacdonald  thanks for this PR I do have a doubt there are a bunch of JS files are we going to migrate them later?

2024-10-03 21:07 UTC, farhaanbukhsh commented on src/constants.ts
> +} as const satisfies Readonly<{ [k: string]: string }>;
```typescript
export const WIDGETS: Readonly<{ [k: string]: string }> = {
  DISCUSSIONS: 'DISCUSSIONS',
  NOTIFICATIONS: 'NOTIFICATIONS',
};

``` 

@bradenmacdonald  I just experimented with this and I found this to be more precise, what do you say?

2024-10-03 21:07 UTC, farhaanbukhsh commented on src/courseware/course/new-sidebar/sidebars/discussions-notifications/notifications/NotificationsWidget.jsx
> +    // eslint-disable-next-line @typescript-eslint/no-implied-eval
Are we running the linter for TS and TSX? I can't find the command being updated and changes in eslintrc.

2024-10-03 21:26 UTC, bradenmacdonald commented
@farhaanbukhsh Yeah, we can slowly convert the JS to TS. It's too complex to do it all at once. But once this PR is merged, we can convert things as we go, and all new stuff can use TS.

2024-10-03 21:29 UTC, bradenmacdonald commented on src/constants.ts
> +} as const satisfies Readonly<{ [k: string]: string }>;
That seems less precise to me? If you do that, the type actually just becomes this, which is basically "any object" - not very useful:

![Screenshot](https://github.com/user-attachments/assets/5113f193-7288-4eb6-b4c0-02219f6c9017)

Whereas using the `satisfies` operator, we get the exactly correct type as a constant:

![Screenshot](https://github.com/user-attachments/assets/fb098c8c-2124-4d6d-9a26-dc116064cf69)

2024-10-03 21:33 UTC, bradenmacdonald commented on src/courseware/course/new-sidebar/sidebars/discussions-notifications/notifications/NotificationsWidget.jsx
> +    // eslint-disable-next-line @typescript-eslint/no-implied-eval
Oops, you are right. Fixed with dc39854ff326f84e22b5327cdb1abe5736e5585b. Changing .eslintrc shouldn't be needed since it inherits from frontend-build which already configures eslint to support typescript.

2024-10-05 02:42 UTC, farhaanbukhsh commented on src/constants.ts
> +} as const satisfies Readonly<{ [k: string]: string }>;
@bradenmacdonald That makes more sense I was looking it from the point of view of just reading it, inferencing it will be more helpful for sure in the way you did it.

2024-10-05 15:01 UTC, bradenmacdonald commented
@farhaanbukhsh Is this good to go now?

2024-10-06 05:34 UTC, farhaanbukhsh approved these changes
👍 

- ✅ I tested this on devstack
- ✅  I read through the code
- ❌  I checked for accessibility issues
- ❌  Includes documentation
- ❌  I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

2024-10-07 17:23 UTC, merged