[BD-29] [TNL-7269] Add low priority tests
openedx/frontend-app-learning pull request #171
Opened 2020-08-08 19:32 UTC by Agrendalath

This adds tests from the low priority list. The codebase has changed since creating that list, so some points are no longer relevant.

## Testing instructions:
1. Run `npm i && npm test`.

## Reviewers
- [ ] @pcockwell 
- [ ] @davidjoy

2020-08-08 19:32 UTC, edx-webhook commented
Thanks for the pull request, @Agrendalath! I've created [BLENDED-538](https://openedx.atlassian.net/browse/BLENDED-538) to keep track of it in Jira.   More details are on the [BD-29](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1543995805/%5BBD-29%5D+Learning+Sequence+Experience+Improvements) project page.

When this pull request is ready, tag your edX technical lead.

<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->

2020-08-28 13:36 UTC, marcotuts commented
@Agrendalath  - is this ready for code review now? I'm going to presume so, but I thought I'd check here.

2020-09-01 19:17 UTC, Agrendalath commented
@marcotuts, sorry for the delay here. As this repository is changing dynamically, there were a few additional changes needed to get this ready for the review.

@pcockwell, some tests started to fail in `src/course-home/outline-tab/OutlineTab.test.jsx`, but other than that it's ready for the review.

2020-09-03 10:56 UTC, pcockwell requested changes
Mostly nitpicks and questions. Overall, the code looks good.

2020-09-03 10:56 UTC, pcockwell commented on src/course-home/outline-tab/OutlineTab.test.jsx
> +    });
Is this still needed? What is it used for?

2020-09-03 10:56 UTC, pcockwell commented on src/course-home/outline-tab/OutlineTab.test.jsx
> +    const outlineTabDataCannotEnroll = Factory.build('outlineTabData', {
This variable seems poorly named. Maybe something like `outlineTabDataHasVisited`?

2020-09-03 10:56 UTC, pcockwell commented on src/course-home/outline-tab/OutlineTab.test.jsx
> +        const courseHomeMetadataForEnrolledUser = Factory.build(
Again, this variable seems poorly named given the description of the test itself. Maybe `courseHomeMetadataForUnenrolledStaff`?

2020-09-03 10:56 UTC, pcockwell commented on src/course-home/outline-tab/OutlineTab.test.jsx
> +    });
Is this a WIP section, or is it not going to be included in this PR?

2020-09-03 10:56 UTC, pcockwell commented on src/generic/user-messages/AlertList.test.jsx
> +  //  `UserMessagesProvider` for testing would introduce a lot of boilerplate code that could get outdated quickly.
Do we have any idea when this will get addressed?

2020-09-03 10:56 UTC, pcockwell commented on src/courseware/course/bookmark/BookmarkButton.test.jsx
> +    const bookmarkDeleteUrlRegExp = new RegExp(`${bookmarkUrl}*,*`);
Why is this variable necessary when all it adds is `*,*` to the end of `bookmarkUrl` and turns it into `RegExp`. Can you provide an example of an expected URL for a delete call?

2020-09-03 10:56 UTC, pcockwell commented on src/courseware/course/bookmark/BookmarkButton.test.jsx
> +    });
> Is this still needed? What is it used for?

Ditto

2020-09-03 10:56 UTC, pcockwell commented on src/courseware/course/content-tools/calculator/Calculator.test.jsx
> +    });
> Is this still needed? What is it used for?

Ditto. Just marking it

2020-09-03 10:56 UTC, pcockwell commented on src/courseware/course/content-tools/calculator/Calculator.test.jsx
> +    });
> Is this still needed? What is it used for?

Ditto, just marking it

2020-09-03 10:56 UTC, pcockwell commented on src/courseware/course/content-tools/notes-visibility/NotesVisibility.test.jsx
> +    });
> Is this still needed? What is it used for?

Ditto, just marking it

2020-09-03 10:56 UTC, pcockwell commented on src/generic/tabs/Tabs.test.jsx
> +        // FIXME: this should use `toHaveStyle`, but it does not detect any style.
Any idea if this will get addressed in this PR?

2020-09-03 10:56 UTC, pcockwell commented on src/generic/user-messages/Alert.test.jsx
> +  };
Are these properties defined for the Alert Types already (in the Alert component) or are you redefining these for this test?

2020-09-03 10:56 UTC, pcockwell commented on src/instructor-toolbar/InstructorToolbar.test.jsx
> +    });
> Is this still needed? What is it used for?

Ditto, just marking it

2020-09-03 10:56 UTC, pcockwell commented on src/tab-page/TabPage.test.jsx
> +    });
> Is this still needed? What is it used for?

Ditto, just marking it

2020-09-03 12:07 UTC, Agrendalath commented on src/course-home/outline-tab/OutlineTab.test.jsx
> +    });
It's for logging unhandled requests, so we can easily catch them while running tests. I'll extract this to a helper function to reduce code duplication.

2020-09-03 12:11 UTC, Agrendalath commented on src/generic/tabs/Tabs.test.jsx
> +        // FIXME: this should use `toHaveStyle`, but it does not detect any style.
This might be a bug in `jest-dom` or some outdated dependency. I didn't dig into this, because it's basically a syntactic sugar in this case.

2020-09-03 12:13 UTC, Agrendalath commented on src/course-home/outline-tab/OutlineTab.test.jsx
> +    });
These were not in the scope, so I just marked them as `TODO`.

2020-09-03 12:14 UTC, Agrendalath commented on src/generic/user-messages/AlertList.test.jsx
> +  //  `UserMessagesProvider` for testing would introduce a lot of boilerplate code that could get outdated quickly.
Nah, we don't have any roadmap for this.

2020-09-03 12:27 UTC, Agrendalath commented on src/courseware/course/bookmark/BookmarkButton.test.jsx
> +    const bookmarkDeleteUrlRegExp = new RegExp(`${bookmarkUrl}*,*`);
I found `axiosMock.onDelete(new RegExp(``${bookmarkUrl}*,*``)).reply(200, { });` less readable, so split it into two lines.

This API view is defined [here](https://github.com/edx/edx-platform/blob/cca33732ba74fd926bda558693ad6247327adb98/openedx/core/djangoapps/bookmarks/views.py#L261).
Example request: `http://localhost:18000/api/bookmarks/v1/bookmarks/Mock User,block-v1:edX+DemoX+Demo_Course_1+type@vertical+block@bcdabcdabcdabcdabcdabcdabcdabcd2/`

2020-09-03 12:45 UTC, Agrendalath commented on src/generic/user-messages/Alert.test.jsx
> +  };
These are being returned by [these internal functions](https://github.com/edx/frontend-app-learning/blob/f715fd5ed6cdb051a39f540ceff072f2cc88230c/src/generic/user-messages/Alert.jsx#L13-L40), so we're redefining them for this test. We could try to use something like [rewire](https://github.com/speedskater/babel-plugin-rewire) to access them, but then this test would not have too much sense.

2020-09-07 11:55 UTC, pcockwell approved these changes

2020-09-07 12:06 UTC, Agrendalath commented
@davidjoy, this is ready for your review.

2020-09-18 13:27 UTC, davidjoy commented
FYI - there were some failed tests when I rebased this on master, which I've taken the liberty of fixing in this PR: https://github.com/edx/frontend-app-learning/pull/214

Going to merge that one and close this.  Thanks @Agrendalath!

2020-09-18 13:27 UTC, closed without merging