AA-125: Course Goals in Course Home Outline Tab
openedx/frontend-app-learning pull request #190
Opened 2020-08-20 13:29 UTC by ciduarte

2020-08-20 15:52 UTC, Ahernkb approved these changes
Looks great!

2020-08-21 14:39 UTC, xnick421 requested changes

2020-08-21 14:39 UTC, xnick421 commented on src/course-home/outline-tab/widgets/UpdateGoalSelector.jsx
> +  function selectGoalHandler(e) {
i know `e` is like universal known to be short hand for `event`, but maybe being verbose here and writing out `event` is clearer idk

2020-08-21 14:39 UTC, xnick421 commented on src/course-home/outline-tab/OutlineTab.jsx
> +    courseGoalToastHeader,
not sure if we need to leverage redux for this state.  i think this state can just live in this component only.

2020-08-21 14:39 UTC, xnick421 commented on src/course-home/outline-tab/widgets/CourseGoalCard.jsx
> +  function selectGoalHandler(e) {
i know `e` is universally known to be short hand for `event`, but maybe being verbose here wouldnt hurt.  up to you

2020-08-21 14:39 UTC, xnick421 commented on src/course-home/outline-tab/widgets/CourseGoalCard.jsx
> +              onClick={(e) => { selectGoalHandler(e); }}
same here in regards to `event`

2020-08-21 14:39 UTC, xnick421 commented on src/course-home/outline-tab/widgets/CourseGoalCard.jsx
> +                  onClick={(e) => { selectGoalHandler(e); }}
same here in regards to `event`

2020-08-21 14:39 UTC, xnick421 commented on src/course-home/outline-tab/widgets/UpdateGoalSelector.jsx
> +  function selectGoalHandler(e) {
same here in regards to `event`

2020-08-21 14:39 UTC, xnick421 commented on src/course-home/outline-tab/widgets/UpdateGoalSelector.jsx
> +                        onChange={(e) => { selectGoalHandler(e); }}
same here in regards to `event`

2020-08-21 14:39 UTC, xnick421 commented on src/toast/LearningToast.scss
> +#learning-toast {
how come we use id and not class?  id's shouldnt be rendered in the dom twice.  what would happen if we wanted to display two toasts at the same time?

2020-08-21 14:58 UTC, ciduarte commented on src/toast/LearningToast.scss
> +#learning-toast {
Per the design spec we shouldn't be displaying two toasts at once. But that's a good thought, maybe this would fare better as a class..

This will all go away though once we apply styling to the Toast Paragon component!

2020-08-21 18:02 UTC, xnick421 approved these changes

2020-08-27 17:30 UTC, ciduarte commented on src/course-home/data/__factories__/outlineTabData.factory.js
> +  }))
I left these fields empty because I'm not sure how we test different scenarios (verified vs audit, enrolled vs unenrolled)

2020-08-27 18:41 UTC, mikix reviewed
Screenshots look pretty

2020-08-27 18:41 UTC, mikix commented on src/toast/LearningToast.jsx
> +      {bodyLink && bodyText && (
This means that every toast has to have a link. Can we make that optional?

2020-08-27 18:41 UTC, mikix commented on src/course-home/data/slice.js
> +    resetDatesToastBodyLink: null,
We should also rename this stuff to just `toastBody*` and drop the `resetDates` prefix.

2020-08-27 18:41 UTC, mikix commented on src/course-home/outline-tab/messages.js
> +    defaultMessage: 'Welcome to',
This might be worth adding a `description` for the translators' benefit. Like "this goes before a course name" or something. So they know the context is a course, not like a town.

Maybe same for the couple messages above too -- Soccer goal or life goal? Not sure about what? Not every message string needs a translator description. But sometimes context is not obvious.

2020-08-27 18:41 UTC, mikix commented on src/tab-page/TabPage.jsx
> +          show={!!(resetDatesToastBodyLink && resetDatesToastBodyText && resetDatesToastHeader)}
Could this just be `!!resetDatesToastHeader`? The component has the link and text being optional.

2020-08-27 18:41 UTC, mikix commented on src/course-home/data/api.js
> +  const url = new URL(`${getConfig().LMS_BASE_URL}/api/course_home/v1/save_course_goal`);
This probably needs to change if you're switching endpoints on backend, but you know that already.

2020-08-27 18:41 UTC, mikix commented on src/course-home/data/redux.test.js
> +  describe('Test saveCourseGoal', () => {
Nice.

2020-08-27 18:41 UTC, mikix commented on src/course-home/outline-tab/widgets/CourseGoalCard.jsx
> +              variant="sm btn-link btn-block p-0"
This looks at first glance like a misuse of `variant`? Isn't it supposed to be like `link` or something and then the rest of these are `className` content?

2020-08-27 18:41 UTC, mikix commented on src/course-home/outline-tab/OutlineTab.jsx
> +      <LearningToast
This is separate from the reset deadlines toast? Ah, OK. That's easier than having just one at the TabPage level? I'd still like to rename that one to be generic though, since it's actually a generic CallToAction toast, not just a reset deadlines toast.

2020-08-27 18:41 UTC, mikix commented on src/course-home/outline-tab/widgets/UpdateGoalSelector.jsx
> +  function selectGoalHandler(event) {
Ugh. This is not on you and you shouldn't change anything based on this comment. But I much prefer class components. I don't like React's push for function components. Like, you're using a hook here when we could just have class state (which feels more natural to this backend developer). And functions in functions... is fine I guess. But come on. Dang kids on my lawn.

2020-08-27 18:53 UTC, ciduarte commented on src/course-home/outline-tab/widgets/CourseGoalCard.jsx
> +              variant="sm btn-link btn-block p-0"
Yeah the class names in variant are very strange. Some of them need the `btn-` prefix and some of them don't... I went through and removed all the `btn-` prefixes and learned this the hard way

2020-08-27 20:20 UTC, ciduarte commented on src/toast/LearningToast.jsx
> +      {bodyLink && bodyText && (
I guess the naming is misleading here, `bodyText` should only exist if there is a `bodyLink` because it'll go into a button. The actual success message is used in the header. ie. The entire `<Toast.Body />` is optional.

Do you think this would do better as `link` and `linkText`?

(Also, whatever choice we make here will most likely be changed by the Toast Paragon component that I'm creating)

2020-08-27 20:33 UTC, ciduarte commented on src/course-home/outline-tab/widgets/CourseGoalCard.jsx
> +              variant="sm btn-link btn-block p-0"
They worked! Probably just needed your blessing

2020-08-27 20:42 UTC, mikix commented on src/toast/LearningToast.jsx
> +      {bodyLink && bodyText && (
Ah got it. :+1:

2020-08-28 19:34 UTC, mikix approved these changes

2020-08-28 19:34 UTC, mikix commented on src/course-home/outline-tab/widgets/CourseGoalCard.jsx
> +            <Card.Title className="h6 m-0">{intl.formatMessage(messages.goalWelcome)}&nbsp;{title}</Card.Title>
This is fine, who cares. But why do you care so much about not breaking in between `to` and the first word of the course title?

2020-08-28 19:53 UTC, ciduarte commented on src/course-home/outline-tab/widgets/CourseGoalCard.jsx
> +            <Card.Title className="h6 m-0">{intl.formatMessage(messages.goalWelcome)}&nbsp;{title}</Card.Title>
Ooh I have a habit of sprinkling `&nbsp;` wherever I go. This was me thinking if I put a space between `{} {}` that it wouldn't be preserved in the UI, but that's not true...

2020-08-31 13:58 UTC, merged