AA-131: Landing page for anonymous or un-enrolled users
openedx/frontend-app-learning pull request #281
Opened 2020-11-20 20:53 UTC by ciduarte

2020-11-30 22:09 UTC, ciduarte commented on src/alerts/logistration-alert/LogistrationAlert.jsx
> +      style={{ textDecoration: 'underline' }}
MT has made a point about condensing these underlined Hyperlinks into a component because we use them everywhere. Some future Paragon release (if this isn't already out as I'm typing this) _should_ have an inline link class name that we can replace all of the redundant styling with.

2020-11-30 22:10 UTC, ciduarte commented on src/alerts/private-course-alert/PrivateCourseAlert.jsx
> +  // This is complicated by the fact that we don't have a REGISTER_URL env variable available.
Stole this from the existing LogistrationAlert... should I create a REGISTER_URL env variable?

2020-11-30 22:13 UTC, ciduarte commented on src/course-home/outline-tab/OutlineTab.jsx
> -    isEnrolled,
These were left here from early days, we weren't using them 👋

2020-11-30 22:14 UTC, ciduarte commented on src/course-home/outline-tab/OutlineTab.jsx
> -
Moved these into `<LoadedTabPage />` to be above the tabs as in LMS

2020-11-30 22:18 UTC, ciduarte commented on src/alerts/enrollment-alert/hooks.js
> +  const enrollClickHandler = useCallback((courseId) => () => {
`courseId` was originally out of scope, which is why it was broken in our bug bash

2020-12-01 22:04 UTC, ciduarte commented on src/generic/messages.js
> +  registerLowercase: {
Not sure if there's a better way to handle/name these...

2020-12-01 22:06 UTC, ciduarte commented on src/alerts/logistration-alert/messages.js
> -});
Moved these to `generic/messages.js`

2020-12-07 18:58 UTC, ciduarte commented on src/course-home/data/api.js
> +      slug: tab.tabId === 'courseware' ? 'outline' : tab.tabId,
The "Course" tab wasn't active while in course home because our course metadata calls it "courseware"

2020-12-08 14:27 UTC, mikix approved these changes
Nice! As mentioned in slack, it would also be good to confirm that `public` and public_outline` visibility levels work like they should.

(public_outline -- just outline, but they don't have links)
(public -- outline with links and handouts is also visible)

2020-12-08 14:27 UTC, mikix commented on src/alerts/enrollment-alert/EnrollmentAlert.jsx
> +      {intl.formatMessage(messages.enroll)}.
That should probably go inside the string to be translated. I believe fixed-width languages like Chinese use fixed-width versions of a lot of punctuation.

．vs .

2020-12-08 14:27 UTC, mikix commented on src/alerts/enrollment-alert/hooks.js
> +  const { authenticatedUser } = useContext(AppContext);
Is this a different thing than `import { getAuthenticatedUser } from '@edx/frontend-platform/auth';`?

I see both in the codebase.

2020-12-08 14:27 UTC, mikix commented on src/alerts/enrollment-alert/hooks.js
> +  const enrollClickHandler = useCallback((courseId) => () => {
Oof my mistake.

2020-12-08 14:27 UTC, mikix commented on src/alerts/private-course-alert/PrivateCourseAlert.jsx
> +  // This is complicated by the fact that we don't have a REGISTER_URL env variable available.
I think the comment in `LogistrationAlert` was talking about adding a `getRegisterRedirectUrl` to frontend-platform/auth, like they have a `getLoginRedirectUrl` -- but that they might want a REGISTER_URL first, to base that function off of? Adding API to our auth library doesn't sound like a quick fix, if I'm reading that comment right.

2020-12-08 14:27 UTC, mikix commented on src/course-header/Header.jsx
> +        {authenticatedUser && (
It might be cleaner / easier-to-read-this-component, if these two dropdowns were broken into their own components like `AuthenticatedUserDropdown` and `AnonymousUserDropdown` or something like that. But just an optional nit.

2020-12-08 14:27 UTC, mikix commented on src/index.jsx
> +  requireAuthenticatedUser: false,
Probably should drop the comment. And you can also drop the setting at all, since it defaults to `false`.

2020-12-08 16:12 UTC, ciduarte commented on src/course-header/Header.jsx
> +        {authenticatedUser && (
Yeah that's a good idea

2020-12-08 16:48 UTC, ciduarte commented on src/alerts/enrollment-alert/hooks.js
> +  const { authenticatedUser } = useContext(AppContext);
That's a good question... Both calls seem to return identical objects

Both AppContext and getAuthenticatedUser are coming from edx/frontend-platform, so I don't know if one has an advantage over the other in terms of efficiency or source of truth-ness.. Might be why we use them interchangeably 🤔

2020-12-08 16:59 UTC, ciduarte commented on src/alerts/private-course-alert/PrivateCourseAlert.jsx
> +  // This is complicated by the fact that we don't have a REGISTER_URL env variable available.
Ooh I see that, you're right. I skipped past the word "function" and went straight to "we should just add the env variable then"

I will not be doing that

2020-12-10 21:38 UTC, davidjoy requested changes
Er, submitting so these comments will show up.  Still reviewing. ;)

2020-12-10 21:38 UTC, davidjoy commented on src/alerts/enrollment-alert/EnrollmentAlert.jsx
> +    <Button disabled={loading} variant="link" className="p-0 border-0 align-top" style={{ textDecoration: 'underline' }} onClick={enrollClickHandler(courseId)}>
I think there's a bug here - `enrollClickHandler(courseId)` will call the handler and return `null`, setting the `onClick` handler to `null` but evaluating the `enrollClickHandler` on every re-render.

To make this work as written, you'd need to put a closure around this so that there's a function for `onClick` to evaluate when it's triggered:

```
onClick={() => enrollClickHandler(courseId)}
```

The above is the fix.  Everything below this is about the "right" way to do it:

Note that adding closures like that is generally a bad idea if they're being passed to a child component (like `Button`), as it means every re-render of `EnrollmentAlert` will force a re-render of the `Button`, since you're passing in a new function definition on every re-render.  It's not a big deal here since it won't happen that often, but this is the problem that `useCallback` fixes.

To fix it, you'd have to declare your helpful little closure as its own useCallback hook:

```
const enrollCourseClickHandler = useCallback(
  () => enrollClickHandler(courseId), 
  [enrollClickHandler, courseId]
);

// ... later...

onClick={enrollCourseClickHandler}
```

_Then_ you won't be re-rendering the Button needlessly. :)   

(Functional components are a pain in the butt, IMHO)

2020-12-10 21:38 UTC, davidjoy commented on src/alerts/enrollment-alert/hooks.js
> +  const { authenticatedUser } = useContext(AppContext);
In this case, the `AppContext` is better because it means that if `authenticatedUser` changes, the function will be re-rendered.  `getAuthenticatedUser` is better outside the react lifecycle.

2020-12-10 21:42 UTC, davidjoy commented on src/alerts/enrollment-alert/hooks.js
> +  }, [courseIdMemo]);
Curious about why this `courseIdMemo` is necessary.  This whole alerting on data-state situation is so complicated. (criticism of myself)

2020-12-10 21:44 UTC, davidjoy commented on src/alerts/private-course-alert/PrivateCourseAlert.jsx
> +      {anonymousUser && (
I'm assuming codecov is saying there's no test for this clause...

2020-12-10 21:59 UTC, davidjoy commented on src/course-header/AnonymousUserDropdown.jsx
> +function AnonymousUserDropdown({ intl }) {
`Dropdown` seems like a misnomer for this thing... Is it maybe just a `Menu`?  It's just two buttons side-by-side, right?

2020-12-10 22:04 UTC, davidjoy commented on src/course-home/data/api.js
> +      slug: tab.tabId === 'courseware' ? 'outline' : tab.tabId,
Should we normalize this at the API layer?  The risk is that we end up introducing the same bug because someone used the `tabId` elsewhere and didn't see this.  The "normalize" functions in the api.js files exist as an "anti-corruption layer" that normalizes data at the "edge" of the app and ensures that we can use it with confidence and with a consistent taxonomy within the bulk of the app.  Worth considering, perhaps!

2020-12-10 22:05 UTC, davidjoy commented on src/course-home/data/api.js
> +      slug: tab.tabId === 'courseware' ? 'outline' : tab.tabId,
I wrote something here about normalizing this in api.js and didn't realize I was staring at api.js 😀

2020-12-10 22:05 UTC, davidjoy commented on src/course-home/data/api.js
> +      slug: tab.tabId === 'courseware' ? 'outline' : tab.tabId,
Maybe worth a comment here to describe why this is necessary, for posterity.

2020-12-10 22:06 UTC, davidjoy commented on src/course-home/outline-tab/OutlineTab.jsx
> -    isEnrolled,
Thank goodness.  RIP.  

Turns out I was wrong and you all _didn't_ need all that, huh?  Hah!

2020-12-10 22:10 UTC, davidjoy approved these changes
So are there any pages in the learning MFE that still require authentication and should automatically redirect to login if an anonymous user tries to access them?

A few comments, but in general looks great.

2020-12-14 17:37 UTC, ciduarte commented on src/alerts/enrollment-alert/EnrollmentAlert.jsx
> +    <Button disabled={loading} variant="link" className="p-0 border-0 align-top" style={{ textDecoration: 'underline' }} onClick={enrollClickHandler(courseId)}>
Thanks for this explanation! This actually worked as intended because I used currying in the enrollClickHandler, which was only setting `courseId` and returning the rest of the callback function.

```
const enrollClickHandler = useCallback((courseId) => () => {
    return "something";
}

enrollClickHandler(courseId);
>> () => { return "something" }

enrollClickHandler(courseId)();
>> "something"
```

_But_, I did this because we found that the enrollClickHandler wasn't working in a bug bash, and through local testing it seemed like `courseId` was out of scope (which led to this currying and `courseIdMemo` madness)... Now that I'm sanity checking, it seems like this might have been working in the first place? Aliens??? So my changes here and to enrollClickHandler are seemingly unnecessary... _sigh_

2020-12-14 17:39 UTC, ciduarte commented on src/alerts/enrollment-alert/hooks.js
> +  }, [courseIdMemo]);
Revisiting this, I think courseIdMemo is an unnecessary change. Longer explanation in a previous comment 🙂

2020-12-14 19:02 UTC, ciduarte commented on src/course-header/AnonymousUserDropdown.jsx
> +function AnonymousUserDropdown({ intl }) {
Ooh yeah good catch!

2020-12-15 14:51 UTC, mikix approved these changes

2020-12-16 20:50 UTC, merged