static expiration box
openedx/frontend-app-learning pull request #377
Opened 2021-03-05 15:42 UTC by emma-green

2021-04-13 18:39 UTC, julianajlk commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +    <ul className="fa-ul upgradeCard-ul pt-0">
I would name my class as `upgrade-card-ul`, React doesn't have a restriction that I know of (dashed, camel-case, etc) but would be good for consistency with the other classNames already in this file

2021-04-13 18:44 UTC, julianajlk commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +function AccessExpirationDateBanner({ accessExpirationDate, timezoneFormatArgs }) {
What's the difference between a "card" and a "banner"? I think of them as the same, so to me when I read AccessExpirationDateBanner I think it's a separate banner/card than the UpgradeCard, but in this case it's a piece of it?

2021-04-13 18:52 UTC, julianajlk commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +function AccessExpirationDateBanner({ accessExpirationDate, timezoneFormatArgs }) {
Also wondering if it would make sense to pull out some of this stuff to a separate file. It's hard to follow through all of the different functions, but if that would make it complicated to access the data we need here, nevermind

2021-04-14 16:36 UTC, jhan217 reviewed
Couple of general comments about potentially using Paragon variables/components

2021-04-14 16:36 UTC, jhan217 commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +import { faCheck } from '@fortawesome/free-solid-svg-icons';
Could you use the `check` icon from https://paragon-edx.netlify.app/foundations/icons?

2021-04-14 16:36 UTC, jhan217 commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +              <a className="inline-link-underline font-weight-bold" rel="noopener noreferrer" target="_blank" href={`${getConfig().MARKETING_SITE_BASE_URL}/verified-certificate`}>verified certificate
Could you use a [Hyperlink](https://paragon-edx.netlify.app/components/hyperlink/) component here?

2021-04-14 16:36 UTC, jhan217 commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  background-color: #FCF1F4;
`$danger-100` from https://paragon-edx.netlify.app/foundations/colors?

2021-04-14 16:36 UTC, jhan217 commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  background-color: #FFFAED;
Should this be `$warning-100`?

2021-04-14 16:36 UTC, jhan217 commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  padding-left: 1.25rem;
Would it be possible to use any of the [spacing utility classes](https://paragon-edx.netlify.app/foundations/spacing) instead of hardcoding all the values?

2021-04-14 16:36 UTC, jhan217 commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  color: #00262B;
`$primary-500`?

2021-04-14 19:23 UTC, emma-green commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  padding-left: 1.25rem;
Good call out, but I don't think so, because I am not using full rems.

2021-04-14 20:58 UTC, inventhouse requested changes

2021-04-14 20:58 UTC, inventhouse commented on src/course-home/data/api.js
> +    timeOffsetMillis: 0,
I don't see the code where this is actually computed from the `Date` headers (see these two diffs: [src/courseware/data/api.js](https://github.com/edx/frontend-app-learning/pull/385/files#diff-9a08a1a98535680aabde6f7b44130d363b29ea26469f026235f1f0a19e31a02f), [src/course-home/data/api.js](https://github.com/edx/frontend-app-learning/pull/385/files#diff-4d3a6d853ff9fd1354a56024f06c6718c856c281e295de92c5b09ac1e86774bf))

2021-04-14 21:04 UTC, inventhouse commented on src/course-home/data/api.js
> +    timeOffsetMillis: 0,
It would be good to include in the QA as well, that the countdown is correct no matter what your local computer time is set to.

2021-04-14 21:27 UTC, emma-green commented on src/course-home/data/api.js
> +    timeOffsetMillis: 0,
how about I write a test for it?

2021-04-14 21:28 UTC, emma-green commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +import { faCheck } from '@fortawesome/free-solid-svg-icons';
nope. It needs to be fontawesome in order to use it in a list

2021-04-14 21:29 UTC, emma-green commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +              <a className="inline-link-underline font-weight-bold" rel="noopener noreferrer" target="_blank" href={`${getConfig().MARKETING_SITE_BASE_URL}/verified-certificate`}>verified certificate
What would be the advantage of that?

2021-04-15 14:32 UTC, jhan217 commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +              <a className="inline-link-underline font-weight-bold" rel="noopener noreferrer" target="_blank" href={`${getConfig().MARKETING_SITE_BASE_URL}/verified-certificate`}>verified certificate
If the behavior/attributes of Hyperlinks changed, those changes would automatically apply to this link (if it were a Hyperlink component) as well. Not a big deal, as it looks like both are used in this repo.

2021-04-23 18:49 UTC, emma-green commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +function AccessExpirationDateBanner({ accessExpirationDate, timezoneFormatArgs }) {
There's a banner inside the card that counts down to expiration.

2021-04-29 19:42 UTC, emma-green commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  background-color: #FCF1F4;
yes! Good catch! Thank you!!!

2021-04-29 19:50 UTC, emma-green commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  background-color: #FFFAED;
Hmmm....That's not the same color as requested. I'll message Eugene -- maybe FFFAED was an error

2021-04-29 19:51 UTC, emma-green commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  color: #00262B;
yep! Thanks!

2021-04-30 21:11 UTC, emma-green commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +  background-color: #FFFAED;
She said to do $warning-100. Thanks for the callout!

2021-04-30 21:12 UTC, emma-green commented on src/course-home/data/api.js
> +    timeOffsetMillis: 0,
I did a first pass. Please let me know your thoughts :)

2021-05-05 19:36 UTC, inventhouse approved these changes

2021-05-06 13:09 UTC, mikix reviewed
Some minor comments, nothing crazy / blocking

2021-05-06 13:09 UTC, mikix commented on src/course-home/outline-tab/widgets/UpgradeCard.scss
> +.upgrade-card {
This file has a lot of custom css (which also means using a lot of `rem` instead of the bootstrap spacing system).

We prefer to do this sort of thing as bootstrap utility classnames like `m-2` or similar. Keeps sizes the same and reduces all the little bits of css lying around.

Even the stuff you can't do as bootstrap class (like `text-decoration`) we will often do inline to the jsx with a `style={{ textDecoration: 'underline' }}` bit, to keep the styling close to the component.

2021-05-06 13:09 UTC, mikix commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +import { faCheck } from '@fortawesome/free-solid-svg-icons';
Is that a bug with our paragon implementation? Seems like something we should put on a backlog or try to solve. We are trying to get away from direct uses of FA.

2021-05-06 13:09 UTC, mikix commented on src/course-home/outline-tab/OutlineTab.jsx
> -                  }
Dropping this removes the need for the `ref` on `<CourseSock>`, so you can drop that bit and variable it saved the ref to.

2021-05-06 13:09 UTC, mikix commented on src/course-home/data/__snapshots__/redux.test.js.snap
> +        "timeOffsetMillis": 0,
I don't see this being set in the upgrade card tests, and it's zero here. Is it worth a test where this is set and we see the change in the UI? (Or maybe there is one and I missed it)

2021-05-06 16:32 UTC, merged