Add Sidebar and SidebarNotificationButton components
openedx/frontend-app-learning pull request #390
Opened 2021-03-15 20:50 UTC by julianajlk

[REV-2125](https://openedx.atlassian.net/browse/REV-2125).

For Value Prop implementation, we will implement a sidebar that is triggered on click of a button with upgrade messaging and CTA.

2021-04-13 16:47 UTC, wittjeff requested changes

2021-04-13 16:47 UTC, wittjeff commented on src/courseware/course/Sidebar.jsx
> +    <section className="sidebar-container ml-0 ml-lg-4">
Could you please add **aria-label="sidebar notifications"** here?

2021-04-13 16:47 UTC, wittjeff commented on src/courseware/course/messages.js
> +    defaultMessage: 'Sidebar notification button',
Could you please make this a verb or verb phrase like "Show sidebar notifications"?

2021-04-13 16:47 UTC, wittjeff commented on src/courseware/course/messages.js
> +    defaultMessage: 'Close',
"Close sidebar notifications"?

2021-04-13 16:47 UTC, wittjeff commented on src/courseware/course/Sidebar.scss
> +        border: none;
If you use **border: transparent** instead of **border: none**, the border will show up as a white box on Windows High Contrast Mode. Sometimes this is useful. I'm not sure if it would help here.  It would also change your box size calculation for the width of the borders.

2021-04-13 17:06 UTC, julianajlk commented on src/courseware/course/Sidebar.scss
> +        border: none;
@wittjeff Would it be useful to have the "transparent" border if it's on a full width screen (the sidebar takes up the entire screen)?

2021-04-14 14:09 UTC, dianekaplan commented on src/courseware/course/Sidebar.jsx
> +        <p>You have no new notifications at this time.</p>
Will this line be translatable (via transifex) that way? Or should it have an entry in messages or use FormatMessage?

2021-04-14 14:41 UTC, julianajlk commented on src/courseware/course/Sidebar.jsx
> +        <p>You have no new notifications at this time.</p>
Good catch! Formatted message will be added in the next commit

2021-04-14 16:23 UTC, jhan217 commented on src/courseware/course/Sidebar.jsx
> +  const shouldDisplayFullScreen = useWindowSize().width < 992;
Is there a reusable variable that can be used here (and other places where the sizes are hardcoded) so you don't have to hardcode the pixel size? Something like `media-breakpoint-down(xs)` in edx-platform?

2021-04-14 16:23 UTC, jhan217 commented on src/courseware/course/Sidebar.scss
> +    font-weight: 500;
Could you use the `font-weight-bold` class from https://paragon-edx.netlify.app/foundations/typography/?

2021-04-14 19:48 UTC, julianajlk commented on src/courseware/course/Sidebar.scss
> +    font-weight: 500;
Because I have a separate SCSS file, I'm generally choosing not to add utility classes inline but add all CSS to the file to keep it contained. Except for responsive padding/margin, which are simpler to do than adding media queries.

2021-04-14 19:51 UTC, julianajlk commented on src/courseware/course/Sidebar.jsx
> +  const shouldDisplayFullScreen = useWindowSize().width < 992;
There is a way to add to a SCSS file (ie. `$grid-breakpoints`), but not sure about here, will take a look how to do it in JSX.

2021-05-06 18:51 UTC, closed without merging