AA-711: implement upsell click events
openedx/frontend-app-learning pull request #392
Opened 2021-03-15 21:29 UTC by ciduarte

2021-03-15 21:34 UTC, ciduarte commented on src/courseware/course/sequence/lock-paywall/LockPaywall.jsx
> +      linkCategory: '(none)',
So, I know this looks weird, but I'm under the impression that `'(none)'` is what they want here... I'll double check w/ rev

See:
https://github.com/edx/edx-platform/pull/24526#discussion_r459447956

https://openedx.atlassian.net/wiki/spaces/RS/pages/1675100377/How+to+find+upsell+link+click+events

2021-03-15 22:07 UTC, MatthewPiatetsky commented on src/course-home/outline-tab/widgets/UpgradeCard.jsx
> +    sendTrackingLogEvent('edx.bi.ecommerce.upsell_links_clicked', {
what is the difference between sendTrackEvent and sendTrackingLogEvent, first goes to segment and second to splunk?

2021-03-15 22:10 UTC, MatthewPiatetsky approved these changes
a review from someone on rev squad familiar with these events might be a good idea

2021-03-16 12:33 UTC, mikix approved these changes

2021-03-16 13:36 UTC, dianekaplan commented on src/courseware/course/sequence/lock-paywall/LockPaywall.jsx
> +      linkCategory: '(none)',
Yes sorry- this awkward choice was my fault, you're right that this is the way to keep it consistent

2021-03-16 13:52 UTC, dianekaplan requested changes
Excited to see this started so soon!

One general flag: I don't see the actual link names passed along to sendTrackEvent or sendTrackingLogEvent in the code (course_home_green and in_course_upgrade)- not sure which one sends to Segment? 

Our trackUpsellClick function in edx-platform took the link name along with the set of properties (pageName, linkType, linkCategory), so segment events have `event:properties:linkName` that we search on, also used by our New Relic graph to see the relative counts of the different upsell links. In this code I don't see the link names being passed along- is this happening in a subtle way that I'm missing, or still to be done?

2021-03-16 14:35 UTC, ciduarte commented
> One general flag: I don't see the actual link names passed along to sendTrackEvent or sendTrackingLogEvent in the code (course_home_green and in_course_upgrade)- not sure which one sends to Segment?
> 
> Our trackUpsellClick function in edx-platform took the link name along with the set of properties (pageName, linkType, linkCategory), so segment events have `event:properties:linkName` that we search on, also used by our New Relic graph to see the relative counts of the different upsell links. In this code I don't see the link names being passed along- is this happening in a subtle way that I'm missing, or still to be done?

The `linkName` is definitely something I missed! Glad you caught that.

2021-03-16 14:53 UTC, ciduarte commented
>  not sure which one sends to Segment?

`sendTrackEvent` goes to Segment, so that's what we actually want. Updated it to use that rather than `sendTrackingLogEvent`.

2021-03-16 16:22 UTC, dianekaplan approved these changes
Thanks for adding the linkName! No other feedback for these changes, so once you've got the new sendTrackEvent lines under test this will be good to go. Thanks!

2021-03-16 20:10 UTC, merged