Account activation pop up added:
openedx/frontend-app-learning pull request #425
Opened 2021-04-28 19:24 UTC by adeelehsan

VAN-435

2021-04-29 14:08 UTC, davidjoy requested changes
Apologies, but there are a number of things I think we're going to need to fix.

1. Please use the AlertModal from Paragon - it should remove the need to have custom CSS for this.  `Modal` has a poor API and is soon to be deprecated.  Documentation is here: https://paragon-edx.netlify.app/components/modal/alert-modal/ 
2. We can't hard code "edX" into our MFEs... these are used by the Open edX community.  If we want to have a button that says "Continue to edX" the "edX" part of that needs to be set to the SITE_NAME configuration variable and parameterized in the i18n message.  
3. Please use more unambiguous `id` attributes for your FormattedMessages and more descriptive descriptions - "cta" isn't really specific to this functionality, and translators may need more details in the descriptions to make these understandable.
4. I see several warnings on the PR about packages that aren't in package.json, such as universal-cookie.  These need to be fixed.
5. There are other warnings about using anchor tags as buttons - these are accessibility issues.  You may need to add a `role` to the anchor tag if it appears as a link and has an onClick handler.

2021-04-30 17:14 UTC, adeelehsan commented
@davidjoy please review it again. I have addressed the requested changes.

2021-05-05 18:38 UTC, davidjoy commented
Hi @adeelehsan - this looks so good!  Thanks for making those changes.

The one last thing I didn't think of at the time would be to add a few component tests for `AccountActivationAlert`, focusing on:

- Proper hiding/showing of the component depending on cookie state (presumably you'll have to mock js-cookie...)
- Proper calling of the activation email endpoint when a user clicks the button.

Basically we want to make sure it shows up only when it's supposed to, and actually calls the API it's supposed to call!

2021-05-17 17:13 UTC, davidjoy requested changes
Thank you for indulging me so far, @adeelehsan.  I hate to say it, but a test that shows that the alert _doesn't_ show up unless the cookie is true seems important.  Otherwise we don't know whether this is being shown to all users all the time.

2021-05-17 17:23 UTC, davidjoy commented on src/alerts/logistration-alert/AccountActivationAlert.jsx
> +                  defaultMessage="resend the email"
Should this message start with a capital?  I.e., "Resend the email"

2021-05-21 16:47 UTC, adeelehsan commented on src/alerts/logistration-alert/AccountActivationAlert.jsx
> +                  defaultMessage="resend the email"
According to the design it should be "resend the email"

2021-05-21 16:56 UTC, davidjoy commented on src/alerts/logistration-alert/AccountActivationAlert.jsx
> +    Cookies.remove('show-account-activation-popup', { path: '/', domain: process.env.SESSION_COOKIE_DOMAIN });
Need this domain be specified?  Does it default to the current domain?

Also, if necessary, custom environment variables need to be added to edx-internal so they show up during the build, and should also be added to the object returned by `getConfig()`, rather than being accessed directly from `process.env`.

2021-05-21 16:57 UTC, davidjoy approved these changes
Small reminder re: the new environment variable.  Otherwise looks good.

2021-05-21 17:01 UTC, adeelehsan commented on src/alerts/logistration-alert/AccountActivationAlert.jsx
> +    Cookies.remove('show-account-activation-popup', { path: '/', domain: process.env.SESSION_COOKIE_DOMAIN });
domain is `.edx.org`. Already created the PR for internal. thanks for the reminder.

2021-05-21 17:53 UTC, mikix approved these changes
I'm a little confused about this case - from the screenshot looks like the user is already logged in, but the modal is talking about logging back in. But regardless, I'm sure you and UX have it all sorted.

2021-05-21 17:53 UTC, mikix commented on src/alerts/logistration-alert/AccountActivationAlert.jsx
> +      onClose={() => ({})}
This feels odd - is this a required prop?

2021-05-27 11:44 UTC, adeelehsan commented on src/alerts/logistration-alert/AccountActivationAlert.jsx
> +      onClose={() => ({})}
Yes, that's why passing empty implementation.

2021-05-27 16:21 UTC, mikix approved these changes

2021-06-04 15:13 UTC, merged