WIP: [BD-26] Add support for special exams
openedx/frontend-app-learning pull request #435
Opened 2021-05-06 13:57 UTC by TamoshaytisV

2021-05-06 13:57 UTC, edx-webhook commented
Thanks for the pull request, @TamoshaytisV! I've created [BLENDED-838](https://openedx.atlassian.net/browse/BLENDED-838) to keep track of it in Jira.   More details are on the [BD-26](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2523627980/BD-26+Proctoring+MFE+and+configuration) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-05-11 13:40 UTC, TamoshaytisV commented
@Zacharis278

2021-05-11 13:47 UTC, zacharis278 commented on src/courseware/course/sequence/Sequence.jsx
> +import SequenceExamWrapper from '../../../../packages/frontend-lib-special-exams/src';
we can't merge with this import since not everyone running this library will have a local version of this package in this specific folder.

we'll also need to add this library to package.json

2021-05-11 13:47 UTC, schenedx reviewed
LGTM. We can only merge this PR after the PR at https://github.com/edx/frontend-lib-special-exams/pull/1 is merged and version created, right?

2021-05-11 13:47 UTC, schenedx commented on src/courseware/data/api.js
> +    specialExamsEnabled: metadata.is_mfe_special_exams_enabled,
#NIT can we rename this flag to be `specialExamsEnabledWaffleFlag`? This way, it's pretty evident in our code base we should retire this flag when the waffle rolls out.

2021-05-12 03:28 UTC, idegtiarov commented on src/courseware/course/sequence/Sequence.jsx
> +import SequenceExamWrapper from '../../../../packages/frontend-lib-special-exams/src';
We've discussed that this part is a show stopper for the PR.

2021-05-13 09:28 UTC, TamoshaytisV commented on src/courseware/data/api.js
> +    specialExamsEnabled: metadata.is_mfe_special_exams_enabled,
addressed

2021-05-14 17:45 UTC, schenedx commented on src/courseware/data/api.js
> +    specialExamsEnabled: metadata.is_mfe_special_exams_enabled,
Thank you for addressing this!

2021-05-14 17:49 UTC, Zacharis278 requested changes

2021-05-14 17:49 UTC, Zacharis278 commented on .eslintignore
> -jest.config.js
nit: missing newline

2021-05-14 17:49 UTC, Zacharis278 commented on .gitignore
> +packages
this can be removed now I think

2021-05-14 17:49 UTC, Zacharis278 commented on .gitignore
> +packages
ditto

2021-05-14 17:49 UTC, Zacharis278 commented on src/courseware/CoursewareContainer.jsx
> +    if (!specialExamsEnabledWaffleFlag) {
I think we should put in a unit test to cover the behavior of this waffle flag. It simplistic, but somewhat of a critical code path

2021-05-18 07:36 UTC, idegtiarov commented on .eslintignore
> -jest.config.js
👍

2021-05-19 14:08 UTC, idegtiarov commented on src/courseware/CoursewareContainer.jsx
> +    if (!specialExamsEnabledWaffleFlag) {
Default behavior already covered by the tests, please take a look at https://github.com/edx/frontend-app-learning/blob/master/src/courseware/CoursewareContainer.test.jsx#L409
Since we have the flag `specialExamsEnabledWaffleFlag == false` mfe-al redirecs to the LegacyWebUrl

2021-05-21 13:15 UTC, idegtiarov commented
@Zacharis278 tests have passed! What would be our next step?

2021-05-21 13:15 UTC, Zacharis278 approved these changes

2021-05-24 12:44 UTC, merged