Adds notes visibility toggle
openedx/frontend-app-learning pull request #44
Opened 2020-04-03 23:42 UTC by davestgermain

[TNL-7162](https://openedx.atlassian.net/browse/TNL-7162)

This adds a notes visibility toggle button, which posts a message to the unit iframe in order to trigger the visibility on the LMS side. Requires https://github.com/edx/edx-platform/pull/23614

This also rearranges the calculator and notes inside a `ContentTools` component.

2020-04-06 19:11 UTC, davidjoy requested changes
Looks good!  Just have a few stylistic suggestions, mostly, to help bring it in line with some best practices and all that.

2020-04-06 19:11 UTC, davidjoy commented on src/courseware/course/tools/data/thunks.js
> +export default function toggleNotes() {
I'm pretty certain I suggested we should add this as a thunk, but now that I read it, I realize this isn't a thunk. :)  I think I'd move this to an `api.js` file instead, just for clarity. Thunks in the frontend apps sorta imply async/promise-based redux actions, neither of which this ended up being in the end.

2020-04-06 19:11 UTC, davidjoy commented on src/courseware/course/tools/index.jsx
> +export default class ContentTools extends Component {
FYI - our best practices would be to have this file be named `ContentTools.jsx` and for the `index.js` file of this directory to merely be a place to consolidate all the directory/module's exports, i.e., the things the rest of the app need to use.  

Take a look at src/courseware/course/bookmark/index.js as an example.

2020-04-06 19:11 UTC, davidjoy commented on src/courseware/course/tools/index.jsx
> +export default class ContentTools extends Component {
Also, this component is a great candidate for a functional component, since it's so simple!

2020-04-06 19:11 UTC, davidjoy commented on src/courseware/course/tools/notes/index.jsx
> +class NotesVisibility extends Component {
Same comment as course/tools/index.jsx above.

2020-04-06 19:11 UTC, davidjoy commented on src/courseware/course/tools/notes/notes.scss
> +    display: inline-block;
To the extent that it's possible, it'd be good to use our utility CSS classes on the tag, which would let us get rid of a good chunk of this custom CSS, I think.  https://edx.github.io/paragon/foundations/css-utilities

2020-04-07 17:32 UTC, davestgermain commented on src/courseware/course/tools/data/thunks.js
> +export default function toggleNotes() {
Ah, got it. I moved it to `api.js`

2020-04-07 17:35 UTC, davestgermain commented
@davidjoy I've refactored the modules. I don't know how to totally avoid custom css for those bottom buttons, but I made a common class for both the calculator and notes buttons.

2020-04-09 15:18 UTC, davidjoy approved these changes

2020-04-09 18:46 UTC, merged