test: add consumer pact tests for courseware
openedx/frontend-app-learning pull request #510
Opened 2021-06-30 12:52 UTC by Ali-D-Akbar

[PROD-2401](https://openedx.atlassian.net/browse/PROD-2401)
Adding contract based tests. The pact will be between frontend-app-learning and LMS.

Steps to run these tests on your local machine:
1. npm install
2. npm test -- src/courseware/data/pact-tests/lmsPact.test.jsx

2021-06-30 17:05 UTC, DawoudSheraz commented on package.json
> +    "jest-pact": "^0.9.1",
why jest-pact? how is it different from pact-js? and what's the support level for jest-pact as compared to pact-js?

2021-06-30 17:06 UTC, DawoudSheraz commented on src/pact-tests/lmsPact.test.jsx
> +pactWith({ consumer: 'MyConsumer', provider: 'MyProvider' }, provider => {
use appropriate consumer and provider names. the consumer is frontend-app-learning and the provider is lms.

2021-06-30 17:14 UTC, DawoudSheraz commented on src/pact-tests/lmsPact.test.jsx
> +    it('returns course blocks', () => getAuthenticatedHttpClient().get(`${baseUrl}/api/courses/v2/blocks/`).then(response => {
You should not be making API calls directly in test. Use the method written in api.js. This is an incorrect way of writing contract tests. See https://docs.pact.io/consumer/contract_tests_not_functional_tests

2021-06-30 17:15 UTC, DawoudSheraz commented on src/pact-tests/lmsPact.test.jsx
> +            'block-v1:edX+DemoX+Demo_Course_1+type@sequential+block@bcdabcdabcdabcdabcdabcdabcdabcd2': {
don't just add random data. Remember that this data or matching data will need to be setup properly in provider verification. Additionally, only add those fields which are used within learning MFE.

2021-06-30 18:03 UTC, Ali-D-Akbar commented on package.json
> +    "jest-pact": "^0.9.1",
jest-pact is exactly like pact-js with some more utility as `pactWith` handles variable ports, starts and ends the mock server beforeAll and afterAll interactions/tests and `provider.verify()` after each interaction/test. Since it works like pact-js, support can be found by pact foundation related to pact-js.

2021-06-30 18:03 UTC, Ali-D-Akbar commented on src/pact-tests/lmsPact.test.jsx
> +pactWith({ consumer: 'MyConsumer', provider: 'MyProvider' }, provider => {
yes, I'll rename once the tests pass.

2021-06-30 18:04 UTC, Ali-D-Akbar commented on src/pact-tests/lmsPact.test.jsx
> +pactWith({ consumer: 'MyConsumer', provider: 'MyProvider' }, provider => {
yes, I'll rename once the tests pass.

2021-08-04 05:40 UTC, DawoudSheraz requested changes

2021-08-04 05:40 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  });
async/await can be removed.

2021-08-04 05:40 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +    it('should return the correct data', async () => {
make this statement more explicit.

2021-08-04 05:40 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +    it('should return the correct data', async () => {
same here

2021-08-04 05:40 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +            license: null,
don't just use random values. Understand how the api returns the information. e.g. you have mentioned enrollment mode as null. This will cause issues during provider verification.

2021-08-04 05:40 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +        },
we will assume user is logged(and setup this in provider states). Since you have mentioned correct data, don't add any auth related error. Instead, add what will be the success value for this.

2021-08-04 05:40 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +      });
description and interactions don't match.

2021-08-04 09:05 UTC, azanbinzahid commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  beforeAll(async () => {
maybe async/await can be removed from here as well, [ref](https://github.com/pact-foundation/pact-js/blob/7c91c33a7a81f74c801f03a957b06905839d8743/examples/e2e/test/consumer.spec.js#L87).

2021-08-04 09:12 UTC, azanbinzahid commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +    it('should return the correct data', async () => {
A few examples can be found from [here](https://github.com/pact-foundation/pact-js/blob/master/examples/e2e/test/consumer.spec.js) especially describe / it statements.

2021-08-05 08:49 UTC, Ali-D-Akbar commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  beforeAll(async () => {
They're using one-liner syntax where the promise is returned directly.
We have to explicitly add async/await in our example since the promise won't be returned as a result.

2021-08-09 10:33 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  const reDate = '^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][2
nit: dateRegex. Is this taken from pact's formatter?

2021-08-09 10:33 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  });
remove curly braces. The presence of braces can change the return format. Correct me I missed something with finalize block.

2021-08-09 10:34 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +          path: '/api/courses/v2/blocks/',
add query params that are added by api.js method when doing api call

2021-08-09 10:35 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  const reDate = '^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][2
You can use common matchers from https://github.com/pact-foundation/pact-js/#match-common-formats

2021-08-09 10:36 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +            root: like('block-v1:edX+DemoX+Demo_Course+type@course+block@course'),
using like here does not make sense. like is used with objects. You can use string here https://github.com/pact-foundation/pact-js/#match-based-on-type

2021-08-09 10:37 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +          path: `/api/courseware/course/${courseId}`,
again, if there are query params added before API call, add them here.

2021-08-09 10:38 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +              upgrade_url: string('link'),
you can use the `term` to do certain checks again link https://github.com/pact-foundation/pact-js/#match-by-regular-expression

2021-08-09 10:39 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +            id: like('course-v1:edX+DemoX+Demo_Course'),
instead of like, use term to validate the regex checks. You can use opaque keys regex for this purpose.

2021-08-09 10:40 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +              sku: '8CF08E5',
instead of hard coding these values, use appropriate matchers.

2021-08-09 10:40 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +            items: eachLike({
add minimum value for eachLike.

2021-08-09 10:41 UTC, Ali-D-Akbar commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  const reDate = '^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][2
I took it from here: https://www.myintervals.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/

2021-08-09 10:42 UTC, DawoudSheraz reviewed
added some nits and updates to address

2021-08-09 10:42 UTC, Ali-D-Akbar commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  });
Either is fine Since the testing environment eventually waits for every open promise to be closed.
But yes, changing this for the sake of consistency.

2021-08-09 10:49 UTC, Ali-D-Akbar commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +              sku: '8CF08E5',
using like on an object applies all appropriate matchers to each value: https://github.com/pact-foundation/pact-js/#match-based-on-type 

`Note that you can wrap a like around a single value or an object. When wrapped around an object, all values and child object values will be matched according to types, unless overridden by something more specific like a term.`

2021-08-09 10:51 UTC, Ali-D-Akbar commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +            items: eachLike({
Min value cannot be set to 0 and by default, the min value is 1.

2021-08-09 11:22 UTC, azanbinzahid commented on src/courseware/data/pact-tests/frontend-app-learning-lms.json
> +      },
If we cross reference it from lms api-docs, we can see this endpoint requires at-least one param. Therefore it fails to get a matching response from LMS. What can be done to ensure param requirements for all such api calls?

![image](https://user-images.githubusercontent.com/47540683/128698751-ed0b7af5-ac59-4069-a34d-72bdbddd5863.png)

2021-08-09 12:15 UTC, Ali-D-Akbar commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +              upgrade_url: string('link'),
This is kind of an unsurety what this field will have. It can be either a whole http url, just an api endpoint for frontend-app-lms or can be null. Applying regex might complicate a lot of things here.

2021-08-10 07:53 UTC, DawoudSheraz commented on src/courseware/data/pact-tests/lmsPact.test.jsx
> +  const reDate = '^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][2
@Ali-D-Akbar For followup PR, replace this regex with the matchers provided by pact

2021-08-10 07:54 UTC, DawoudSheraz approved these changes
ok to merge for the first run.

2021-08-10 09:32 UTC, azanbinzahid approved these changes

2021-08-10 09:57 UTC, merged