fix: update Navigation tab items styling to match design.
openedx/frontend-app-learning pull request #536
Opened 2021-07-12 18:56 UTC by saadyousafarbi

### [TNL-7969](https://openedx.atlassian.net/browse/TNL-7969)

### Description
Styling fix for Navigation tab items.

#### Before
<img width="615" alt="Screen Shot 2021-07-12 at 11 54 42 PM" src="https://user-images.githubusercontent.com/30112155/125341091-ab02e980-e36c-11eb-81a7-350295fa57ed.png">

#### After
<img width="621" alt="Screen Shot 2021-07-12 at 11 53 13 PM" src="https://user-images.githubusercontent.com/30112155/125341083-a9392600-e36c-11eb-98c4-967c80acda8e.png">

2021-07-13 07:08 UTC, marcotuts requested changes
Not sure if comments are visible until I create a review (mobile UI on GitHub makes it seem like my comments are still pending.) 

Added two online comments

2021-07-13 07:08 UTC, marcotuts commented on src/index.scss
> +      background-color: $gray-400;
I think this should switch to $light-400 (it's a lighter gray color)

2021-07-13 07:08 UTC, marcotuts commented on src/index.scss
> +      background-color: $gray-400;
Same note here -

I think this should switch to $light-400 (it's a lighter gray color)

2021-07-13 20:05 UTC, saadyousafarbi commented
@marcotuts updated PR and screenshot with updated color! Please have a look, Thank you!

2021-07-26 09:07 UTC, awais-ansari reviewed
Everything is good. Just need to add a focus effect on tabs. 
https://www.figma.com/file/eGmDp94FlqEr4iSqy1Uc1K/Paragon-Design-System?node-id=9076%3A672

2021-07-26 20:24 UTC, saadyousafarbi commented
@awais-ansari thanks for pointing that out. Have added `focus` state, and added a screenshot within the PR description.

2021-07-27 07:28 UTC, awais-ansari approved these changes

2021-07-27 20:23 UTC, marcotuts approved these changes

2021-07-27 20:28 UTC, merged