Update path
openedx/frontend-app-learning pull request #540
Opened 2021-07-13 17:18 UTC by KristinAoki

2021-07-15 19:13 UTC, ormsbee commented on docs/decisions/0009-courseware-url-shortening.md
> +https://learning.edx.org/c/:courseId/:sequenceHash/:unitHash/:sectionSlug/:sequenceSlug/:unitSlug/
Are we ever going to allow partial paths? Or will all other path types forward to this?

2021-07-15 19:19 UTC, ormsbee commented on docs/decisions/0009-courseware-url-shortening.md
> +https://learning.edx.org/c/course-v1:edX+DemoX.1+2T2019/YmxvY2/njuRCq/Optional_Example_Problem_Types/STEM_Problems/Code_Grader
What is used to generate the slug fields? Django's [slugify](https://docs.djangoproject.com/en/3.2/ref/utils/#django.utils.text.slugify)? If so, it's going to move things to lowercase and dashes, so the slug portion would look like: `optional-example-problem-types/stem-problems/code-grader`.

Are Unicode identifiers going to be accepted in the slug? (Django supports it).

2021-07-15 19:24 UTC, ormsbee commented on docs/decisions/0009-courseware-url-shortening.md
> +The slugs based on `display_name` are optional because not all blocks have an associated `display_name` attributes, most likely to occur in OLX imports. The `sequenceHash` and `unitHash` will shorten
We have a `display_name_with_default` attribute that will guarantee that something gets put there, FWIW.

2021-07-15 19:24 UTC, ormsbee commented on docs/decisions/0009-courseware-url-shortening.md
> +* :sectionSlug (optional) - `display_name` of the current sequence's parent section.
Does the Course name get its own slug?

2021-07-15 19:27 UTC, ormsbee commented on docs/decisions/0009-courseware-url-shortening.md
> +The slugs based on `display_name` are optional because not all blocks have an associated `display_name` attributes, most likely to occur in OLX imports. The `sequenceHash` and `unitHash` will shorten
> blake2b

Please specify the digest size (6 bytes?).

2021-07-15 19:44 UTC, ormsbee commented on docs/decisions/0009-courseware-url-shortening.md
> +* :unitSlug (optional) - `display_name` of the current unit
When slugs are omitted (or they're old slugs because the name has changed since the link was created) do they redirect to the canonical version with slugs?

2021-07-15 19:50 UTC, ormsbee commented on docs/decisions/0009-courseware-url-shortening.md
> +https://learning.edx.org/c/:courseId/:sequenceHash/:unitHash/:sectionSlug/:sequenceSlug/:unitSlug/
If we're going to allow partial paths (e.g. a sequence hash without a unit hash), please consider combining the significant parts with a different delimiter, like a period:

```
https://learning.edx.org/c/course-v1:edX+DemoX.1+2T2019/YmxvY2.njuRCq/Optional_Example_Problem_Types/STEM_Problems/Code_Grader
```

That way there's no ambiguity–we know that the segment after the course key is going to be the significant ID portion of it, and everything that follows is for readability. We don't have to worry that maybe "njuRCq" is a hash ID or maybe it's the first part of the decorative-stuff-to-be-ignored.

2021-07-19 13:42 UTC, KristinAoki commented on docs/decisions/0009-courseware-url-shortening.md
> +* :sectionSlug (optional) - `display_name` of the current sequence's parent section.
I was not originally going to include it, but if you think I should, I will.

2021-07-19 15:54 UTC, ormsbee commented on docs/decisions/0009-courseware-url-shortening.md
> +* :sectionSlug (optional) - `display_name` of the current sequence's parent section.
@mondiaz, @JAAkana: Any thoughts on whether a slug of the course name belongs in courseware URLs, or is that just making it longer without providing sufficient value?

2021-07-20 13:17 UTC, JAAkana commented on docs/decisions/0009-courseware-url-shortening.md
> +* :sectionSlug (optional) - `display_name` of the current sequence's parent section.
I have a mild opinion to rely first on  courseID since the org/number/run are unique and convey human-ish info. Course names can be long and not-unique (i.e. multiple runs), I believe names  re-cover ground captured in the courseID.

2021-08-04 21:43 UTC, kdmccormick requested changes
Good work so far. Of my comments below, the only one that's a real concern to me is the one about the old URLs still working.

Do you feel like you'll be able to integrate that requirement into your project? Happy to chat if you think it would increase the scope too much--maybe there is a way the team can help.

2021-08-04 21:43 UTC, kdmccormick commented on docs/decisions/0009-courseware-url-shortening.md
> +After exploring different URL patterns and possible redundancies in the current URL format. The course, run, and organization is stated in every portion of the URL. We also do not need the URL to tel
> After exploring different URL patterns and possible redundancies in the current URL format. 

Consider rewording this incomplete sentence.

2021-08-04 21:43 UTC, kdmccormick commented on src/course-home/data/api.js
> +          models.sequences.[sequenceId].sectionId = section.id;
Huh, I've never seen the `.[` syntax before. What does that do?

2021-08-04 21:43 UTC, kdmccormick commented on docs/decisions/0009-courseware-url-shortening.md
> +# Courseware URL shortening
Thanks for including an ADR! It's already made this change easier for me to review, and it should be helpful for devs who want to understand this change in the future.

2021-08-04 21:43 UTC, kdmccormick commented on docs/decisions/0009-courseware-url-shortening.md
> +* :unitHash (required) - a `urlsafe_b64encode` version of the `unitId`.
Are these actually the urlsafe_b64encoded versions *of the blake2b hash* of the ids?

2021-08-04 21:43 UTC, kdmccormick commented on docs/decisions/0009-courseware-url-shortening.md
> +If old URLs are not properly routed then the content and those links will no longer be accessible to the user. The old URLs could include, but not limited to, bookmarks and exams.
From the ticket's acceptance criteria:

> * First, implement the proposal above, but redirect the new URLs to old URLs. So, there will be no user-facing change yet, since users will still only know about the old URLs.
> * When we have confidence that the new URLs are working, make it so old URLs redirect new URLs instead.
> * ...
> * Finally, update https://github.com/edx/edx-platform/blob/c194b3fa573ef730c5a228acbea0ce6823519b8c/openedx/features/course_experience/url_helpers.py#L147, which builds URLs for frontend redirection, to use the new URLs.
> * It may be smart to leave in support for the old URLs (redirecting them to the new ones) forever. This would avoid breaking bookmarks, old links, etc. It would also allow us to link to the Learning MFE without computing the unit_key_hash , for debugging or whatever.

It seems like this PR jumps to Step 2, in which the new URLs become the canonical URLs. That's OK, but I do think it's important that the old URLs continue to work, at least for now. Ensuring that the old URLs don't break will significantly de-risk the rollout of this change.

2021-08-04 21:43 UTC, kdmccormick commented on src/courseware/course/sequence/content-lock/ContentLock.jsx
> +    history.push(`/c/${courseId}/${prereqId}`);
Wow, half of the tests in this repo must have broken when you made this change! Kudos to you for working through those.

2021-08-04 21:43 UTC, kdmccormick commented on docs/decisions/0009-courseware-url-shortening.md
> +
The changed URLs may have an impact on currently-running experiments, which often depend on the URL scheme. I'll follow up on this.

2021-08-05 13:12 UTC, KristinAoki commented on src/course-home/data/api.js
> +          models.sequences.[sequenceId].sectionId = section.id;
Definitely a typo, thanks for catching1

2025-04-15 20:47 UTC, bradenmacdonald commented
I'm gonna close this PR - it's definitely not going to be merged after all this time. Would still be nice to see something like this done eventually though.

2025-04-15 20:47 UTC, closed without merging