[SE-4650] OEP-15 - add support for course-wide custom resources
openedx/frontend-app-learning pull request #581
Opened 2021-08-11 09:59 UTC by ha-D

## Description

Details about the purpose of this PR can be found in [edx-platform#28411](https://github.com/edx/edx-platform/pull/28411).

In this PR we're just taking the course-wide JS and CSS URLs from the course metadata and adding them to then pager `<head>`.

## Testing Instructions

- Run a devstack and checkout both `edx-platform` and `frontend-app-learning` repo to the `hadi/se-4650/oep-15` branch
- Follow the testing instructions [edx-platform#28411](https://github.com/edx/edx-platform/pull/28411) to add course-wide scripts to the course via the studio
- Visit a course page, check that the scripts are added to the page head

(If there's a simple way for me to get the Learning MFE running on the OCIM sandbox in [edx-platform#28411](https://github.com/edx/edx-platform/pull/28411) let me know and I could do that instead, I didn't want to spend too much time seeing whether I could do that or not)

## Reviewers
- [] @nizarmah
- [] @bradenmacdonald

@edx/engage-squad

2021-08-11 09:59 UTC, edx-webhook commented
Thanks for the pull request, @ha-D! I've created [OSPR-5960](https://openedx.atlassian.net/browse/OSPR-5960) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-08-11 22:10 UTC, nizarmah reviewed
Hello @ha-D! Nice work on this as well. 👍🏼 

I've read through the changes and I have a small nit. 

Other than that, I'm building a new app server for the sandbox instance where the `frontend-app-learning` MFE is enabled.

I'll update my review once the new app server is ready for me to test.

2021-08-11 22:10 UTC, nizarmah commented on src/tab-page/LoadedTabPage.jsx
> +        {courseWideJs && courseWideJs.map(js => <script key={js} src={js} />)}
Small nit: would you mind please adding the script type, `type="text/javascript"`?

2021-08-12 18:35 UTC, ha-D commented on src/tab-page/LoadedTabPage.jsx
> +        {courseWideJs && courseWideJs.map(js => <script key={js} src={js} />)}
Done

2021-08-14 11:50 UTC, nizarmah approved these changes
@ha-D thanks for addressing the comment I had 👍🏼 I've setup the [frontend-app-learning](https://app.pr28411.sandbox.opencraft.hosting/learning/course/course-v1:edX+DemoX+Demo_Course/home) MFE on the [sandbox instance](https://pr28411.sandbox.opencraft.hosting/).

I've also tested that things are working as expected there as well.

I had some trouble with the `toastr` library. I didn't end up investigating it; instead, I added an alert dialog.

LGTM though. I'll pass the review over to @bradenmacdonald.

2021-08-18 14:53 UTC, natabene commented
@ha-D Thank you for your contribution. Please let me know once it is ready for our review.

2021-08-18 21:13 UTC, bradenmacdonald commented
@natabene I think this is ready for review now, see comment above.

Although I was asked to review, I'm not a core committer on this repo nor super up to speed with it, so I think we'll need you to find us a reviewer.

The code seems simple and straightforward though :)

2021-08-23 16:12 UTC, natabene commented
@BbrSofiane Would you like to review as a core committer for frontend-app-learning?

2021-08-24 17:55 UTC, mikix commented on src/tab-page/LoadedTabPage.jsx
> +        {courseWideCss && courseWideCss.map(css => <link key={css} rel="stylesheet" href={css} />)}
I'm very leery of adding arbitrary css/js to the react side of things. The MFE is fast moving and doesn't want to have to make guarantees about DOM structure or anything like that.

For example, when we added the course-welcome and course-handouts features to the MFE, we "sandboxed" that arbitrary html/js inside iframes.

Can we do this asset loading inside the courseware iframe, to better isolate it?

2021-08-24 17:56 UTC, mikix commented on src/tab-page/LoadedTabPage.jsx
> +        {courseWideCss && courseWideCss.map(css => <link key={css} rel="stylesheet" href={css} />)}
Oh I'm sorry - I'm reading the part of the platform PR that says this is explicitly your point - you want them in the parent page too.

2021-08-24 18:49 UTC, mikix commented on src/tab-page/LoadedTabPage.jsx
> +        {courseWideCss && courseWideCss.map(css => <link key={css} rel="stylesheet" href={css} />)}
I'm chatting with folks that are bigger frontend experts at edX - but this whole arbitrary JS approach is very much not where we are trying to heading with the MFEs. I'm trying to see what the vision for this kind of use case is.

And your use case is basically loading some external libraries that do page-wide stuff, not trying to manipulate any specific DOM structures, yeah? Because that would definitely be a problem, given how React works.

But maybe we can find a more future-proof way to inject external libraries...

2021-08-24 20:35 UTC, jmyatt requested changes
we will not be able to approve this approach.  As @mikix mentioned, this works around a core edX MFE principle of sound boundary definitions.

2021-08-25 12:19 UTC, ha-D commented
All right, thats understandable. We can assume the Course-wide JS/CSS should only be targeted towards the XBlocks and course material (which is handled in this [PR](https://github.com/edx/edx-platform/pull/28411)) and not the MFE.

As for use cases, I can think of a couple examples where having something like this in the MFE would have been useful to clients:
- Adding things like chatbots to all pages
- Adding a client's preferred analytics service to their OpenEdx deployment

2021-08-27 13:53 UTC, Colin-Fredericks commented on src/tab-page/LoadedTabPage.jsx
> +        {courseWideCss && courseWideCss.map(css => <link key={css} rel="stylesheet" href={css} />)}
@mkikix Glad to demo some of our use cases if it would help.

2021-09-02 15:40 UTC, bradenmacdonald commented
@ha-D @jmyatt What about changing this approach to only add the JS within the iframe? Surely having that use case is better than nothing, and then there's no interference with React.

And it provides similar capabilities to the current situation, which sees authors doing things like adding HTML blocks (with the custom JS) to every unit - which has the same effect but is a giant pain to manage.

2021-09-02 16:55 UTC, ha-D commented
@bradenmacdonald Yeah I agree, it's what I intended as well.  It wouldn't need any changes on the MFE side though, the content rendered in the iframes should already have the JS included with the changes in the edx-platform PR, since it's using the same base templates that were changed there.

2021-09-02 17:23 UTC, mikix commented
Yeah from an MFE perspective, loading the JS in the xblock iframe seems fine - that's similar to existing patterns and security boundaries.

I think medium to long term, there might need to be a discussion around a modern version of OEP-15. But in the meantime, having this JS loaded inside the xblock iframe seems reasonable (and isn't anything adding any new risk, right? - course teams can inject arbitrary JS via html xblocks - this is just a super easy way to do it across the course, yeah?)

Which would mean we can close this MFE-side PR?

2021-09-02 20:36 UTC, Colin-Fredericks commented
> having this JS loaded inside the xblock iframe seems reasonable (and isn't anything adding any new risk, right? - course teams can inject arbitrary JS via html xblocks - this is just a super easy way to do it across the course, yeah?)

@mikix That's correct - this will replicate existing functionality but with a centralized file reference. Not as useful as the original proposal, but still an improvement.

Presumably we'll have to keep adding JS to custom tabs by hand, unless those are secretly XBlocks these days. At least that's fewer files.

We *used* to be able to access the outer frame for the course, but the "new user experience" broke that and we had to pull a bunch of course navigation walkthroughs.

2021-09-08 19:23 UTC, natabene commented
Owning team believes that, unfortunately, the only thing to do with this PR is to close it without merging. That latest comment seems like more of a Product question, and not something that this PR addresses.

2021-09-08 19:37 UTC, closed without merging

2021-09-14 19:57 UTC, edx-webhook commented
@ha-D Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-learning&entry.867055334=https://github.com/edx/frontend-app-learning/pull/581&entry.1484655318=https://github.com/ha-D&entry.752974735=2021-08-11+09:59&entry.1917517419=2021-09-08+19:37&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->