Feat  breadcrumb rolloutout flag + analytics
openedx/frontend-app-learning pull request #647
Opened 2021-09-20 15:41 UTC by connorhaugh

2021-09-20 18:07 UTC, connorhaugh commented
Still need to add unit tests, but defaults for the environments seem to be working.

2021-09-20 18:23 UTC, kdmccormick requested changes
Tracking stuff looks good.

Some change requests are around the config stuff. I feel like we should have some better docs around all of this...

2021-09-20 18:23 UTC, kdmccormick commented on .env.development
> +ENABLE_JUMPNAV=''
is this really the value you want in development mode?

2021-09-20 18:23 UTC, kdmccormick commented on .env.test
> +ENABLE_JUMPNAV=''
same question

2021-09-20 18:23 UTC, kdmccormick commented on README.rst
> +  Disable to have simple hyperlinks for breadcrumbs.
What would I set it to to disable it?

(yeah, I know 'false' is kinda obvious, but can booleans-as-strings can get confusing sometimes. best to be explicit.)

2021-09-20 18:23 UTC, kdmccormick commented on .env
> +ENABLE_JUMPNAV='false'
this is the default value -- so you're actually defaulting it to 'false' right now.

2021-09-20 18:23 UTC, kdmccormick commented on src/index.jsx
> +        ENABLE_JUMPNAV: process.env.ENABLE_JUMPNAV || 'true',
As counterintuitive as it is, I'd go with the grain here and go with `|| null` instead of `|| 'true'`. The best place to set the default is in the `.env` file, which is where folks will look to see what variables are available. This `mergeConfig` block is just a bit of boilerplate that we have in all MFEs for some reason.

2021-09-20 18:34 UTC, kdmccormick commented
@connorhaugh Here's how the frontend config process works, since it'll probably clarify my suggestions.

* When an MFE is built, `NODE_ENV` is checked.
  * If there is a matching `.env.$NODE_ENV`, then that file is used to populated `process.ENV`.
  * Otherwise, `.env` is used to populate `process.ENV`.
  * Additionally, build configuration values can be explicitly passed in on the command line. These values override what's in the `.env*` files.
* Once the frontend is loaded, frontend-platform calls `initialize`, and merges the config from `process.ENV` into its internal configuration dictionary, which is exposed through `getConfig()`.

How does this work in production? In our prod-frontend-app-* and stage-frontend-app-* pipelines, each
 MFE is built by invoking `npm run build`.  Since NODE_ENV is `production`, the default `.env` is used. However, the values from the correspondin `*_config.yaml` are passed into the command line there, overriding the default values.

2021-09-20 19:13 UTC, connorhaugh commented on src/index.jsx
> +        ENABLE_JUMPNAV: process.env.ENABLE_JUMPNAV || 'true',
Ahh, that makes sense, just kind of a jumbled "where is the thing that happens first" situtation. I'm planning to turn your reviews, etc into a doc or confluence page.

2021-09-21 18:00 UTC, connorhaugh commented on README.rst
> +  Disable to have simple hyperlinks for breadcrumbs.
I have added additional info.

2021-09-21 18:00 UTC, connorhaugh commented on .env
> +ENABLE_JUMPNAV='false'
I have made this "true", as true should be default, then it can be overwritten in prod/edge.

2021-09-21 18:01 UTC, connorhaugh commented on .env.development
> +ENABLE_JUMPNAV=''
set to true.

2021-09-21 18:01 UTC, connorhaugh commented on .env.test
> +ENABLE_JUMPNAV=''
set to true.

2021-09-21 18:04 UTC, connorhaugh commented
@kdmccormick I've addressed you concerns, making "true" the default, and letting the config overrides for prod and edge be "false". That should work. I'd love to finish off the review/ approval pending code coverage (which is taking a while, bc jest).

2021-09-21 18:57 UTC, kdmccormick approved these changes
LGTM pending codecov 👍🏻 

Heads up -- someone could deploy stage frontend-app-learning to production at any point. If this isn't merged yet, then that would push the jumpnav out to everyone, right? If so, I would recommending either pausing the frontend-app-learning pipeline (with a message referencing this PR) or temporarily reverting your earlier PR. If you're not able to merge this by EOD today, then I'd recommend the latter option, as to not clog up the pipeline for everyone for too long.

2021-09-21 18:57 UTC, kdmccormick commented on README.rst
> +  Disable to have simple hyperlinks for breadcrumbs. Setting it to any other value but 'true' ('false','I love flags', 'etc' would disable the Jumpnav).
I appreciate the specificity here 💯

2021-09-21 19:39 UTC, merged