WIP: Add studio/insights links to staff toolbar
openedx/frontend-app-learning pull request #65
Opened 2020-05-07 21:17 UTC by stvstnfrd

2020-05-07 21:41 UTC, stvstnfrd reviewed
Here's a first take at TNL-7152.

The one thing that isn't nailed down yet is the getting/setting of the config variables (for the Studio and Insights URL bases), but everything else works around that. @davidjoy Am I on the right track?

2020-05-07 21:41 UTC, stvstnfrd commented on .env
> +CMS_BASE=null
For these two settings, I'm using the equivalent setting name from `edx-platform`.

2020-05-07 21:41 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +import { getConfig } from '@edx/frontend-platform';
Is this how I want to be fetching `edx-platform`-like settings?

2020-05-07 21:41 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +  if (!url_studio && !url_insights) {
If we aren't displaying either link, bail, since there's nothing else to show yet (no masquerade dropdown).

2020-05-07 21:41 UTC, stvstnfrd commented on .env
> +ANALYTICS_DASHBOARD_URL=null
Is this what I need to do for `getConfig`?
And if so, how do these values get set during deployment?

2020-05-07 21:41 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +  // const url_studio_base = 'http://localhost:18010';
I have these hard-coded sections here because the `getConfig` doesn't seem to be plumbing through...

2020-05-07 21:44 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +      url_studio = url_studio_base + '/container/' + unitId;
Is there a blessed way to build cross-service links?
Within the same django service, we could call `reverse`, but I'm not clear on how, if at all, we do so reproducibly in MFEs.

We could also build the URL on the backend and spit it out via the API, instead of letting the frontend build it :shrug:

2020-05-08 09:35 UTC, stvstnfrd commented on .env
> +ANALYTICS_DASHBOARD_URL=null
Ah, it looks like I need a PR to frontend-platform, in the spirit of https://github.com/edx/frontend-platform/pull/77 ?

2020-05-08 14:36 UTC, davidjoy commented on .env
> +ANALYTICS_DASHBOARD_URL=null
The frontend-platform PR is only necessary if it's a thing we want/desire all micro-frontends to have by default.  

As for production, environment variables are setup in `edx-internal` here: https://github.com/edx/edx-internal/blob/master/frontends/frontend-app-learning/prod_config.yml

(Note that that's the prod one - stage is a sibling of it)

If we _do_ want ANALYTICS_DASHBOARD_URL to be available to all MFEs, then it can instead be added here:

https://github.com/edx/edx-internal/blob/master/frontends/common/prod_config.yml

... in which case we'll want that frontend-platform PR.

2020-05-08 14:37 UTC, davidjoy commented on .env
> +CMS_BASE=null
Hmm, I'm not sure which is the greater virtue - making it consistent with the other frontend values, or with another system... for what it's worth, they don't actually share config (see the above comment).  I think I'd lean towards making this .env file consistent/making the values predictable when writing MFEs.

2020-05-08 14:38 UTC, davidjoy commented on .env
> +ANALYTICS_DASHBOARD_URL=null
As per the below, maybe this is `ANALYTICS_DASHBOARD_BASE_URL`?

2020-05-08 14:39 UTC, davidjoy commented on src/courseware/course/InstructorToolbar.jsx
> +  // const urlBase = getConfig().ANALYTICS_DASHBOARD_URL;
Without the frontend-platform PR, you can get custom config into `getConfig()` like this, as demonstrated in the account settings MFE:

https://github.com/edx/frontend-app-account/blob/master/src/index.jsx#L59

2020-05-08 14:42 UTC, davidjoy commented on src/courseware/course/InstructorToolbar.jsx
> +      urlFull += `/${courseId}`;
This function should always have a courseId provided to it, I'd guess.

In which case I think the whole function collapses down to:

```
return `${getConfig().ANALYTICS_DASHBOARD_URL}/courses/${courseId}`;
```

I don't feel strongly about it at all, but in general I've just been putting strings like that inline and not bothering with a function or constant unless I'm reusing it. ¯\_(ツ)_/¯

2020-05-08 14:43 UTC, davidjoy commented on src/courseware/course/InstructorToolbar.jsx
> +    if (unitId) {
Unlike the above, `unitId` doesn't always exist yet, so this one may continue to need some conditionals like this. 👍

2020-05-08 14:44 UTC, davidjoy commented on src/courseware/course/InstructorToolbar.jsx
> +    return null;
I _think_ we agreed at standup yesterday that we still want the links to the legacy experience to hang around for now, because instructors outside the canary are still testing/using both.

2020-05-08 14:44 UTC, davidjoy requested changes
See ze comments!  Nothing crazy, I hope. :)

2020-05-08 14:50 UTC, marcotuts commented on src/courseware/course/InstructorToolbar.jsx
> +      url_studio = url_studio_base + '/container/' + unitId;
what do we do for the "view unit in studio" button, is that any help at all? (maybe not in MFE land?)

2020-05-08 14:52 UTC, marcotuts commented on src/courseware/course/InstructorToolbar.jsx
> +    return null;
I was going to ask if this PR would remove the existing "view unit in studio" buttons. 

One option is - these buttons could also be added via an edx-platform PR and removed from all content views for both legacy and MFE? (thoughts on that? )

2020-05-11 21:52 UTC, stvstnfrd reviewed
Comments addressed.

2020-05-11 21:52 UTC, stvstnfrd commented on .env
> +CMS_BASE=null
So it looks like we already have a variable `STUDIO_BASE_URL` in the common internal vars.
So I'll reuse that and punt on the moral dilemma :)

2020-05-11 21:52 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +  // const urlBase = getConfig().ANALYTICS_DASHBOARD_URL;
Thanks for the sample!
Implemented.

2020-05-11 21:52 UTC, stvstnfrd commented on .env.development
> -PORT=2000
Just alphabetized.

2020-05-11 21:52 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +            <a className="btn d-block btn-outline-light" href={urlLms}>View in the existing experience</a>
Back by popular demand!

2020-05-11 21:52 UTC, stvstnfrd commented on .env
> +STUDIO_BASE_URL=
Just looping back here from the "outdated" thread:
This variable appears to already exist in our prod/stage secrets, so using this name.

2020-05-11 21:52 UTC, stvstnfrd commented on .env
> +INSIGHTS_BASE_URL=
Since we're not tied to the `edx-platform` convention, I renamed this to be more in line with the existing pattern of `<service>_BASE_URL`.

2020-05-11 21:52 UTC, stvstnfrd commented on .env.test
> +BASE_URL='localhost:2000'
Updating, per template thread, to keep in sync.

2020-05-11 21:52 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +      urlFull += `/${courseId}`;
#### re: function or not

Here, we do need at least the first `if` check;
we don't want to show any link if the `*_BASE_URL` isn't set.
I'm not a fan of ternary operators, especially with computed/formatted values (harder to debug), so I'll keep the function in use :)

#### Re: the `courseId` check:
Yeah, it should always be set now, but...
Maybe I was over-future-proofing; I figured covering that edge case would also make this "widget" work in a course-unaware situation (and be slightly more resilient).

#### As is, if called without a `courseId`, it will link to your list of all courses on your Insights Dashboard


Alternatively, if we do _not_ want to support this behavior (ie the button not be used/displayed in a course-unaware situation), we could return `falsey` to:

#### "hide" the button if called without a `courseId`.

```js
let urlFull;
if (urlBase) {
  if (courseId) {
    urlFull = `${urlBase}/courses/${courseId}`;
  }
}
```

If we don't check for `courseId` at all (and just interpolate directly) and this is called without `courseId`, this will fail silently with links like:
```
https://localhost/courses/null
```

which is the kind of thing we probably won't notice until we notice ;)

FWIW, the Studio link is _not_ displayed if called without either `courseId` or `unitId`..

My preference would be leave as-is, but I'm also open to hiding the button entirely if misconfigured (called without `courseId` (see above) or even with an empty/`falsey` value. I'd prefer to not leave this edge uncovered :)

### TL;DR: Should we fail or fall-back if this is called without a `courseId`?
- fail: do not show the link/button
- fall-back: show a link/button to the general Insights dashboards (list of all courses)

2020-05-11 21:52 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +            <a className="btn d-block btn-outline-light" href={urlLms}>View in the existing experience</a>
@marcotuts Note: I did remove `unit` from `View [unit] in the existing experience`, to match the text on the other two buttons `View in Studio`, `View in Insights`.
It also makes the long button slightly shorter ;)

Happy to restore the full text or change to something else.

2020-05-11 21:52 UTC, stvstnfrd commented on .env
> +STUDIO_BASE_URL=
Oh, also worth pointing out @davidjoy , defaulting these to `null` appears to set them to the _string_ `null`;
I couldn't figure out why it wasn't coming back `falsey`...

So we may want to circle back here and revisit how we're using default `null` values, in this repo and through the ecosystem (starting w/ the template?).

- Maybe I did something weird?
  - Can you repro?
- Maybe this is just the first it's come up?

2020-05-11 21:52 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +            <a className="btn d-block btn-outline-light" href={urlLms}>View in the existing experience</a>
![Screenshot_2020-05-11_14-50-14](https://user-images.githubusercontent.com/7300975/81615771-ff8c8c80-9396-11ea-87fa-8e9e9768e88a.png)

2020-05-14 15:46 UTC, davidjoy commented on .env.test
> -SEGMENT_KEY=null
Huh, looks like this disappeared here and in the dev one?  (I only nit about this because keeping the three files in sync with the same keys is the only way to stay sane when you actually have to debug something related to them. :)

2020-05-14 15:52 UTC, davidjoy commented on src/courseware/course/InstructorToolbar.jsx
> +      urlFull += `/${courseId}`;
Regarding the existence of `*_BASE_URL` - we should be able to take for granted in our application code that these have been defined.  Until recently it was a fatal error in frontend-platform if one of them came through as `undefined`, today you'll get a console warning for each one that hasn't been set properly.  

As for the courseId, sounds a _bit_ over-future-proofy to me, but I don't feel very strongly.  Might be worth noting that it won't happen in the current client-side implementation, but we want to leave the check in as an accurate representation of what it's capable of.

2020-05-14 15:53 UTC, davidjoy commented on src/courseware/course/InstructorToolbar.jsx
> +      urlFull += `/${courseId}`;
And if you do the fallback, that'll be the 'correct' behavior and would only mildly inconvenience a user if there was a bug in getting the courseId in, right?  Seems better than hiding it, which stops them dead.  I vote for fallback!

2020-05-14 15:54 UTC, davidjoy commented on src/courseware/course/InstructorToolbar.jsx
> +            <a className="btn d-block btn-outline-light" href={urlLms}>View in the existing experience</a>
@marcotuts - Do we need the paragraph of text still?  Just sanity-checking.

2020-05-14 22:31 UTC, stvstnfrd commented on .env.test
> -SEGMENT_KEY=null
I may have subconsciously done that :)

I didn't actually mean to merge it like that, though I think I was thinking:
> I bet we don't need to redefine those since they _should_ inherit from `.env`

:)

Anyway, it's since been restored.

2020-05-14 22:31 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +      urlFull += `/${courseId}`;
Re: fallback

Yeah, exactly. The idea is that worst case (assuming `courseId` is missing in error, not by intent) you're inconvenienced by going to the dashboard and picking out your course, instead of a getting a broken link that doesn't take you where you want (and probably 404s).

2020-05-14 22:31 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +            <a className="btn d-block btn-outline-light" href={urlLms}>View in the existing experience</a>
@davidjoy and @marcotuts Ah yeah, good catch. I think I nuked it in preparation of the masquerade toolbar and didn't revisit. I can restore it for now and then pull it when masquerade bar lands?

2020-05-15 14:14 UTC, davidjoy commented on src/index.jsx
> +        'INSIGHTS_BASE_URL': process.env.INSIGHTS_BASE_URL || '',
I think, for me, I'd only use an empty string if I expected to do some string manipulation on it even though it's "empty"... otherwise I think I'd expect these to just be set to null.

2020-05-15 14:15 UTC, davidjoy approved these changes
I think we still have a small decision to make about allowing INSIGHTS_BASE_URL and STUDIO_BASE_URL to be optional, but in principle this PR is good to go, I think.

2020-05-15 17:16 UTC, marcotuts commented on src/courseware/course/InstructorToolbar.jsx
> +            <a className="btn d-block btn-outline-light" href={urlLms}>View in the existing experience</a>
meh, ok to remove starting now. leave as is :) thanks!

2020-05-15 17:16 UTC, marcotuts commented on src/courseware/course/InstructorToolbar.jsx
> +            <a className="btn d-block btn-outline-light" href={urlLms}>View in the existing experience</a>
(if you already restored it that's fine too. it'll go away at the latest with the masquerade work.)

2020-05-15 17:27 UTC, stvstnfrd commented on src/courseware/course/InstructorToolbar.jsx
> +            <a className="btn d-block btn-outline-light" href={urlLms}>View in the existing experience</a>
Nope, still gone, will stay gone then!

2020-05-15 18:54 UTC, stvstnfrd commented on src/index.jsx
> +        'INSIGHTS_BASE_URL': process.env.INSIGHTS_BASE_URL || '',
`null` it is!

2020-05-15 21:25 UTC, merged