Resume from last completed unit
openedx/frontend-app-learning pull request #66
Opened 2020-05-11 15:24 UTC by davestgermain

[TNL-7203](https://openedx.atlassian.net/browse/TNL-7203)

2020-05-13 15:37 UTC, davidjoy commented on src/data/thunks.js
> +export function fetchResumeBlock(courseId) {
I'd remove this and call `getResumeBlock` directly in the component.  A thunk is only necessary/appropriate for actions being `dispatch`'d to redux.  Since we're not changing redux's state with this request, we don't need a thunk.

2020-05-13 15:39 UTC, davidjoy commented on src/data/api.js
> +  return data;
If you change the keys from `section` and `unit` to `section_id` and `unit_id` in the edx-platform PR, it'd be appropriate to camelCase them here so that the rest of the app sees them as `sectionId` and `unitId.

2020-05-13 15:39 UTC, davidjoy requested changes
Few small cleanup things, otherwise looks great!

2020-05-14 14:02 UTC, davestgermain commented on src/data/thunks.js
> +export function fetchResumeBlock(courseId) {
Ok, I got rid of the `thunks` indirection.

2020-05-14 15:16 UTC, davidjoy approved these changes

2020-05-14 15:17 UTC, merged