Create masquerade widget component
openedx/frontend-app-learning pull request #71
Opened 2020-05-20 17:43 UTC by stvstnfrd

on the Staff Instructor Toolbar

2020-05-20 18:30 UTC, davidjoy commented on src/courseware/course/masquerade-widget/index.jsx
> +class MasqueradeWidget extends Component {
Fyi - the convention we've been following is for the index.jsx file for a module to merely define the public API for that module, and for the component to be in a file where the filename matches the component name - i.e., MasqueradeWidget.jsx

2020-05-20 18:36 UTC, davidjoy commented on src/courseware/course/masquerade-widget/utils.jsx
> +import React from 'react';
Hmm, I think what we might want to do here is to just create a `<MasqueradeOptions>` component that we pass some props into, rather than moving these into a utils file.  The handleClick function, iterating over the available options, rendering the items, that's all classic component stuff.  In MasqueradeWidget, where you're putting `{options}` in the dropdown menu, you'd just put <MasqueradeOptions {...theRightProps} /> in there instead.  Would be much more canonical.  I think we tend to use 'utils' files for random helper functions that are reused in a few places and otherwise don't fit anywhere else - i.e., they're not an api call, or a thunk, a reducer, or a selector, etc.

2020-05-20 18:37 UTC, davidjoy requested changes
A few code organization things, mostly... I think there are some more familiar patterns we can use.  Otherwise looks good.

2020-06-02 16:11 UTC, stvstnfrd reviewed
@davidjoy Addressed the file naming issue, left a comment about the `utils` file; let me know what you think.

2020-06-02 16:11 UTC, stvstnfrd commented on src/courseware/course/masquerade-widget/index.jsx
> +class MasqueradeWidget extends Component {
Renamed in upcoming commit.

2020-06-02 16:11 UTC, stvstnfrd commented on src/courseware/course/masquerade-widget/utils.jsx
> +import React from 'react';
Heh, so funny story here...

I totally agree that it's all classic component stuff, so much so that I originally wrote those functions as instance methods on `MasqueradeWidget`!
But after some refactoring, I was never referencing instance state (`this`) in the methods, so I just made them state-less functions (in the `MasqueradeWidget.jsx` file) (I don't know if `eslint` enforces this, but `pylint` _does_ check for instance methods that don't touch `self`). Then I got to thinking, since the class doesn't need to share its state with these functions, and it even only needs one of them, I figured I'd move the helpers to their own module and then just import the single one we need.

That said, I'd prefer to _not_ create a new component just for this; `MasqueradeWidget` is thin as it is.
Let me know if you feel strongly otherwise.

So I can move these back as stateless in `MasqueradeWidget.jsx`.
We _could_ add them to the `class`, but that seems a bit dirty :shrug:

2020-06-02 19:05 UTC, davidjoy commented on src/courseware/course/masquerade-widget/utils.jsx
> +import React from 'react';
Hmm, a component that doesn't reference `this` is actually a prime example of an old school functional component before hooks. :D  

Put another way - `parseAvailableOption` is already a functional component because it's returning JSX that's getting rendered - it just happens to be in a file named utils.jsx instead of something like "AvailableOptions.jsx".  So... you _did_ create a component just for it! :) 

Now that I'm reading a bit closer, the `handleClick` is relying on data props, which isn't generally done in React.  If it were declared inside the functional component as a handler (with or without the `useCallback` hook), it'd have access to all that via lexical scoping, which is the canonical way that's done.  

Even `isSelected` could do its work via lexical scoping, rather than by passing props in, but I don't feel strongly about that/it may be clearer how it is currently.

But, er, yeah, now that I'm reading, I feel pretty strongly that you already have a component here, masquerading as utils. :)

2020-06-03 06:51 UTC, stvstnfrd commented on src/courseware/course/masquerade-widget/utils.jsx
> +import React from 'react';
> Put another way - `parseAvailableOption` is already a functional component because it's returning JSX that's getting rendered - it just happens to be in a file named utils.jsx instead of something like "AvailableOptions.jsx". So... you _did_ create a component just for it! :)

Alright, alright, I see it now ;)
 
> Now that I'm reading a bit closer, the `handleClick` is relying on data props, which isn't generally done in React. If it were declared inside the functional component as a handler (with or without the `useCallback` hook), it'd have access to all that via lexical scoping, which is the canonical way that's done.

Soooo, the reason I wanted to remove `handleClick` from the closure was that we'd need to iterate over that in a loop and I'd generally prefer to avoid creating `n` copies of a function with separate closures, than to just have a single function/method.

But I agree, `data-*` props is not the way to do this, old habits and all, so I've turned this into an official component.
I opted for a class-based component, for consistency w/ the other new component here, plus to avoid creating `handleClick` in a loop ;)

> Even `isSelected` could do its work via lexical scoping, rather than by passing props in, but I don't feel strongly about that/it may be clearer how it is currently.

It's now an instance method :)

> But, er, yeah, now that I'm reading, I feel pretty strongly that you already have a component here, masquerading as utils. :)

Reimplemented as `MasqueradeWidgetOption.jsx`.

2020-06-03 06:57 UTC, stvstnfrd reviewed
@davidjoy Alright, no more utils ;)

2020-06-03 15:42 UTC, davidjoy approved these changes

2020-06-12 07:46 UTC, stvstnfrd commented on src/courseware/course/sequence/Unit.jsx
> +      { contentTypeGatingEnabled && unit.graded && (
@davidjoy This is the one other change needed here (since your original +1).

The backend now determines entirely whether or not content type gating should be enabled for this course for this user, accounting for masquerade settings.
We no longer want to check the user's enrollment track here because during masquerade it's either:
- misleading (eg: a staff user in the audit track), or
- missing (eg: "Limited Access")

2020-06-19 16:59 UTC, merged