feat: Sidebar refactor and add support for discussions sidebar [BD-38]
openedx/frontend-app-learning pull request #762
Opened 2021-12-07 12:13 UTC by xitij2000

2021-12-07 12:13 UTC, edx-webhook commented
Thanks for the pull request, @xitij2000! I've created [BLENDED-1037](https://openedx.atlassian.net/browse/BLENDED-1037) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


When this pull request is ready, tag your edX technical lead.


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-12-08 10:48 UTC, xitij2000 commented
@davidjoy 
Would love to get your feedback on this given your work on frontend plugins. 
This is refactoring the sidebar code and adding a new discussions sidebar. Ideally I'd like to do this in a way that's pluggable down the line. I've tried to do this somewhat, and can see a mechanism where a plugin can provide an Icon component for the trigger and a sidebar component for the sidebar. How would that work with the current iframe approach?

2022-01-11 13:27 UTC, asadazam93 commented
@xitij2000 Can you please rebase and fix tests?

2022-01-12 08:22 UTC, xitij2000 commented
> @xitij2000 Can you please rebase and fix tests?

I would like to get some feedback on the approach etc before we invest more time on this. This is an active repo and the testing here is complex so I'd like to get some feedback on the technical approach etc before I add that.

2022-01-18 14:50 UTC, mehaknasir requested changes

2022-01-18 14:50 UTC, mehaknasir commented on src/courseware/course/Course.test.jsx
> +    expect(notificationTrigger.parentNode).not.toHaveClass('border-primary-700');
I can see that the test cases were written using class selectors before as well. but I feel this is not a good approach to ensure if something is visible on screen. can we change that to test ids, please?

2022-01-18 14:50 UTC, mehaknasir commented on src/courseware/course/sequence/Sequence.jsx
> +      <div className={classNames('sequence', { 'position-relative': shouldDisplayTriggers })} style={{ width: '100%' }}>
can be replaced with `w-100` bootstrap class

2022-01-18 14:50 UTC, mehaknasir commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
> +    setLocalStorage(`upgradeNotificationCurrentState.${courseId}`, 'initialize');
saving in local storage? what if the user changes the browser? or cleans the local storage? isn't it these notifications states will become invalid?

2022-01-18 14:50 UTC, mehaknasir commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
> +    setLocalStorage(`upgradeNotificationCurrentState.${courseId}`, 'initialize');
I feel this should be implemented at the backend where the storage is not under users' control.

2022-01-19 05:14 UTC, xitij2000 commented on src/courseware/course/Course.test.jsx
> +    expect(notificationTrigger.parentNode).not.toHaveClass('border-primary-700');
@mehaknasir  That only works if a node is added/removed. The absence or presence of a class is what needs to be tested here. The result of this click should be that the element is highlighted using a css class. So I'm not sure how test ids apply here?

2022-01-19 05:16 UTC, xitij2000 commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
> +    setLocalStorage(`upgradeNotificationCurrentState.${courseId}`, 'initialize');
This is not my code but the result of refactoring existing code from here: https://github.com/openedx/frontend-app-learning/pull/762/files#diff-459583d559f1b0d02db79555b95569eca3de1431dc7ac86d842aefc3972203e4L52-L78

I am not at liberty to change this code.

2022-01-19 05:18 UTC, xitij2000 commented on src/courseware/course/sequence/Sequence.jsx
> +      <div className={classNames('sequence', { 'position-relative': shouldDisplayTriggers })} style={{ width: '100%' }}>
I am not fully aware of the reasoning for the original style clause. I'm trying to avoid making any changes to code that I did not write so as to avoid unexpected issues.

2022-01-19 15:06 UTC, davidjoy commented on src/courseware/course/sidebar/common/SidebarBase.scss
> +.sidebar-container {
I'd expect we could use bootstrap utility classes for nearly everything in this file, and then they'd align with our best practices and be brandable.  As a best practice, I think we want to create custom scss files only when strictly necessary so we can lean into our design system.

2022-01-19 17:47 UTC, awais-ansari commented on src/courseware/course/sequence/Sequence.jsx
> +      <div className={classNames('sequence', { 'position-relative': shouldDisplayTriggers })} style={{ width: '100%' }}>
<div className={classNames('sequence', { 'position-relative': shouldDisplayTriggers })} style={{ width: '100%' }}>
 <div className={classNames('sequence w-100', { 'position-relative': shouldDisplayTriggers })}>
style clause and w-100 have same effect and precedence. We just need to replace it. It will not create any unexpected issue.

2022-01-19 17:47 UTC, awais-ansari commented on src/courseware/course/Course.test.jsx
> +    expect(notificationTrigger.parentNode).not.toHaveClass('border-primary-700');
yes, It's good practice not to use classes as selectors in test cases but according to the situation, we only have this option here.

2022-01-19 19:29 UTC, marcotuts commented on src/courseware/course/sidebar/SidebarContextProvider.jsx
> +    setLocalStorage(`upgradeNotificationCurrentState.${courseId}`, 'initialize');
Ok to leave in place existing requirements here like this one unless we hear otherwise from owners of the features, if that makes sense.

2022-01-19 21:34 UTC, ciduarte reviewed
Reviewing on behalf of Engage Squad. Mostly a11y and styling comments.

Additionally, I'd appreciate either screenshots or a video demo of how the Sidebar looks in the mobile view. Let's confirm whether the responsive behavior is appropriate before merging.

2022-01-19 21:34 UTC, ciduarte commented on src/courseware/course/sequence/Sequence.jsx
> +      <div className={classNames('sequence', { 'position-relative': shouldDisplayTriggers })} style={{ width: '100%' }}>
+1

2022-01-19 21:34 UTC, ciduarte commented on src/courseware/course/sidebar/common/SidebarBase.scss
> +.sidebar-container {
+1, for reference, you can find how our utility classes map to the styling in this file here https://paragon-openedx.netlify.app/foundations/css-utilities/

2022-01-19 21:34 UTC, ciduarte commented on src/courseware/course/sidebar/sidebars/notifications/NotificationTray.scss
> +    font-size: 0.875rem;
Similar to David's comment above, we should use the Bootstrap/Paragon utility classes where possible, especially for fonts so they align with our design system.

In this case, the font utility class would be `small` which maps to `0.875rem`. The padding utility class would be `p-3` which translates to `1rem`.

For reference: https://paragon-openedx.netlify.app/foundations/css-utilities/

2022-01-19 21:34 UTC, ciduarte commented on src/courseware/course/sidebar/sidebars/notifications/NotificationIcon.scss
>      border-radius: 50% !important;
`border-radius: 50%;` can be replaced with the CSS utility class `rounded-circle`

`padding: 0.25rem` can be replaced with `p-1`

2022-01-19 21:34 UTC, ciduarte commented on src/courseware/course/sidebar/sidebars/discussions/messages.js
> +  discussionsTray: {
I see this is being used as the aria label in the DiscussionsSidebar. I'd argue we could just use `discussionsTitle` as the aria label. Announcing that something is a "sidebar" feels unnecessary, given the semantic meaning of `<section />`.

2022-01-19 21:34 UTC, ciduarte commented on src/courseware/course/sidebar/sidebars/discussions/messages.js
> +    description: 'Title text displayed for the discussions sidebar',
These descriptions are used to give translators more context so they can find the appropriate translations. Can we change this description to "Title text for a forum where users are able to discuss course topics"

2022-01-19 21:34 UTC, ciduarte commented on src/courseware/course/sidebar/sidebars/discussions/messages.js
> +    description: 'Button to open the discussions tray and show discussions',
Can we change this description to "Alt text for a button that opens the Discussions feature"

2022-01-19 21:34 UTC, ciduarte commented on src/courseware/course/sidebar/sidebars/discussions/DiscussionsTrigger.jsx
> +    <SidebarTriggerBase onClick={onClick} ariaLabel={intl.formatMessage(messages.openDiscussionsTrigger)}>
Should we also have alt text that says "Close discussions tray"?

2022-01-20 09:12 UTC, xitij2000 commented on src/courseware/course/sidebar/sidebars/notifications/NotificationIcon.scss
>      border-radius: 50% !important;
@ciduarte There are a couple of cases where there is no direct match. In those cases, does it make sense to swap it out for the closest matching class?

2022-01-20 09:13 UTC, xitij2000 commented on src/courseware/course/sidebar/sidebars/notifications/NotificationTray.scss
> +    font-size: 0.875rem;
Will do.

2022-01-26 10:28 UTC, xitij2000 commented on src/courseware/course/sidebar/sidebars/discussions/DiscussionsTrigger.jsx
> +    <SidebarTriggerBase onClick={onClick} ariaLabel={intl.formatMessage(messages.openDiscussionsTrigger)}>
The close button for the discussions MFE is hosted by the MFE itself, so the text will live there.

2022-02-14 21:47 UTC, Cup0fCoffee requested changes

2022-02-14 21:47 UTC, Cup0fCoffee commented on src/courseware/course/NotificationTray.scss
>      border-bottom: 1px solid $light-400;
```suggestion
    border-bottom: 1px solid $light-400;
}
```

2022-02-14 21:50 UTC, Cup0fCoffee commented
:+1:

- [x] I tested this
- [x] I read through the code

2022-02-15 17:11 UTC, mehaknasir commented
@xitij2000 if you can resolve conflicts and finalise I will post the final review.

2022-02-25 05:27 UTC, xitij2000 commented
@mehaknasir  I've updated the PR and fixed the issues. It is ready for another look.

2022-03-01 01:54 UTC, Cup0fCoffee commented
:+1: Reviewed again after changes which started using the new topics API

- [x] I tested this
- [x] I read through the code

2022-03-01 14:08 UTC, mehaknasir approved these changes

2022-03-02 07:22 UTC, xitij2000 commented
@mehaknasir Could you merge this?

2022-03-04 06:23 UTC, asadazam93 commented
@xitij2000 Can you please check why the tests are not running?

2022-03-04 14:28 UTC, xitij2000 commented
@asadazam93  I squashed and pushed again, and the tests have run this time.

2022-03-07 13:50 UTC, xitij2000 commented
@asadazam93 To avoid needing to refactor this again if things change, we should merge this soon.

2022-03-07 13:56 UTC, merged

2022-03-07 13:56 UTC, edx-webhook commented
@xitij2000 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/762&entry.1484655318=https://github.com/xitij2000&entry.752974735=2021-12-07+12:13&entry.1917517419=2022-03-07+13:56&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->