fix: [AA-1076] show grade override notice
openedx/frontend-app-learning pull request #773
Opened 2021-12-13 20:26 UTC by cdeery

- Progress page indicates if a grade has been overridden

2021-12-14 14:01 UTC, mikix requested changes

2021-12-14 14:01 UTC, mikix commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
We are moving away from using FontAwesome icons to paragon icons (which may or may not use FA under the covers, I'm not 100% - I believe it has some icons that FA does not?):
- https://edx.github.io/paragon/components/icon
- https://edx.github.io/paragon/foundations/icons

So something like:
```
import { Icon } from '@edx/paragon';
import { Info } from '@edx/paragon/icons';

<Icon src={Info} />
```

(which here, means you can add just Icon to the already imported list of icons above)

2021-12-14 14:01 UTC, mikix commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +              <div data-testid="override-message">{intl.formatMessage(messages.sectionGradeOverridden)}</div>
The testid looks leftover from a previous test attempt - I'd drop it though, as it's unused and would end up in resulting DOM.

2021-12-14 22:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/ProgressTab.test.jsx
> +      setTabData({
Not sure if this is possible, but are you able to override a smaller subset of the tab data here? I feel bad for ya having to write all this when I think we only care about one small part. Maybe even by taking the existing tab data and just doing something like `tabData.section_scores[1].subsections.push(...)` and then just add the one thing of the override. Or maybe even `tabData.section_scores[1].subsections[0].override = ...;`.

I think it could help the readability of this test as well if that's possible so it's easier to see exactly what we care about in the tab data.

2021-12-14 22:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/grades/messages.js
> +  },
👏

2021-12-14 22:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +              <div data-testid="override-message">{intl.formatMessage(messages.sectionGradeOverridden)}</div>
I don't think you need the data-testid here. I don't think your test is using it. Maybe consult Carla on this point.

2021-12-14 22:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +            <div className="row w-100 m-0 x-small ml-4 pt-2 pl-1 text-gray-700 flex-nowrap">
Might be worth having Carla take a look at this because I'm definitely not the one to speak on it, but looks fine to me

2021-12-14 22:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +            <div className="row w-100 m-0 x-small ml-4 pt-2 pl-1 text-gray-700 flex-nowrap">
Do you need the `w-100` here if you already have it on the parent div? And I just realized it's on the collapsible.body as well. I think you might be able to drop both.

2021-12-14 22:35 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +    }),
Do you know if we have plans on using these fields?

2021-12-14 22:36 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +              <div data-testid="override-message">{intl.formatMessage(messages.sectionGradeOverridden)}</div>
Don't know why this didn't show up when I was reviewing the code, but +1 here

2021-12-15 14:45 UTC, cdeery commented on src/course-home/progress-tab/ProgressTab.test.jsx
> +      setTabData({
I kept adding stuff to make the warnings being thrown by the test go away.

2021-12-15 14:59 UTC, Dillon-Dumesnil commented on src/course-home/progress-tab/ProgressTab.test.jsx
> +      setTabData({
Oof. Okay, took a look at the code and see that that method sets what the axios call will respond so yes, better to set it all there. That being said, I believe you only need to `section_scores` (see test "renders correct total weighted grade when showGrades is false" for an example) since I think the only part you care about is setting the override. Should at least help with some of the cruft.

2021-12-15 15:00 UTC, cdeery commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +              <div data-testid="override-message">{intl.formatMessage(messages.sectionGradeOverridden)}</div>
It was leftover from a different testing approach. removed.

2021-12-15 21:33 UTC, cdeery commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
I originally tried to used the Paragon info icon, but I could not get it to resize smaller, and it was super easy with FontAwesome. How do I resize a paragon icon?

2021-12-15 21:34 UTC, cdeery commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +              <div data-testid="override-message">{intl.formatMessage(messages.sectionGradeOverridden)}</div>
Done

2021-12-15 21:34 UTC, cdeery commented on src/course-home/progress-tab/grades/messages.js
> +  },
I thought you would like that!

2021-12-15 22:01 UTC, cdeery commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +    }),
Thanks for the reminder. I was going to see if we wanted them in a tooltip for the info icon

2021-12-16 16:18 UTC, mikix commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +              <div data-testid="override-message">{intl.formatMessage(messages.sectionGradeOverridden)}</div>
Did you forget to push up? I still se the testid.

2021-12-16 16:21 UTC, mikix commented on src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
The paragon docs linked above have an example:
```
  <Icon src={Add} className="text-white" style={{ height: '48px', width: '48px' }} />
```

Which seems like a very manual way to do it, but :shrug:. Does that work?

2021-12-21 15:48 UTC, mikix approved these changes

2021-12-21 19:07 UTC, merged