AA-133 mfe dates banner
openedx/frontend-app-learning pull request #79
Opened 2020-06-10 17:30 UTC by xnick421

- dates banner on dates tab

2020-06-12 18:14 UTC, mikix commented on src/dates-banner/messages.js
> +  'datesBanner.datesTabInfoBanner.header': {
I know you are copying from the TNL team's messages file. But look at what I do in the dates-tab message file for example (and this is also what the react-intl docs do).

Repeating the id as the message key is pointless and makes it harder to use. Instead, you can simply do:

```
defineMessags({
  header: {
    id: 'datesBanner.datesTabInfoBanner.header',
    ...
  }, ...
}
```

Then simply `intl.formatMessage(messages.header)` instead of an akward `intl.formatMessage(messages['datesBanner.datesTabInfoBanner.header'])`.

But after writing all that, I see that you dynamically generate the lookup id. So less good advice for your use case. But leaving this here as general advice.

2020-06-12 18:14 UTC, mikix commented on src/dates-banner/DatesBannerContainer.jsx
> +    },
Why not this one in one line like the others? And why specify model and courseId?

2020-06-12 18:14 UTC, mikix commented on src/dates-banner/DatesBanner.jsx
> +    if (name === 'resetDatesBanner') {
Checking name like this is kinda breaking component boundaries. Now this lower down component has to know the name of an upper component.

Could you have maybe... an `onClick` prop passed to `DatesBanner` that gets handled in `DatesBannerContainer`? Maybe as a property in the banner dictionaries.

2020-06-12 18:14 UTC, mikix commented on src/dates-banner/DatesBanner.jsx
> +        {name !== 'datesTabInfoBanner' && (
Same comment here. Maybe if you added an onClick prop, you could use whether that's defined or not to decide whether to show a button.

2020-06-12 18:14 UTC, mikix commented on src/data/api.js
> +  return camelCaseObject(data);
Is there actually data returned from this? If not, might just not want to return anything.

2020-06-12 18:14 UTC, mikix commented on src/data/api.js
> +export async function getCourseHomeCourseMetadata(courseId) {
Oh I thought we were already using this endpoint. I guess not...

2020-06-12 18:14 UTC, mikix commented on src/data/thunks.js
> +      getCourseHomeCourseMetadata(courseId),
This was originally intended as a replacement for `getCourseMetadata` for tabs I think. You should be able to just one-line replace it above and then skip the rest of the changes to this method.

2020-06-12 18:14 UTC, mikix commented on src/data/thunks.js
> +      }
Rather than having to have a switch statement here, why not just pass down the `fetch` prop to `TabContainer` all the way down to this `resetDeadlines` call? Then it can just call the right fetch method without any knowledge of what the various tabs are.

2020-06-12 19:13 UTC, ciduarte reviewed
Just passing through.. one small nit. MT brought up some good points.

I didn't know that `messages.js` file existed, or that any of that implementation existed for i18n, so glad I browsed. Good learning moment.

2020-06-12 19:13 UTC, ciduarte commented on src/data/api.js
> +export async function getCourseHomeCourseMetadata(courseId) {
nit: Could we rename this to `getCourseHomeMetadata`? Or is that not specific enough

2020-06-15 14:11 UTC, davidjoy commented on src/dates-banner/messages.js
> +  'datesBanner.datesTabInfoBanner.header': {
Nice, I hadn't fully thought through that you could simplify it this way.

2020-06-15 14:17 UTC, davidjoy requested changes

2020-06-15 14:17 UTC, davidjoy commented on src/dates-banner/DatesBanner.scss
> +.banner {
If at all possible, we should try to use the Bootstrap utility classes here, especially for borders/background colors/margins.  One, it keeps it all standardized and lookin' nice, and two, it's easily update-able when we do a rebrand or it's themed in Open edX instances.

2020-06-15 14:17 UTC, davidjoy commented on src/dates-banner/DatesBanner.scss
> +.banner {
I'm not sure exactly which colors these are, but hopefully they're in our existing color palette!  It also helps make sure we're meeting our a11y requirements.

2020-06-15 18:11 UTC, davidjoy approved these changes

2020-06-16 13:55 UTC, merged