refactor: remove and reduce usage of SCSS variables
openedx/frontend-app-learning pull request #942
Opened 2022-05-05 12:57 UTC by xitij2000

This PR replaces usages of scss variables with closest equivalent classes. The aim is to be visually identical. 

There are places where this is not possible, and I hope this PR can start a discussion about what to do in those cases.

2022-05-05 12:58 UTC, openedx-webhooks commented
Thanks for the pull request, @xitij2000! I've created [OSPR-6659](https://openedx.atlassian.net/browse/OSPR-6659) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-05-06 18:20 UTC, natabene commented
@xitij2000 Thank you for your contribution. Is this ready for our review?

2022-05-13 06:16 UTC, xitij2000 commented
> @xitij2000 Thank you for your contribution. Is this ready for our review?

Not yet, I think I might break this into two PRs.

2022-05-16 04:26 UTC, tecoholic approved these changes
@xitij2000 :+1: with the small fixes for the duplicates

- [x] I tested this: Built the front-end, visited various pages to check if the elements are styled appropriately  & verified that most are as expected.
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] Includes documentation - NA

2022-05-16 04:26 UTC, tecoholic commented on src/course-home/outline-tab/widgets/FlagButton.scss
>    box-shadow: 0 0 0 2px $light-400;
```suggestion
```
Looks like a duplicate style definition.

2022-05-16 04:26 UTC, tecoholic commented on src/course-home/outline-tab/widgets/FlagButton.scss
>      border: 1px solid $primary-300;
```suggestion
```
Another duplicate definition

2022-05-16 04:26 UTC, tecoholic commented on src/course-home/outline-tab/widgets/FlagButton.scss
>    box-shadow: 0 0 0 2px $primary-300;
```suggestion
```
Another duplicate definition.

2022-05-18 10:22 UTC, xitij2000 commented on src/course-home/outline-tab/widgets/FlagButton.scss
>    box-shadow: 0 0 0 2px $light-400;
@tecoholic Yes, in this case, the issue is that color-mix isn't supported currently, so this is more of a forward-looking change, but a better solution would be to just create css variables for colour mixes like --light-400 etc. 

I think it's worth discussing, and adding this to paragon.

2022-06-08 15:57 UTC, natabene commented
Just checking if it still not ready.

2022-06-16 10:27 UTC, xitij2000 commented
> Just checking if it still not ready.

I'm currently preparing an ADR that could impact this PR, so will come back to it once that work is ready.

2022-08-18 16:33 UTC, natabene commented
@xitij2000 Just wanted to check if this is still not ready.

2022-10-12 14:47 UTC, itsjeyd commented
Hey @xitij2000, do you have any updates about this PR? Is it ready for review now, or perhaps no longer relevant?

2022-10-27 11:29 UTC, itsjeyd commented
@xitij2000 Friendly ping about the status of this PR :) Is it ready for review or should we close it?

2022-10-27 12:08 UTC, xitij2000 commented
> @xitij2000 Friendly ping about the status of this PR :) Is it ready for review or should we close it?

Sorry for the delay. I've been recovering from illness recently and am trying to juggle quite a bit. I'll update these PRs next sprint.

2022-10-28 09:11 UTC, itsjeyd commented
@xitij2000 Sounds good! Thanks for the update.

2022-11-25 11:07 UTC, xitij2000 commented
> @xitij2000 Just wanted to check if this is still not ready.

This is ready now.

2022-12-05 14:06 UTC, ProductRyan commented
Adding to our internal JIRA for tracking:
https://2u-internal.atlassian.net/browse/AU-941

2023-01-06 12:01 UTC, itsjeyd commented
@ProductRyan Just checking in to see if you had any updates on when we could expect a review for this PR?

@xitij2000 In the meantime could you address the merge conflicts that came up here?

2023-01-10 13:41 UTC, leangseu-edx commented on src/generic/upsell-bullets/UpsellBullets.jsx
> -    <li className="upsell-bullet">
I would prefer this to remain `upsell-bullet`. Although the styling is trivial, we might use it as selector.

2023-01-10 13:46 UTC, leangseu-edx commented on src/generic/upgrade-notification/UpgradeNotification.jsx
> -    <ul className="fa-ul upgrade-notification-ul pt-0">
Even if you remove `upgrade-notification-ul` style completely, I think these name should remain.

2023-01-10 13:48 UTC, leangseu-edx requested changes
I would ask you to preserve some of the className. Especially for those with class name of `upsell` and `upgrade`. They might be use for analytics.

2023-01-24 16:19 UTC, itsjeyd commented
@xitij2000 Friendly ping on this. Looks like it's pretty close to being ready for merge :)

2023-02-08 10:01 UTC, itsjeyd commented
Hey @xitij2000, when you get a minute could you please post an update on when you expect to get back to this PR?

2023-02-24 04:09 UTC, xitij2000 commented
> Hey @xitij2000, when you get a minute could you please post an update on when you expect to get back to this PR?

Since the creation of this PR, there have been new developments on the paragon side, with design tokens that will provide a better path for this kind of work. So I can close this PR for now and re-open when this can be rebased on that work.

2023-02-24 04:09 UTC, closed without merging

2023-02-24 04:09 UTC, openedx-webhooks commented
@xitij2000 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/942&entry.1484655318=https://github.com/xitij2000&entry.752974735=2022-05-05+12:57&entry.1917517419=2023-02-24+04:09&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->