feat: [VAN-1000] - Set weekly goal through welcome email via query param
openedx/frontend-app-learning pull request #956
Opened 2022-07-14 05:17 UTC by shafqatfarhan

**Description**
Set weekly goa via query param and delete param to avoid setting it multiple times.

**Ticket**
https://2u-internal.atlassian.net/browse/VAN-1000

2022-07-18 03:21 UTC, zainab-amir approved these changes

2022-07-18 14:04 UTC, cdeery requested changes
A couple of comments

2022-07-18 14:04 UTC, cdeery commented on src/course-home/outline-tab/widgets/WeeklyLearningGoalCard.jsx
> +      handleSelect(weeklyGoal, true);
I think the input needs to be checked for correct values before it is consumed.

2022-07-18 14:04 UTC, cdeery commented on src/course-home/outline-tab/widgets/WeeklyLearningGoalCard.jsx
>      setGetReminderSelected(selectReminders);
Am I correct that the expectation here is that if the learner does not want to be subscribed to email reminders then they have the opportunity to do that when they go to the page? Does the focus need to be set to the unsubscribe button? How would users with assistive technology know they could unsubscribe?

2022-07-20 03:31 UTC, shafqatfarhan commented on src/course-home/outline-tab/widgets/WeeklyLearningGoalCard.jsx
> +      handleSelect(weeklyGoal, true);
done

2022-07-20 03:55 UTC, shafqatfarhan commented on src/course-home/outline-tab/widgets/WeeklyLearningGoalCard.jsx
>      setGetReminderSelected(selectReminders);
Yes, learners have an option to unsubscribe to reminder emails. Currently, the focus is not set to the unsubscribe button even when the user manually sets the goal from the UI.

To support assistive technology, we are already setting the `aria-checked` attribute to indicate the currently selected weekly goal button in their group.

2022-07-20 03:56 UTC, shafqatfarhan commented
@cdeery PR is ready for review again. Thanks.

2022-07-25 17:37 UTC, cdeery approved these changes
Thanks for the changes. Looks good

2022-07-26 04:07 UTC, merged