fix: fix alignment in the streak celebration modal
openedx/frontend-app-learning pull request #975
Opened 2022-09-12 15:40 UTC by ihor-romaniuk

**Description:**
Fix alignment in the streak celebration modal. The reason for the error is the upgrade of the paragon library from version `16.14.9` to `19.14.1`.

**Current behaviour:** 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/17108583/189695000-b5bc94d6-23f1-4b82-be39-6c9a83a3ee95.png">

**Fixed behaviour:** 
<img width="526" alt="fixed" src="https://user-images.githubusercontent.com/17108583/189694438-aff56165-d1fe-4e34-a6bb-0119170122e1.png">

2022-09-12 15:40 UTC, openedx-webhooks commented
Thanks for the pull request, @ihor-romaniuk!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-09-19 15:49 UTC, natabene commented
@ihor-romaniuk Thank you for the contribution.

2022-10-27 09:53 UTC, itsjeyd commented
@ihor-romaniuk Just to confirm: This PR is ready for review, right?

2022-10-27 13:19 UTC, ihor-romaniuk commented
@itsjeyd Yes. It's ready for review.

2022-12-05 14:17 UTC, ProductRyan commented
Is this a dupe of https://github.com/openedx/frontend-app-learning/pull/974 ?

2022-12-06 14:02 UTC, itsjeyd commented
@ProductRyan It looks like #974 is targeting Nutmeg while this PR is targeting master. That seems to be the main difference between the two PRs.

@ihor-romaniuk Please correct me if I'm wrong :)

2022-12-08 16:27 UTC, ihor-romaniuk commented
@itsjeyd Yes. You are absolutely right. This PR is targeting the master branch. 
Can I make any links for such PRs in the future to simplify reviewing and merging them?

2022-12-09 10:15 UTC, itsjeyd commented
@ihor-romaniuk 

> Can I make any links for such PRs in the future to simplify reviewing and merging them?

Good question! A good option is to list related PRs (and/or dependencies) in the PR description, under a suitable heading. For example:

> ## Description
> ...
> ## Other information
> ...
> ### Dependencies
> * #1234
> * #5678
> ### Related PRs
> * #2323
> * #4242

This example builds on the official [Pull Request Template](https://github.com/openedx/edx-platform/blob/master/.github/pull_request_template.md) for edx-platform.

It's always a good idea to use that template for your PRs, as it will help you include all the information that reviewers are happy to see.

2022-12-15 10:15 UTC, itsjeyd commented
Hi @ProductRyan, now that we've [confirmed](https://github.com/openedx/frontend-app-learning/pull/975#issuecomment-1342980988) that this PR is not a duplicate of #974, could we get it lined up for review by the engineering team as well?

2023-01-06 11:22 UTC, itsjeyd commented
Hey @ProductRyan, just checking in to see if you had a chance to create an AU ticket for this PR and line it up for review (?).

CC @mattcarter

2023-01-12 14:41 UTC, ProductRyan commented
@ihor-romaniuk @itsjeyd - This looks good from product POV. I've created an internal JIRA ticket Aurora eng review.
https://2u-internal.atlassian.net/browse/AU-997

2023-01-13 13:29 UTC, itsjeyd commented
Great, thank you @ProductRyan!

2023-01-24 15:55 UTC, itsjeyd commented
(Re-adding `product review` label since we decided not to remove it from PRs including user-facing changes.)

2023-01-24 16:46 UTC, leangseu-edx requested changes
LGTM 👍

2023-01-24 16:47 UTC, leangseu-edx approved these changes

2023-01-24 16:47 UTC, merged

2023-01-24 16:47 UTC, openedx-webhooks commented
@ihor-romaniuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learning&entry.867055334=https://github.com/openedx/frontend-app-learning/pull/975&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2022-09-12+15:40&entry.1917517419=2023-01-24+16:47&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->